ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=superio

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/CommonFiles

METAFILE=superio.$(META)

SOURCESLIST=Sources.List

VCPROJ=superio.vcproj

include $(ROOT)/Makefiles/Make.Plugin
