ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=timer

INCLUDES= \
	$(ROOT)/include/Prague \
	$(ROOT)/include \
	$(ROOT)/CommonFiles

STDLIBS= $(THREADSLIB)

METAFILE=timer.$(META)

SOURCESLIST=Sources.List

VCPROJ=timer.vcproj

include $(ROOT)/Makefiles/Make.Plugin
