#define VER_INTERNALNAME_STR		"KLBG" 
#define VER_FILEDESCRIPTION_STR		"KLBG Mini-Filter"
#define VER_INTERNALEXTENSION_STR	"SYS"

#define VER_FILETYPE				VFT_DRV
#define VER_FILESUBTYPE				VFT2_DRV_SYSTEM

#define VER_FILEVERSION_HIGH		8
#define VER_FILEVERSION_LOW			0
#define VER_FILEVERSION_BUILD	6
#define VER_FILEVERSION_COMPILATION	2

#include <version/ver_product.h>
