ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=avlib

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/AV \
	$(ROOT)/include/Extract \
	$(ROOT)/include/ProductCore \
	$(ROOT)/CommonFiles

VCPROJ=avlib.vcproj

SOURCESLIST=Sources.List

include $(ROOT)/Makefiles/Make.Plugin
