ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=report

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/ProductCore \
	$(ROOT)/CommonFiles

METAFILE=report.$(META)

VCPROJ=report.vcproj

SOURCESLIST=Sources.List

include $(ROOT)/Makefiles/Make.Plugin
