ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=util

INCLUDES= \
	$(ROOT)/CommonFiles \
	$(ROOT)/include/Prague \
	$(ROOT)/include

METAFILE=PrUtil.meta

SOURCESLIST=Sources.List

VCPROJ=Util.vcproj

include $(ROOT)/Makefiles/Make.Plugin
