ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=passdmap

INCLUDES= \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/include \
	$(ROOT)/CommonFiles

METAFILE=passdmap.$(META)

SOURCESLIST=Sources.List

VCPROJ=passdmap.vcproj

include $(ROOT)/Makefiles/Make.Plugin
