ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=unarj

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/CommonFiles \

METAFILE=unarj.$(META)

SOURCESLIST=Sources.List

VCPROJ=unarj.vcproj

include $(ROOT)/Makefiles/Make.Plugin
