#ifndef __PIDSERROR_H__
#define __PIDSERROR_H__

#include <winerror.h>

#define FACILITY_PRAGUE_IDS 0xa00

#define PIDS_E_INTERNALERROR				MAKE_HRESULT(11,FACILITY_PRAGUE_IDS,1)
#define PIDS_E_OUTOFORDER					MAKE_HRESULT(11,FACILITY_PRAGUE_IDS,2)
#define PIDS_E_INCORRECTCATEGORY			MAKE_HRESULT(11,FACILITY_PRAGUE_IDS,3)
#define PIDS_E_EMPTYRANGE					MAKE_HRESULT(11,FACILITY_PRAGUE_IDS,4)
#define PIDS_E_OUTOFRANGE					MAKE_HRESULT(11,FACILITY_PRAGUE_IDS,5)
#define PIDS_E_USER_NOT_REGISTERED			MAKE_HRESULT(11,FACILITY_PRAGUE_IDS,6)
#define PIDS_E_SQL							MAKE_HRESULT(11,FACILITY_PRAGUE_IDS,7)


#endif // __PISERROR_H__