#ifndef __PISRVERROR_H__
#define __PISRVERROR_H__

#include <winerror.h>

#define FACILITY_PRAGUE_ISRV 0xb00

#define PISRV_E_INTERNALERROR								MAKE_HRESULT(11,FACILITY_PRAGUE_ISRV,1)
#define PISRV_E_OUTOFORDER									MAKE_HRESULT(11,FACILITY_PRAGUE_ISRV,2)
#define PISRV_E_HASNOTCONNECTED							MAKE_HRESULT(11,FACILITY_PRAGUE_ISRV,3)
#define PISRV_E_MEMORYALLOCATIONERROR				MAKE_HRESULT(11,FACILITY_PRAGUE_ISRV,4)
#define PISRV_E_DIFFERENTTYPES							MAKE_HRESULT(11,FACILITY_PRAGUE_ISRV,5)
#define PISRV_E_SAVECONTAINER							  MAKE_HRESULT(11,FACILITY_PRAGUE_ISRV,6)
#define PISRV_E_SAVERESERVECOPY					    MAKE_HRESULT(11,FACILITY_PRAGUE_ISRV,7)
#define PISRV_E_CONNECTION									MAKE_HRESULT(11,FACILITY_PRAGUE_ISRV,8)
#define PISRV_E_INTNOTFOUND  								MAKE_HRESULT(11,FACILITY_PRAGUE_ISRV,9)
#define PISRV_E_SAVEDESCRIPTIONDB						MAKE_HRESULT(11,FACILITY_PRAGUE_ISRV,10)
#define PISRV_E_UIOWNER   									MAKE_HRESULT(11,FACILITY_PRAGUE_ISRV,11)


#endif // __PISERROR_H__