ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=ntreelib

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/klava \
	$(ROOT)/CommonFiles

VCPROJ=ntreelib.vcproj

SOURCESLIST=Sources.List

include $(ROOT)/Makefiles/Make.Archive
