ROOT:=../../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=updater2005

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/ProductCore \
	$(ROOT)/include/AV \
	$(ROOT)/include/Prague \
	$(ROOT)/include/PPP/ \
	$(ROOT)/CommonFiles 

DEFINES= \

LIBRARIES= \
	Updater \
	compatutils \

DEPS= \
	

METAFILE=./UpdaterTask/updater2005.$(META)

VCPROJ=updater2005.vcproj

SOURCESLIST=Sources.List

include $(ROOT)/Makefiles/Make.Plugin
