ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=tempfile

INCLUDES= \
	$(ROOT)/include/Prague \
	$(ROOT)/include \
	$(ROOT)/CommonFiles

METAFILE=tempfile.$(META)

SOURCESLIST=Sources.List

VCPROJ=TempFile.vcproj

include $(ROOT)/Makefiles/Make.Plugin
