ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=avpmgr

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/AV \
	$(ROOT)/include/Extract \
	$(ROOT)/include/ProductCore \
	$(ROOT)/AVP32 \
	$(ROOT)/CommonFiles

METAFILE=AvpMgr.$(META)

SOURCESLIST=Sources.List

VCPROJ=AvpMgr.vcproj

include $(ROOT)/Makefiles/Make.Plugin
