ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=cu_test

INCLUDES = \
	$(ROOT)/include \
	$(ROOT)/CommonFiles

SOURCES= \
	main.cpp


include $(ROOT)/Makefiles/Make.Executable
