ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=oas

INCLUDES= \
	${ROOT}/include \
	${ROOT}/CommonFiles

DEPS= \
	

METAFILE=oas.$(META)

VCPROJ=oas.vcproj

SOURCESLIST=Sources.List
		
include $(ROOT)/Makefiles/Make.Plugin
