ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=unreduce

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/CommonFiles

METAFILE=unreduce_trans.$(META)

SOURCESLIST=Sources.List

VCPROJ=unreduce.vcproj

include $(ROOT)/Makefiles/Make.Plugin
