//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CKAHUMTESTUI2.rc
//
#define IDR_MANIFEST                    1
#define IDC_Clear                       2
#define IDS_NO_RULE                     2
#define IDS_FAILEDTORESOLVEHOST         3
#define IDC_Clear2                      3
#define IDS_PROMPT_RESTORE_DEFAULT      4
#define IDD_CKAHUMTESTUI2_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDD_PACKETRULES                 130
#define IDD_PACKETRULE                  131
#define IDD_PORT                        133
#define IDD_ADDRESSLIST                 134
#define IDD_ADDRESS                     135
#define IDD_NEWADDRESS                  136
#define IDD_APPRULES                    137
#define IDD_APPRULE                     138
#define IDD_CR_CONSOLE                  140
#define IDD_APPRULEELT                  141
#define IDD_BANOMET                     142
#define IDD_HostStat                    143
#define IDD_ConnDialog                  144
#define IDD_TIMES                       145
#define IDD_TIME                        146
#define IDD_TIMEELT                     147
#define IDD_RedirectorExcludes          148
#define IDC_START                       1000
#define IDC_RELOAD                      1001
#define IDC_STOP                        1002
#define IDC_PAUSE                       1003
#define IDC_RESUME                      1004
#define IDC_RELOADPATH                  1005
#define IDC_SETPARAM                    1006
#define IDC_GETPARAM                    1007
#define IDC_SetParamID                  1008
#define IDC_SetParamNum                 1009
#define IDC_SetParamValue               1010
#define IDC_Result                      1011
#define IDC_GetParamID                  1012
#define IDC_GetParamNum                 1013
#define IDC_GetParamValue               1014
#define IDC_GETPARAMCOUNT               1015
#define IDC_GetParamCountID             1016
#define IDC_GetParamCountValue          1017
#define IDC_ATTACKLIST                  1018
#define IDC_SETIDSPARAM                 1019
#define IDC_SetIDSParamID               1020
#define IDC_SetIDSPar_Deny              1021
#define IDC_SetIDSPar_Notify            1022
#define IDC_SetIDSPar_Log               1023
#define IDC_SetIDSPar_Ban               1024
#define IDC_EDIT1                       1025
#define IDC_STM_START                   1026
#define IDC_STM_STOP                    1027
#define IDC_IPADDRESS1                  1028
#define IDC_IPADDRESS2                  1029
#define IDC_Unban                       1030
#define IDC_STM_Pause                   1031
#define IDC_STM_Resume                  1032
#define IDC_FW_START                    1033
#define IDC_FW_STOP                     1034
#define IDC_FW_PAUSE                    1035
#define IDC_FW_RESUME                   1036
#define IDC_CKAHUMPAUSE                 1037
#define IDC_CKAHUMRESUME                1038
#define IDC_NETLIST                     1039
#define IDC_UpdateNetList               1040
#define IDC_FW_PACKETRULES              1041
#define IDC_FW_APPRULES                 1042
#define IDC_OpenPortList                1043
#define IDC_UpdateOpenPortList          1044
#define IDC_CKAHUMENABLE                1045
#define IDC_LIST2                       1046
#define IDC_CKAHUMDISABLE               1046
#define IDC_OpenConnectionList          1047
#define IDC_AddPacketRule               1047
#define IDC_UpdateOpenConnectionList    1048
#define IDC_PacketRuleName              1048
#define IDC_EditPacketRule              1048
#define IDC_BreakConnection             1049
#define IDC_EnablePacket                1049
#define IDC_DeletePacketRule            1049
#define IDC_BlockPacketRule             1050
#define IDC_RestorePacketRule           1050
#define IDC_CR_START                    1050
#define IDC_AppPath                     1051
#define IDC_CR_STOP                     1051
#define IDC_ProtoPacket                 1052
#define IDC_CR_Pause                    1052
#define IDC_CmdLine                     1052
#define IDC_NotifyPacket                1053
#define IDC_CR_Resume                   1053
#define IDC_LogPacket                   1054
#define IDC_CR_Console                  1054
#define IDC_TRACELOG                    1055
#define IDC_ProtoPacket3                1056
#define IDC_GetBannedList               1056
#define IDC_ProtoPacket2                1057
#define IDC_ConnList                    1057
#define IDC_StmChange                   1058
#define IDC_DirIncomingPacket           1061
#define IDC_DirOutgoingPacket           1062
#define IDC_DirBothPacket               1063
#define IDC_DirIncomingStream           1064
#define IDC_DirOutgoingStream           1065
#define IDC_DirBothStream               1066
#define IDC_SingleValue                 1068
#define IDC_RangeLoValue                1069
#define IDC_AddressList                 1069
#define IDC_RangeHiValue                1070
#define IDC_AddAddress                  1070
#define IDC_SinglePort                  1071
#define IDC_DeleteAddress               1071
#define IDC_PortRange                   1072
#define IDC_RemotePortList              1073
#define IDC_AddRemotePort               1074
#define IDC_DeleteRemotePort            1075
#define IDC_LocalPortList               1076
#define IDC_Name                        1076
#define IDC_AddLocalPort                1077
#define IDC_DeleteLocalPort             1078
#define IDC_RemoteAddressList           1079
#define IDC_AddRemoteAddress            1080
#define IDC_RangeFrom                   1080
#define IDC_DeleteRemoteAddress         1081
#define IDC_RangeTo                     1081
#define IDC_LocalAddressList            1082
#define IDC_SubnetIP                    1082
#define IDC_AddLocalAddress             1083
#define IDC_SubnetMask                  1083
#define IDC_DeleteLocalAddress          1084
#define IDC_HostAddress                 1085
#define IDC_EditLocalAddress            1085
#define IDC_AddressRange                1086
#define IDC_EditRemoteAddress           1086
#define IDC_AddressSubnet               1087
#define IDC_EditLocalPort               1087
#define IDC_HostIPList                  1088
#define IDC_EditRemotePort              1088
#define IDC_HostIPListAdd               1089
#define IDC_HostIPListClear             1090
#define IDC_HostIPorName                1090
#define IDC_RULELIST                    1091
#define IDC_AddApplicationRule          1092
#define IDC_EditApplicationRule         1093
#define IDC_DeleteApplicationRule       1094
#define IDC_BrowseApp                   1095
#define IDC_TCPInCheck                  1096
#define IDC_TCPInRemoteAddressList      1097
#define IDC_TCPInAddRemoteAddress       1098
#define IDC_TCPInEditRemoteAddress      1099
#define IDC_TCPInDeleteRemoteAddress    1100
#define IDC_TCPInRemotePortList         1101
#define IDC_TCPInAddRemotePort          1102
#define IDC_TCPInEditRemotePort         1103
#define IDC_TCPInDeleteRemotePort       1104
#define IDC_TCPInLocalPortList          1105
#define IDC_TCPInAddLocalPort           1106
#define IDC_TCPInEditLocalPort          1107
#define IDC_TCPInDeleteLocalPort        1108
#define IDC_TCPOutCheck                 1109
#define IDC_TCPOutRemoteAddressList     1110
#define IDC_TCPOutAddRemoteAddress      1111
#define IDC_TCPOutEditRemoteAddress     1112
#define IDC_TCPOutDeleteRemoteAddress   1113
#define IDC_TCPOutRemotePortList        1114
#define IDC_TCPOutAddRemotePort         1115
#define IDC_TCPOutEditRemotePort        1116
#define IDC_TCPOutDeleteRemotePort      1117
#define IDC_TCPOutLocalPortList         1118
#define IDC_TCPOutAddLocalPort          1119
#define IDC_TCPOutEditLocalPort         1120
#define IDC_TCPOutDeleteLocalPort       1121
#define IDC_UDPInCheck                  1122
#define IDC_UDPInRemoteAddressList      1123
#define IDC_UDPInAddRemoteAddress       1124
#define IDC_UDPInEditRemoteAddress      1125
#define IDC_UDPInDeleteRemoteAddress    1126
#define IDC_UDPInRemotePortList         1127
#define IDC_UDPInAddRemotePort          1128
#define IDC_UDPInEditRemotePort         1129
#define IDC_UDPInDeleteRemotePort       1130
#define IDC_UDPInLocalPortList          1131
#define IDC_UDPInAddLocalPort           1132
#define IDC_UDPInEditLocalPort          1133
#define IDC_UDPInDeleteLocalPort        1134
#define IDC_UDPOutCheck                 1135
#define IDC_UDPOutRemoteAddressList     1136
#define IDC_UDPOutAddRemoteAddress      1137
#define IDC_UDPOutEditRemoteAddress     1138
#define IDC_UDPOutDeleteRemoteAddress   1139
#define IDC_UDPOutRemotePortList        1140
#define IDC_UDPOutAddRemotePort         1141
#define IDC_UDPOutEditRemotePort        1142
#define IDC_UDPOutDeleteRemotePort      1143
#define IDC_UDPOutLocalPortList         1144
#define IDC_UDPOutAddLocalPort          1145
#define IDC_UDPOutEditLocalPort         1146
#define IDC_UDPOutDeleteLocalPort       1147
#define IDC_AppRuleName                 1148
#define IDC_BlockAppRule                1149
#define IDC_NotifyApp                   1150
#define IDC_EnableApp                   1151
#define IDC_FWLEVEL                     1152
#define IDC_LogApp                      1152
#define IDC_RestoreApplicationRule      1153
#define IDC_IsCmdLine                   1153
#define IDC_Console                     1155
#define IDC_CR_CONSOLE_PORT             1158
#define IDC_Enable                      1159
#define IDC_ELTLIST                     1160
#define IDC_AddElement                  1161
#define IDC_EditElement                 1162
#define IDC_DeleteElement               1163
#define IDC_BANNED_LIST                 1165
#define IDC_HostStat                    1166
#define IDC_HOST_STAT                   1167
#define IDC_OpenConnList                1169
#define IDC_Times                       1171
#define IDC_TimesList                   1173
#define IDC_AddTime                     1175
#define IDC_EditTime                    1176
#define IDC_DeleteTime                  1177
#define IDC_AddTimeElt                  1178
#define IDC_EditTimeElt                 1179
#define IDC_DeleteTimeElt               1180
#define IDC_TimeList                    1181
#define IDC_TimeSeconds                 1182
#define IDC_TimeDaySeconds              1183
#define IDC_TimeMinutes                 1184
#define IDC_TimeHours                   1185
#define IDC_TimeDays                    1186
#define IDC_TimeWeekDays                1187
#define IDC_TimeMonths                  1188
#define IDC_TimeYears                   1189
#define IDC_TimeMax                     1190
#define IDC_TimeMin                     1191
#define IDC_CR_Watchdog                 1192
#define IDC_RecalcHash                  1193
#define IDC_CR_Watchdog2                1194
#define IDC_EXCLUDES_LIST               1198
#define IDC_ADD_EXCLUDE                 1199
#define IDC_REMOVE_EXCLUDE              1200
#define IDC_EDIT_HOST                   1201
#define IDC_EDIT_PORT                   1202
#define IDC_EDIT_PATH                   1203

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1204
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
