#define AGetTrueHandle      __CTS_func_TH
#define AMemAlloc           __CTS_func_MA
#define AMemCoreleft        __CTS_func_MC
#define AMemFree            __CTS_func_MF
#define ASC_Decode          __CTS_func_CD_
#define ASC_DecodeEnd       __CTS_func_CDF
#define ASC_DecodeInit      __CTS_func_CDI
#define ASC_Encode          __CTS_func_CE_
#define ASC_EncodeEnd       __CTS_func_CEF
#define ASC_EncodeInit      __CTS_func_CEI
#define Aclose              __CTS_func_FC
#define Aopen               __CTS_func_FO
#define Aread               __CTS_func_FR
#define Aseek               __CTS_func_FS
#define Atell               __CTS_func_FT
#define Awrite              __CTS_func_FW
#define Bin2Hex             __CTS_func_BH
#define CloseTouchPort      __CTS_func_CTP
#define CreateRandomValues  __CTS_func_RV
#define Crypto              __CTS_func_CR
#define DecodeBuffer        __CTS_func_CDB
#define DecodeConstructor   __CTS_func_CDC
#define DecodeDestructor    __CTS_func_CDD
#define DecodeEnd           __CTS_func_CDE
#define EncodeBuffer        __CTS_func_CEB
#define EncodeConstructor   __CTS_func_CEC
#define EncodeDestructor    __CTS_func_CED
#define EncodeEnd           __CTS_func_CEE
#define FindStr             __CTS_func_FF
#define GetGostKey          __CTS_func_GGK
#define GetURandValue       __CTS_func_RG
#define GostCode            __CTS_func_GC
#define GostDecode          __CTS_func_GD
#define Hex2Bin             __CTS_func_HB
#define InitFind            __CTS_func_FI
#define InitTouchPort       __CTS_func_TI
#define Randomize           __CTS_func_RN
#define ReadTouchRAM        __CTS_func_RT
#define ReadTouchROM        __CTS_func_TO
#define SetCryptoBlock      __CTS_func_SG
#define SetGostKey          __CTS_func_SGK
#define SetURandValue       __CTS_func_RS
#define URand               __CTS_func_RD
#define UUDecode            __CTS_func_UD
#define UUDecodeInit        __CTS_func_UI
#define UUEncode            __CTS_func_UE
#define UUEncodeEnd         __CTS_func_UF
#define UUEncodeInit        __CTS_func_UB
#define VerifySN            __CTS_func_VS
#define VestaBuffer         __CTS_func_VB
#define VestaInit           __CTS_func_VI
#define WriteTouchRAM       __CTS_func_WT
#define _dsign_rf           __CTS_func_DR
#define _dsign_sh           __CTS_func_SD
#define _dsign_us           __CTS_func_DU
#define _invert_afn         __CTS_func_AI
#define _modilp_afn         __CTS_func_AM
#define _not_rf             __CTS_func_NR
#define _not_sh             __CTS_func_SO
#define _not_us             __CTS_func_NU
#define _reg_rf             __CTS_func_RR
#define _reg_sh             __CTS_func_SE
#define _reg_us             __CTS_func_RU
#define _sign_rf            __CTS_func_SR
#define _sign_us            __CTS_func_SU
#define _signa_sh           __CTS_func_SA
#define _signb_sh           __CTS_func_SB
#define ac_end_encode       __CTS_func_CAE
#define ac_in               __CTS_func_CAN
#define ac_init_decode      __CTS_func_CAD
#define ac_init_encode      __CTS_func_CAI
#define ac_out              __CTS_func_CAO
#define ac_threshold_val    __CTS_func_CAT
#define afin1               __CTS_func_A1
#define afin2               __CTS_func_A2
#define asc_cleanup         __CTS_func_CAC
#define crc32               __CTS_func_C5
#define createrandfile      __CTS_func_CT
#define decrypr             __CTS_func_DS
#define gcrypt              __CTS_func_GR
#define getstat             __CTS_func_GS
#define modilq_rf           __CTS_func_MR
#define modilq_us           __CTS_func_MU
#define randname            __CTS_func_RF
#define removerandfile      __CTS_func_RE
#define splitname           __CTS_func_SN
#define swd_accept          __CTS_func_CSP
#define swd_alloc           __CTS_func_CSA
#define swd_cleanup         __CTS_func_CSC
#define swd_dchar           __CTS_func_CSS
#define swd_dinit           __CTS_func_CSD
#define swd_dpair           __CTS_func_CSR
#define swd_findbest        __CTS_func_CSF
#define swd_init            __CTS_func_CSI
#define updaterandfile      __CTS_func_UR
#define updcrc16f           __CTS_func_CF

#define crc16( ptr, len )   updcrc16f( 0, ptr, len )

#define __add_bufin         __CTS_variable_BI
#define __add_bufout        __CTS_variable_BO
#define __add_cur           __CTS_variable_AC
#define __asc_byte          __CTS_variable_AB
#define __asc_flag          __CTS_variable_AF
#define __asc_pos           __CTS_variable_AP
#define __ib                __CTS_variable_IB
#define __ibf               __CTS_variable_IF
#define __ibl               __CTS_variable_IL
#define __n_bufin           __CTS_variable_NI
#define __n_bufout          __CTS_variable_NO
#define __ob                __CTS_variable_OB
#define __obl               __CTS_variable_OL
#define __outlen            __CTS_variable_OT
#define swd_bpos            __CTS_variable_SB
#define swd_char            __CTS_variable_SC
#define swd_mlf             __CTS_variable_SM

