ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=sign

INCLUDES= \
	. \
	..

SOURCES= \
	signlib.unix/my_strl.c \
	signlib.unix/n_constr.c \
	signlib.unix/n_sha.c \
	signlib.unix/n_shnor.c \
	signlib.unix/n_signsh.c \
	signlib.unix/s_buflen.c \
	signlib.unix/s_chbuf.c \
	signlib.unix/s_check.c \
	signlib.unix/s_chfile.c \
	signlib.unix/s_chfres.c \
	signlib.unix/s_chres.c \
	signlib.unix/s_cnot.c \
	signlib.unix/s_crpriv.c \
	signlib.unix/s_except.c \
	signlib.unix/s_fnguid.c \
	signlib.unix/s_fnstr.c \
	signlib.unix/s_hash.c \
	signlib.unix/s_klok.c \
	signlib.unix/s_lnfile.c \
	signlib.unix/s_lnot.c \
	signlib.unix/s_putn.c \
	signlib.unix/s_sgnfil.c \
	signlib.unix/s_sgnmem.c \
	signlib.unix/s_sifile.c \
	signlib.unix/s_sign.c \
	signlib.unix/s_spkey.c \
	signlib.unix/s_strver.c \
	../Stuff/TEXT2BIN.c

include $(ROOT)/Makefiles/Make.Archive
