/* Generated by Together */
#include "stdafx.h"
#include <string>
#include "HttpResponse.h"
#include "ContentImp.h"

namespace OnlineActivation
{
///////////////////////////////////////////////////////////////////////////////
ContentImp::ContentImp(const boost::shared_ptr<HttpResponse>& pResponse)
	: m_pResponse(pResponse)
{
}
///////////////////////////////////////////////////////////////////////////////
Content::ContentType ContentImp::GetType() const
{
	const std::string& contentType = m_pResponse->GetContentType();
	// translate content type
	if (contentType == "text/html")
		return CONTENT_HTML;
	if (contentType == "application/octet-stream")
		return CONTENT_BINARY;
	return CONTENT_OTHER;
}
///////////////////////////////////////////////////////////////////////////////
const void* ContentImp::GetData() const
{
	return m_pResponse->GetData();
}
///////////////////////////////////////////////////////////////////////////////
size_t ContentImp::GetDataSize() const
{
	return m_pResponse->GetDataSize();
}
///////////////////////////////////////////////////////////////////////////////
}