 /* Generated by Together */

#include "stdafx.h"

#include "WinInternet.h"
#include "HttpRequest.h"
#include "HttpConnection.h"

namespace OnlineActivation
{

//-----------------------------------------------------------------------------

HttpConnection::HttpConnection
(
	InternetHandle& hSession,
	const char* lpszServerName,
	INTERNET_PORT nServerPort
)
{
	m_hConnection = WinInternet::Connect
	(
		hSession, 
		lpszServerName, 
		nServerPort, 
		NULL, 
		NULL, 
		INTERNET_SERVICE_HTTP, 
		0, 
		NULL
	);
}

//-----------------------------------------------------------------------------

boost::shared_ptr<HttpRequest> HttpConnection::CreateRequest
(
	HttpRequest::VerbType nVerb,
	const char* lpszResource,
	DWORD dwFlags
)
{
	return boost::shared_ptr<HttpRequest>
		(new HttpRequest(m_hConnection, nVerb, lpszResource, dwFlags));
}

//-----------------------------------------------------------------------------

} // namespace OnlineActivation
