/* Generated by Together */

#ifndef _AG_HTTPRESPONSE_H_
#define _AG_HTTPRESPONSE_H_

#include <vector>
#include "InternetHandle.h"

namespace OnlineActivation
{

class HttpResponse
{
public:

	HttpResponse(InternetHandle& hResponse);

	unsigned short GetStatusCode();

	std::string GetContentType();

	const void* GetData() const;

	size_t GetDataSize() const;

private:

	InternetHandle m_hResponse;

	std::vector<unsigned char> m_data;
};

} // namespace OnlineActivation

#endif //_AG_HTTPRESPONSE_H_
