/* Generated by Together */

#ifndef _AG_HTTPCONNECTION_H_
#define _AG_HTTPCONNECTION_H_

#include "HttpRequest.h"

namespace OnlineActivation
{
/**
 * Internet connection. 
 */
class HttpConnection
{
public: 

	/**
	 * Constructs HttpConnection object. 
	 */
	HttpConnection
	(
		InternetHandle& hSession,
		const char* lpszServerName,
		INTERNET_PORT nServerPort
	);

	/**
	 * Creates request.
	 */
	boost::shared_ptr<HttpRequest> CreateRequest
	(
		HttpRequest::VerbType nVerb,
		const char* lpszResource,
		DWORD dwFlags
	);

private:
	
	InternetHandle	m_hConnection;

	/** @link dependency 
	 * @stereotype instantiate*/
	/*# HttpRequest lnkHttpRequest; */
};

} // namespace OnlineActivation

#endif //_AG_HTTPCONNECTION_H_
