/* Generated by Together */

#include "stdafx.h"

#include "WinInternet.h"
#include "HttpConnection.h"
#include "InternetSession.h"


namespace OnlineActivation
{
///////////////////////////////////////////////////////////////////////////////
InternetSession::InternetSession
(
	const char* szAgent, 
	DWORD dwAccessType, 
	const char* szProxyName, 
	const char* szProxyBypass 
)
{
	// create session with configuration read from registry
	m_hSession = WinInternet::Open
		(szAgent, dwAccessType, szProxyName, szProxyBypass, 0);
}
///////////////////////////////////////////////////////////////////////////////
boost::shared_ptr<HttpConnection> InternetSession::CreateConnection
(
	const char* szServerName,
	INTERNET_PORT nServerPort
)
{
	return boost::shared_ptr<HttpConnection>
		(new HttpConnection(m_hSession, szServerName, nServerPort));
}
///////////////////////////////////////////////////////////////////////////////
} // namespace OnlineActivation
