/* Generated by Together */

#ifndef _AG_REQUESTDATA_H_
#define _AG_REQUESTDATA_H_

#include <vector>

namespace OnlineActivation
{

class RequestData
{
public:
	RequestData(const char* szHeaders, const void* pData, size_t nSize);
	const char*  GetHeaders() const;
	const size_t GetHeadersLength() const;
	const void*  GetData() const;
	const size_t GetDataSize() const;
private:
	std::string m_headers;
	std::vector<unsigned char> m_data;
};

}
#endif // _AG_REQUESTDATA_H_
