/* Generated by Together */

#include "stdafx.h"
#include "RequestData.h"

namespace OnlineActivation
{
///////////////////////////////////////////////////////////////////////////////
RequestData::RequestData(const char* szHeaders, const void* pData, size_t nSize)
	: m_headers(szHeaders)
	, m_data
	(
		reinterpret_cast<const unsigned char*>(pData), 
		reinterpret_cast<const unsigned char*>(pData) + nSize
	)
{
}
///////////////////////////////////////////////////////////////////////////////
const char* RequestData::GetHeaders() const
{
	return m_headers.c_str();
}
///////////////////////////////////////////////////////////////////////////////
const size_t RequestData::GetHeadersLength() const
{
	return m_headers.length();
}
///////////////////////////////////////////////////////////////////////////////
const void* RequestData::GetData() const
{
	return m_data.empty() ? 0 : &m_data[0];
}
///////////////////////////////////////////////////////////////////////////////
const size_t RequestData::GetDataSize() const
{
	return m_data.size();
}
///////////////////////////////////////////////////////////////////////////////
} // namespace OnlineActivation