ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=klavprlib

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/klava \
	$(ROOT)/include/klava/bases \
	$(ROOT)/include/Prague \
	$(ROOT)/include/AV \
	$(ROOT)/CommonFiles

VCPROJ=klavprlib.vcproj

SOURCESLIST=Sources.List

include $(ROOT)/Makefiles/Make.Archive

