program avz;
uses
  system,
  Forms,
  windows,
  ntdll,
  SysUtils,
  Unit1 in 'Unit1.pas' {Main},
  uAboutDLG in 'uAboutDLG.pas' {AboutDLG},
  uInfectedView in 'uInfectedView.pas' {InfectedView},
  uProcessView in 'uProcessView.pas' {ProcessView},
  uServiceView in 'uServiceView.pas' {ServiceView},
  uSPIView in 'uSPIView.pas' {SPIView},
  zSharedFunctions in '..\zSharedFunctions.pas',
  uRegSearch in 'uRegSearch.pas' {RegSearch},
  zPELoader in 'zPELoader.pas',
  zStringCompressor in '..\zStringCompressor.pas',
  zLSP in 'zLSP.pas',
  uOpenPorts in 'uOpenPorts.pas' {NetOpenPorts},
  zIPPorts in 'zIPPorts.pas',
  uFileSearch in 'uFileSearch.pas' {FileSearchDLG},
  zVirFileList in 'zVirFileList.pas',
  uExtLogView in 'uExtLogView.pas' {ExtLogView},
  uLast in 'uLast.pas' {Last},
  zServices in 'zServices.pas',
  zProcess in 'zProcess.pas',
  uNetShares in 'uNetShares.pas' {NetShares},
  uAutoruns in 'uAutoruns.pas' {Autoruns},
  zVBAMacros in 'zVBAMacros.pas',
  zAutoruns in 'zAutoruns.pas',
  uFileCountThread in 'uFileCountThread.pas',
  uSysCheck in 'uSysCheck.pas' {SysCheck},
  zKernelMode in 'zKernelMode.pas',
  zAVZDriverN in 'zAVZDriverN.pas',
  uKernelObjectsView in 'uKernelObjectsView.pas' {KernelObjectsView},
  uBackupScripts in 'uBackupScripts.pas' {BackupScriptsDLG},
  zProcessMemory in 'zProcessMemory.pas',
  zHTMLTemplate in 'zHTMLTemplate.pas',
  uAutoQurantine in 'uAutoQurantine.pas' {AutoQurantine},
  zBHO in 'zBHO.pas',
  uExplorerExtManager in 'uExplorerExtManager.pas' {ExplorerExtManager},
  uDeleteModeDLG in 'uDeleteModeDLG.pas' {DeleteModeDLG},
  zAVZArcKernel in 'zAVZArcKernel.pas',
  zCHMUnpacker in 'unpack\CHM\zCHMUnpacker.pas',
  zEmailUnpacker in 'unpack\MAIL\zEmailUnpacker.pas',
  uFileDeleteModeDLG in 'uFileDeleteModeDLG.pas' {FileDeleteModeDLG},
  zExplorerExt in 'zExplorerExt.pas',
  uPrintExtManager in 'uPrintExtManager.pas' {PrintExtManager},
  uQurantineByList in 'uQurantineByList.pas' {QurantineByList},
  zUserScripting in 'zUserScripting.pas',
  uKeyloggerManager in 'uKeyloggerManager.pas' {KeyloggerManager},
  uBHOManager in 'uBHOManager.pas' {BHOManager},
  zPrintExt in 'zPrintExt.pas',
  uAutoUpdate in 'uAutoUpdate.pas' {AutoUpdate},
  zAutoUpdate in '..\zAutoUpdate.pas',
  uTaskScheduler in 'uTaskScheduler.pas' {TaskScheduler},
  zTaskScheduler in 'zTaskScheduler.pas',
  zHostsFile in 'zHostsFile.pas',
  uHostsManager in 'uHostsManager.pas' {HostsManager},
  zCRC32 in '..\zCRC32.pas',
  uAutoUpdateSetup in 'uAutoUpdateSetup.pas' {AutoUpdateSetup},
  zFileHandles in 'zFileHandles.pas',
  zESScripting in 'zESScripting.pas',
  zUnRar in 'unpack\RAR\zUnRar.pas',
  uCookies in 'uCookies.pas' {CookiesSearch},
  uTextReportView in 'uTextReportView.pas' {TxtLogView},
  zFileSearch in 'zFileSearch.pas',
  uExecProcessDLG in 'uExecProcessDLG.pas' {ExecProcessDLG},
  zKeyloggerHunter in 'zKeyloggerHunter.pas',
  uProtocolManager in 'uProtocolManager.pas' {ProtocolManager},
  zProtocols in 'zProtocols.pas',
  uSystemRepair in 'uSystemRepair.pas' {SysRepair},
  uRevizor in 'uRevizor.pas' {RevizorDLG},
  uDPFManager in 'uDPFManager.pas' {DPFManager},
  zDPF in 'zDPF.pas',
  uCPLManager in 'uCPLManager.pas' {CPLManager},
  zCPLExt in 'zCPLExt.pas',
  zDirectFileCopy in 'zDirectFileCopy.pas',
  uSelectDeletedFile in 'uSelectDeletedFile.pas' {SelectDeletedFile},
  uRunScript in 'uRunScript.pas' {RunScriptDLG},
  zNtRegistry in '..\zNtRegistry.pas',
  uActiveSetup in 'uActiveSetup.pas' {ActiveSetupManager},
  zActiveSetup in 'zActiveSetup.pas',
  zLogSystem in 'zLogSystem.pas',
  zAVKernel in '..\zAVKernel.pas',
  zScriptingKernel in 'zScriptingKernel.pas',
  zAVZKernel in 'zAVZKernel.pas',
  zAVZVersion in '..\zAVZVersion.pas',
  uGUIShared in 'uGUIShared.pas' {GUIShared},
  zTranslate in 'zTranslate.pas',
  uStdScripts in 'uStdScripts.pas' {StdScriptsDLG},
  zCodepageFix in 'zCodepageFix.pas',
  uRepairWizard in 'uRepairWizard.pas' {RepairWizard},
  zBackupEngine in 'zBackupEngine.pas',
  zIEAPI in 'zIEAPI.pas',
  zXMLLogger in 'zXMLLogger.pas';

{$R *.RES}
begin
  ZSetThreadLocale(LOCALE_SYSTEM_DEFAULT);
  Application.Initialize;
  ZSetThreadLocale(LOCALE_SYSTEM_DEFAULT);
//  ZSetThreadLocale(1049);
  Application.CreateForm(TMain, Main);
  Application.CreateForm(TExtLogView, ExtLogView);
  Application.CreateForm(TQurantineByList, QurantineByList);
  Application.CreateForm(TLast, Last);
  Application.Run;
end.

