/* soapH.h
   Generated by gSOAP 2.7.0d from soapheader.h
   Copyright (C) 2001-2004 Genivia, Inc. All Rights Reserved.
   This software is released under one of the following three licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
   See README.txt for further details.
*/
#ifndef soapH_H
#define soapH_H
#include "soapStub.h"

SOAP_BEGIN_NAMESPACE(soap)
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_resolve_attachments(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);

SOAP_FMAC3 void SOAP_FMAC4 soap_fdelete(struct soap_clist*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_xsd__byte
#define SOAP_TYPE_xsd__byte (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__byte(struct soap*, char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__byte(struct soap*, char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_xsd__byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_xsd__byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_byte(struct soap*, char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_xsd__short
#define SOAP_TYPE_xsd__short (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__short(struct soap*, short *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__short(struct soap*, short const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__short(struct soap*, const short *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__short(struct soap*, const char*, int, const short *, const char*);
SOAP_FMAC3 short * SOAP_FMAC4 soap_get_xsd__short(struct soap*, short *, const char*, const char*);
SOAP_FMAC3 short * SOAP_FMAC4 soap_in_xsd__short(struct soap*, const char*, short *, const char*);

#ifndef SOAP_TYPE_short
#define SOAP_TYPE_short (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_short(struct soap*, short *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_short(struct soap*, short const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_short(struct soap*, const short *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_short(struct soap*, const char*, int, const short *, const char*);
SOAP_FMAC3 short * SOAP_FMAC4 soap_get_short(struct soap*, short *, const char*, const char*);
SOAP_FMAC3 short * SOAP_FMAC4 soap_in_short(struct soap*, const char*, short *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_int(struct soap*, int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__int(struct soap*, long *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__int(struct soap*, long const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__int(struct soap*, const long *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__int(struct soap*, const char*, int, const long *, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_get_xsd__int(struct soap*, long *, const char*, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_in_xsd__int(struct soap*, const char*, long *, const char*);

#ifndef SOAP_TYPE_long
#define SOAP_TYPE_long (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_long(struct soap*, long *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_long(struct soap*, long const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_long(struct soap*, const long *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_long(struct soap*, const char*, int, const long *, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_get_long(struct soap*, long *, const char*, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_in_long(struct soap*, const char*, long *, const char*);

#ifndef SOAP_TYPE_xsd__long
#define SOAP_TYPE_xsd__long (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__long(struct soap*, LONG64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__long(struct soap*, LONG64 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__long(struct soap*, const LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__long(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_xsd__long(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_xsd__long(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_LONG64(struct soap*, LONG64 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_xsd__float
#define SOAP_TYPE_xsd__float (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__float(struct soap*, float *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__float(struct soap*, float const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__float(struct soap*, const float *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_get_xsd__float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_xsd__float(struct soap*, const char*, float *, const char*);

#ifndef SOAP_TYPE_float
#define SOAP_TYPE_float (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_float(struct soap*, float *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_float(struct soap*, float const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_float(struct soap*, const float *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_get_float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_float(struct soap*, const char*, float *, const char*);

#ifndef SOAP_TYPE_xsd__double
#define SOAP_TYPE_xsd__double (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__double(struct soap*, double *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__double(struct soap*, double const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__double(struct soap*, const double *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_get_xsd__double(struct soap*, double *, const char*, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_xsd__double(struct soap*, const char*, double *, const char*);

#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap*, double *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_double(struct soap*, double const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap*, const double *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap*, double *, const char*, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap*, const char*, double *, const char*);

#ifndef SOAP_TYPE_xsd__unsignedByte
#define SOAP_TYPE_xsd__unsignedByte (84)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__unsignedByte(struct soap*, unsigned char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__unsignedByte(struct soap*, const unsigned char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_xsd__unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_xsd__unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (83)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_unsignedByte(struct soap*, unsigned char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#ifndef SOAP_TYPE_xsd__unsignedShort
#define SOAP_TYPE_xsd__unsignedShort (80)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__unsignedShort(struct soap*, unsigned short *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__unsignedShort(struct soap*, unsigned short const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__unsignedShort(struct soap*, const unsigned short *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__unsignedShort(struct soap*, const char*, int, const unsigned short *, const char*);
SOAP_FMAC3 unsigned short * SOAP_FMAC4 soap_get_xsd__unsignedShort(struct soap*, unsigned short *, const char*, const char*);
SOAP_FMAC3 unsigned short * SOAP_FMAC4 soap_in_xsd__unsignedShort(struct soap*, const char*, unsigned short *, const char*);

#ifndef SOAP_TYPE_unsignedShort
#define SOAP_TYPE_unsignedShort (79)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedShort(struct soap*, unsigned short *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_unsignedShort(struct soap*, unsigned short const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedShort(struct soap*, const unsigned short *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedShort(struct soap*, const char*, int, const unsigned short *, const char*);
SOAP_FMAC3 unsigned short * SOAP_FMAC4 soap_get_unsignedShort(struct soap*, unsigned short *, const char*, const char*);
SOAP_FMAC3 unsigned short * SOAP_FMAC4 soap_in_unsignedShort(struct soap*, const char*, unsigned short *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_unsignedInt(struct soap*, unsigned int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE_xsd__unsignedInt
#define SOAP_TYPE_xsd__unsignedInt (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__unsignedInt(struct soap*, unsigned long *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__unsignedInt(struct soap*, unsigned long const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__unsignedInt(struct soap*, const unsigned long *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__unsignedInt(struct soap*, const char*, int, const unsigned long *, const char*);
SOAP_FMAC3 unsigned long * SOAP_FMAC4 soap_get_xsd__unsignedInt(struct soap*, unsigned long *, const char*, const char*);
SOAP_FMAC3 unsigned long * SOAP_FMAC4 soap_in_xsd__unsignedInt(struct soap*, const char*, unsigned long *, const char*);

#ifndef SOAP_TYPE_unsignedLong
#define SOAP_TYPE_unsignedLong (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedLong(struct soap*, unsigned long *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_unsignedLong(struct soap*, unsigned long const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedLong(struct soap*, const unsigned long *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedLong(struct soap*, const char*, int, const unsigned long *, const char*);
SOAP_FMAC3 unsigned long * SOAP_FMAC4 soap_get_unsignedLong(struct soap*, unsigned long *, const char*, const char*);
SOAP_FMAC3 unsigned long * SOAP_FMAC4 soap_in_unsignedLong(struct soap*, const char*, unsigned long *, const char*);

#ifndef SOAP_TYPE_xsd__unsignedLong
#define SOAP_TYPE_xsd__unsignedLong (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__unsignedLong(struct soap*, ULONG64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__unsignedLong(struct soap*, ULONG64 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__unsignedLong(struct soap*, const ULONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__unsignedLong(struct soap*, const char*, int, const ULONG64 *, const char*);
SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_get_xsd__unsignedLong(struct soap*, ULONG64 *, const char*, const char*);
SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_in_xsd__unsignedLong(struct soap*, const char*, ULONG64 *, const char*);

#ifndef SOAP_TYPE_unsignedLONG64
#define SOAP_TYPE_unsignedLONG64 (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedLONG64(struct soap*, ULONG64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_unsignedLONG64(struct soap*, ULONG64 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedLONG64(struct soap*, const ULONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedLONG64(struct soap*, const char*, int, const ULONG64 *, const char*);
SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_get_unsignedLONG64(struct soap*, ULONG64 *, const char*, const char*);
SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_in_unsignedLONG64(struct soap*, const char*, ULONG64 *, const char*);

#ifndef SOAP_TYPE_param__null
#define SOAP_TYPE_param__null (117)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_param__null(struct soap*, bool *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_param__null(struct soap*, bool const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_param__null(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_param__null(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap_param__null2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_param__null(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_param__null(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2param__null(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__boolean(struct soap*, bool *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__boolean(struct soap*, bool const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap_xsd__boolean2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2xsd__boolean(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_bool(struct soap*, bool const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2bool(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_SOAPPermissions
#define SOAP_TYPE_SOAPPermissions (134)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAPPermissions(struct soap*, const char*, int, const SOAPPermissions *, const char*);
SOAP_FMAC3 SOAPPermissions * SOAP_FMAC4 soap_get_SOAPPermissions(struct soap*, SOAPPermissions *, const char*, const char*);
SOAP_FMAC3 SOAPPermissions * SOAP_FMAC4 soap_in_SOAPPermissions(struct soap*, const char*, SOAPPermissions *, const char*);

SOAP_FMAC5 SOAPPermissions * SOAP_FMAC6 soap_new_SOAPPermissions(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAPPermissions(struct soap*, SOAPPermissions*);
SOAP_FMAC5 SOAPPermissions * SOAP_FMAC6 soap_instantiate_SOAPPermissions(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_SOAPPermissions(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_param__arrayvalue
#define SOAP_TYPE_param__arrayvalue (126)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_param__arrayvalue(struct soap*, const char*, int, const param__arrayvalue *, const char*);
SOAP_FMAC3 param__arrayvalue * SOAP_FMAC4 soap_get_param__arrayvalue(struct soap*, param__arrayvalue *, const char*, const char*);
SOAP_FMAC3 param__arrayvalue * SOAP_FMAC4 soap_in_param__arrayvalue(struct soap*, const char*, param__arrayvalue *, const char*);

SOAP_FMAC5 param__arrayvalue * SOAP_FMAC6 soap_new_param__arrayvalue(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_param__arrayvalue(struct soap*, param__arrayvalue*);
SOAP_FMAC5 param__arrayvalue * SOAP_FMAC6 soap_instantiate_param__arrayvalue(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_param__arrayvalue(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_param__params
#define SOAP_TYPE_param__params (123)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_param__params(struct soap*, const char*, int, const param__params *, const char*);
SOAP_FMAC3 param__params * SOAP_FMAC4 soap_get_param__params(struct soap*, param__params *, const char*, const char*);
SOAP_FMAC3 param__params * SOAP_FMAC4 soap_in_param__params(struct soap*, const char*, param__params *, const char*);

SOAP_FMAC5 param__params * SOAP_FMAC6 soap_new_param__params(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_param__params(struct soap*, param__params*);
SOAP_FMAC5 param__params * SOAP_FMAC6 soap_instantiate_param__params(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_param__params(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_param__node
#define SOAP_TYPE_param__node (121)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_param__node(struct soap*, const char*, int, const param__node *, const char*);
SOAP_FMAC3 param__node * SOAP_FMAC4 soap_get_param__node(struct soap*, param__node *, const char*, const char*);
SOAP_FMAC3 param__node * SOAP_FMAC4 soap_in_param__node(struct soap*, const char*, param__node *, const char*);

SOAP_FMAC5 param__node * SOAP_FMAC6 soap_new_param__node(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_param__node(struct soap*, param__node*);
SOAP_FMAC5 param__node * SOAP_FMAC6 soap_instantiate_param__node(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_param__node(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_param__entry
#define SOAP_TYPE_param__entry (120)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_param__entry(struct soap*, const char*, int, const param__entry *, const char*);
SOAP_FMAC3 param__entry * SOAP_FMAC4 soap_get_param__entry(struct soap*, param__entry *, const char*, const char*);
SOAP_FMAC3 param__entry * SOAP_FMAC4 soap_in_param__entry(struct soap*, const char*, param__entry *, const char*);

SOAP_FMAC5 param__entry * SOAP_FMAC6 soap_new_param__entry(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_param__entry(struct soap*, param__entry*);
SOAP_FMAC5 param__entry * SOAP_FMAC6 soap_instantiate_param__entry(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_param__entry(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_param__value
#define SOAP_TYPE_param__value (118)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_param__value(struct soap*, const char*, int, const param__value *, const char*);
SOAP_FMAC3 param__value * SOAP_FMAC4 soap_get_param__value(struct soap*, param__value *, const char*, const char*);
SOAP_FMAC3 param__value * SOAP_FMAC4 soap_in_param__value(struct soap*, const char*, param__value *, const char*);

SOAP_FMAC5 param__value * SOAP_FMAC6 soap_new_param__value(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_param__value(struct soap*, param__value*);
SOAP_FMAC5 param__value * SOAP_FMAC6 soap_instantiate_param__value(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_param__value(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_param_error_loc
#define SOAP_TYPE_param_error_loc (114)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_param_error_loc(struct soap*, const char*, int, const param_error_loc *, const char*);
SOAP_FMAC3 param_error_loc * SOAP_FMAC4 soap_get_param_error_loc(struct soap*, param_error_loc *, const char*, const char*);
SOAP_FMAC3 param_error_loc * SOAP_FMAC4 soap_in_param_error_loc(struct soap*, const char*, param_error_loc *, const char*);

SOAP_FMAC5 param_error_loc * SOAP_FMAC6 soap_new_param_error_loc(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_param_error_loc(struct soap*, param_error_loc*);
SOAP_FMAC5 param_error_loc * SOAP_FMAC6 soap_instantiate_param_error_loc(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_param_error_loc(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_param_error_loc_args
#define SOAP_TYPE_param_error_loc_args (112)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_param_error_loc_args(struct soap*, const char*, int, const param_error_loc_args *, const char*);
SOAP_FMAC3 param_error_loc_args * SOAP_FMAC4 soap_get_param_error_loc_args(struct soap*, param_error_loc_args *, const char*, const char*);
SOAP_FMAC3 param_error_loc_args * SOAP_FMAC4 soap_in_param_error_loc_args(struct soap*, const char*, param_error_loc_args *, const char*);

SOAP_FMAC5 param_error_loc_args * SOAP_FMAC6 soap_new_param_error_loc_args(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_param_error_loc_args(struct soap*, param_error_loc_args*);
SOAP_FMAC5 param_error_loc_args * SOAP_FMAC6 soap_instantiate_param_error_loc_args(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_param_error_loc_args(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_SOAPComponentId
#define SOAP_TYPE_SOAPComponentId (106)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAPComponentId(struct soap*, const char*, int, const SOAPComponentId *, const char*);
SOAP_FMAC3 SOAPComponentId * SOAP_FMAC4 soap_get_SOAPComponentId(struct soap*, SOAPComponentId *, const char*, const char*);
SOAP_FMAC3 SOAPComponentId * SOAP_FMAC4 soap_in_SOAPComponentId(struct soap*, const char*, SOAPComponentId *, const char*);

SOAP_FMAC5 SOAPComponentId * SOAP_FMAC6 soap_new_SOAPComponentId(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAPComponentId(struct soap*, SOAPComponentId*);
SOAP_FMAC5 SOAPComponentId * SOAP_FMAC6 soap_instantiate_SOAPComponentId(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_SOAPComponentId(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__hexBinary
#define SOAP_TYPE_xsd__hexBinary (104)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__hexBinary(struct soap*, const char*, int, const xsd__hexBinary *, const char*);
SOAP_FMAC3 xsd__hexBinary * SOAP_FMAC4 soap_get_xsd__hexBinary(struct soap*, xsd__hexBinary *, const char*, const char*);
SOAP_FMAC3 xsd__hexBinary * SOAP_FMAC4 soap_in_xsd__hexBinary(struct soap*, const char*, xsd__hexBinary *, const char*);

SOAP_FMAC5 xsd__hexBinary * SOAP_FMAC6 soap_new_xsd__hexBinary(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__hexBinary(struct soap*, xsd__hexBinary*);
SOAP_FMAC5 xsd__hexBinary * SOAP_FMAC6 soap_instantiate_xsd__hexBinary(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__hexBinary(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (101)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__base64Binary(struct soap*, const char*, int, const xsd__base64Binary *, const char*);
SOAP_FMAC3 xsd__base64Binary * SOAP_FMAC4 soap_get_xsd__base64Binary(struct soap*, xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 xsd__base64Binary * SOAP_FMAC4 soap_in_xsd__base64Binary(struct soap*, const char*, xsd__base64Binary *, const char*);

SOAP_FMAC5 xsd__base64Binary * SOAP_FMAC6 soap_new_xsd__base64Binary(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__base64Binary(struct soap*, xsd__base64Binary*);
SOAP_FMAC5 xsd__base64Binary * SOAP_FMAC6 soap_instantiate_xsd__base64Binary(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__base64Binary(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__token_
#define SOAP_TYPE_xsd__token_ (99)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__token_(struct soap*, const char*, int, const xsd__token_ *, const char*);
SOAP_FMAC3 xsd__token_ * SOAP_FMAC4 soap_get_xsd__token_(struct soap*, xsd__token_ *, const char*, const char*);
SOAP_FMAC3 xsd__token_ * SOAP_FMAC4 soap_in_xsd__token_(struct soap*, const char*, xsd__token_ *, const char*);

SOAP_FMAC5 xsd__token_ * SOAP_FMAC6 soap_new_xsd__token_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__token_(struct soap*, xsd__token_*);
SOAP_FMAC5 xsd__token_ * SOAP_FMAC6 soap_instantiate_xsd__token_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__token_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__normalizedString_
#define SOAP_TYPE_xsd__normalizedString_ (96)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__normalizedString_(struct soap*, const char*, int, const xsd__normalizedString_ *, const char*);
SOAP_FMAC3 xsd__normalizedString_ * SOAP_FMAC4 soap_get_xsd__normalizedString_(struct soap*, xsd__normalizedString_ *, const char*, const char*);
SOAP_FMAC3 xsd__normalizedString_ * SOAP_FMAC4 soap_in_xsd__normalizedString_(struct soap*, const char*, xsd__normalizedString_ *, const char*);

SOAP_FMAC5 xsd__normalizedString_ * SOAP_FMAC6 soap_new_xsd__normalizedString_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__normalizedString_(struct soap*, xsd__normalizedString_*);
SOAP_FMAC5 xsd__normalizedString_ * SOAP_FMAC6 soap_instantiate_xsd__normalizedString_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__normalizedString_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__string_
#define SOAP_TYPE_xsd__string_ (93)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string_(struct soap*, const char*, int, const xsd__string_ *, const char*);
SOAP_FMAC3 xsd__string_ * SOAP_FMAC4 soap_get_xsd__string_(struct soap*, xsd__string_ *, const char*, const char*);
SOAP_FMAC3 xsd__string_ * SOAP_FMAC4 soap_in_xsd__string_(struct soap*, const char*, xsd__string_ *, const char*);

SOAP_FMAC5 xsd__string_ * SOAP_FMAC6 soap_new_xsd__string_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__string_(struct soap*, xsd__string_*);
SOAP_FMAC5 xsd__string_ * SOAP_FMAC6 soap_instantiate_xsd__string_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__string_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__wstring_
#define SOAP_TYPE_xsd__wstring_ (90)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__wstring_(struct soap*, const char*, int, const xsd__wstring_ *, const char*);
SOAP_FMAC3 xsd__wstring_ * SOAP_FMAC4 soap_get_xsd__wstring_(struct soap*, xsd__wstring_ *, const char*, const char*);
SOAP_FMAC3 xsd__wstring_ * SOAP_FMAC4 soap_in_xsd__wstring_(struct soap*, const char*, xsd__wstring_ *, const char*);

SOAP_FMAC5 xsd__wstring_ * SOAP_FMAC6 soap_new_xsd__wstring_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__wstring_(struct soap*, xsd__wstring_*);
SOAP_FMAC5 xsd__wstring_ * SOAP_FMAC6 soap_instantiate_xsd__wstring_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__wstring_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__unsignedByte_
#define SOAP_TYPE_xsd__unsignedByte_ (85)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__unsignedByte_(struct soap*, const char*, int, const xsd__unsignedByte_ *, const char*);
SOAP_FMAC3 xsd__unsignedByte_ * SOAP_FMAC4 soap_get_xsd__unsignedByte_(struct soap*, xsd__unsignedByte_ *, const char*, const char*);
SOAP_FMAC3 xsd__unsignedByte_ * SOAP_FMAC4 soap_in_xsd__unsignedByte_(struct soap*, const char*, xsd__unsignedByte_ *, const char*);

SOAP_FMAC5 xsd__unsignedByte_ * SOAP_FMAC6 soap_new_xsd__unsignedByte_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__unsignedByte_(struct soap*, xsd__unsignedByte_*);
SOAP_FMAC5 xsd__unsignedByte_ * SOAP_FMAC6 soap_instantiate_xsd__unsignedByte_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__unsignedByte_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__unsignedShort_
#define SOAP_TYPE_xsd__unsignedShort_ (81)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__unsignedShort_(struct soap*, const char*, int, const xsd__unsignedShort_ *, const char*);
SOAP_FMAC3 xsd__unsignedShort_ * SOAP_FMAC4 soap_get_xsd__unsignedShort_(struct soap*, xsd__unsignedShort_ *, const char*, const char*);
SOAP_FMAC3 xsd__unsignedShort_ * SOAP_FMAC4 soap_in_xsd__unsignedShort_(struct soap*, const char*, xsd__unsignedShort_ *, const char*);

SOAP_FMAC5 xsd__unsignedShort_ * SOAP_FMAC6 soap_new_xsd__unsignedShort_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__unsignedShort_(struct soap*, xsd__unsignedShort_*);
SOAP_FMAC5 xsd__unsignedShort_ * SOAP_FMAC6 soap_instantiate_xsd__unsignedShort_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__unsignedShort_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__unsignedInt_
#define SOAP_TYPE_xsd__unsignedInt_ (77)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__unsignedInt_(struct soap*, const char*, int, const xsd__unsignedInt_ *, const char*);
SOAP_FMAC3 xsd__unsignedInt_ * SOAP_FMAC4 soap_get_xsd__unsignedInt_(struct soap*, xsd__unsignedInt_ *, const char*, const char*);
SOAP_FMAC3 xsd__unsignedInt_ * SOAP_FMAC4 soap_in_xsd__unsignedInt_(struct soap*, const char*, xsd__unsignedInt_ *, const char*);

SOAP_FMAC5 xsd__unsignedInt_ * SOAP_FMAC6 soap_new_xsd__unsignedInt_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__unsignedInt_(struct soap*, xsd__unsignedInt_*);
SOAP_FMAC5 xsd__unsignedInt_ * SOAP_FMAC6 soap_instantiate_xsd__unsignedInt_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__unsignedInt_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__unsignedLong_
#define SOAP_TYPE_xsd__unsignedLong_ (72)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__unsignedLong_(struct soap*, const char*, int, const xsd__unsignedLong_ *, const char*);
SOAP_FMAC3 xsd__unsignedLong_ * SOAP_FMAC4 soap_get_xsd__unsignedLong_(struct soap*, xsd__unsignedLong_ *, const char*, const char*);
SOAP_FMAC3 xsd__unsignedLong_ * SOAP_FMAC4 soap_in_xsd__unsignedLong_(struct soap*, const char*, xsd__unsignedLong_ *, const char*);

SOAP_FMAC5 xsd__unsignedLong_ * SOAP_FMAC6 soap_new_xsd__unsignedLong_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__unsignedLong_(struct soap*, xsd__unsignedLong_*);
SOAP_FMAC5 xsd__unsignedLong_ * SOAP_FMAC6 soap_instantiate_xsd__unsignedLong_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__unsignedLong_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__positiveInteger_
#define SOAP_TYPE_xsd__positiveInteger_ (68)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__positiveInteger_(struct soap*, const char*, int, const xsd__positiveInteger_ *, const char*);
SOAP_FMAC3 xsd__positiveInteger_ * SOAP_FMAC4 soap_get_xsd__positiveInteger_(struct soap*, xsd__positiveInteger_ *, const char*, const char*);
SOAP_FMAC3 xsd__positiveInteger_ * SOAP_FMAC4 soap_in_xsd__positiveInteger_(struct soap*, const char*, xsd__positiveInteger_ *, const char*);

SOAP_FMAC5 xsd__positiveInteger_ * SOAP_FMAC6 soap_new_xsd__positiveInteger_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__positiveInteger_(struct soap*, xsd__positiveInteger_*);
SOAP_FMAC5 xsd__positiveInteger_ * SOAP_FMAC6 soap_instantiate_xsd__positiveInteger_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__positiveInteger_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__nonNegativeInteger_
#define SOAP_TYPE_xsd__nonNegativeInteger_ (65)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__nonNegativeInteger_(struct soap*, const char*, int, const xsd__nonNegativeInteger_ *, const char*);
SOAP_FMAC3 xsd__nonNegativeInteger_ * SOAP_FMAC4 soap_get_xsd__nonNegativeInteger_(struct soap*, xsd__nonNegativeInteger_ *, const char*, const char*);
SOAP_FMAC3 xsd__nonNegativeInteger_ * SOAP_FMAC4 soap_in_xsd__nonNegativeInteger_(struct soap*, const char*, xsd__nonNegativeInteger_ *, const char*);

SOAP_FMAC5 xsd__nonNegativeInteger_ * SOAP_FMAC6 soap_new_xsd__nonNegativeInteger_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__nonNegativeInteger_(struct soap*, xsd__nonNegativeInteger_*);
SOAP_FMAC5 xsd__nonNegativeInteger_ * SOAP_FMAC6 soap_instantiate_xsd__nonNegativeInteger_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__nonNegativeInteger_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__negativeInteger_
#define SOAP_TYPE_xsd__negativeInteger_ (62)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__negativeInteger_(struct soap*, const char*, int, const xsd__negativeInteger_ *, const char*);
SOAP_FMAC3 xsd__negativeInteger_ * SOAP_FMAC4 soap_get_xsd__negativeInteger_(struct soap*, xsd__negativeInteger_ *, const char*, const char*);
SOAP_FMAC3 xsd__negativeInteger_ * SOAP_FMAC4 soap_in_xsd__negativeInteger_(struct soap*, const char*, xsd__negativeInteger_ *, const char*);

SOAP_FMAC5 xsd__negativeInteger_ * SOAP_FMAC6 soap_new_xsd__negativeInteger_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__negativeInteger_(struct soap*, xsd__negativeInteger_*);
SOAP_FMAC5 xsd__negativeInteger_ * SOAP_FMAC6 soap_instantiate_xsd__negativeInteger_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__negativeInteger_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__nonPositiveInteger_
#define SOAP_TYPE_xsd__nonPositiveInteger_ (59)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__nonPositiveInteger_(struct soap*, const char*, int, const xsd__nonPositiveInteger_ *, const char*);
SOAP_FMAC3 xsd__nonPositiveInteger_ * SOAP_FMAC4 soap_get_xsd__nonPositiveInteger_(struct soap*, xsd__nonPositiveInteger_ *, const char*, const char*);
SOAP_FMAC3 xsd__nonPositiveInteger_ * SOAP_FMAC4 soap_in_xsd__nonPositiveInteger_(struct soap*, const char*, xsd__nonPositiveInteger_ *, const char*);

SOAP_FMAC5 xsd__nonPositiveInteger_ * SOAP_FMAC6 soap_new_xsd__nonPositiveInteger_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__nonPositiveInteger_(struct soap*, xsd__nonPositiveInteger_*);
SOAP_FMAC5 xsd__nonPositiveInteger_ * SOAP_FMAC6 soap_instantiate_xsd__nonPositiveInteger_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__nonPositiveInteger_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__byte_
#define SOAP_TYPE_xsd__byte_ (56)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__byte_(struct soap*, const char*, int, const xsd__byte_ *, const char*);
SOAP_FMAC3 xsd__byte_ * SOAP_FMAC4 soap_get_xsd__byte_(struct soap*, xsd__byte_ *, const char*, const char*);
SOAP_FMAC3 xsd__byte_ * SOAP_FMAC4 soap_in_xsd__byte_(struct soap*, const char*, xsd__byte_ *, const char*);

SOAP_FMAC5 xsd__byte_ * SOAP_FMAC6 soap_new_xsd__byte_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__byte_(struct soap*, xsd__byte_*);
SOAP_FMAC5 xsd__byte_ * SOAP_FMAC6 soap_instantiate_xsd__byte_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__byte_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__short_
#define SOAP_TYPE_xsd__short_ (53)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__short_(struct soap*, const char*, int, const xsd__short_ *, const char*);
SOAP_FMAC3 xsd__short_ * SOAP_FMAC4 soap_get_xsd__short_(struct soap*, xsd__short_ *, const char*, const char*);
SOAP_FMAC3 xsd__short_ * SOAP_FMAC4 soap_in_xsd__short_(struct soap*, const char*, xsd__short_ *, const char*);

SOAP_FMAC5 xsd__short_ * SOAP_FMAC6 soap_new_xsd__short_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__short_(struct soap*, xsd__short_*);
SOAP_FMAC5 xsd__short_ * SOAP_FMAC6 soap_instantiate_xsd__short_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__short_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__int_
#define SOAP_TYPE_xsd__int_ (49)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__int_(struct soap*, const char*, int, const xsd__int_ *, const char*);
SOAP_FMAC3 xsd__int_ * SOAP_FMAC4 soap_get_xsd__int_(struct soap*, xsd__int_ *, const char*, const char*);
SOAP_FMAC3 xsd__int_ * SOAP_FMAC4 soap_in_xsd__int_(struct soap*, const char*, xsd__int_ *, const char*);

SOAP_FMAC5 xsd__int_ * SOAP_FMAC6 soap_new_xsd__int_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__int_(struct soap*, xsd__int_*);
SOAP_FMAC5 xsd__int_ * SOAP_FMAC6 soap_instantiate_xsd__int_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__int_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__long_
#define SOAP_TYPE_xsd__long_ (45)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__long_(struct soap*, const char*, int, const xsd__long_ *, const char*);
SOAP_FMAC3 xsd__long_ * SOAP_FMAC4 soap_get_xsd__long_(struct soap*, xsd__long_ *, const char*, const char*);
SOAP_FMAC3 xsd__long_ * SOAP_FMAC4 soap_in_xsd__long_(struct soap*, const char*, xsd__long_ *, const char*);

SOAP_FMAC5 xsd__long_ * SOAP_FMAC6 soap_new_xsd__long_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__long_(struct soap*, xsd__long_*);
SOAP_FMAC5 xsd__long_ * SOAP_FMAC6 soap_instantiate_xsd__long_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__long_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__integer_
#define SOAP_TYPE_xsd__integer_ (41)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__integer_(struct soap*, const char*, int, const xsd__integer_ *, const char*);
SOAP_FMAC3 xsd__integer_ * SOAP_FMAC4 soap_get_xsd__integer_(struct soap*, xsd__integer_ *, const char*, const char*);
SOAP_FMAC3 xsd__integer_ * SOAP_FMAC4 soap_in_xsd__integer_(struct soap*, const char*, xsd__integer_ *, const char*);

SOAP_FMAC5 xsd__integer_ * SOAP_FMAC6 soap_new_xsd__integer_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__integer_(struct soap*, xsd__integer_*);
SOAP_FMAC5 xsd__integer_ * SOAP_FMAC6 soap_instantiate_xsd__integer_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__integer_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__decimal_
#define SOAP_TYPE_xsd__decimal_ (38)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__decimal_(struct soap*, const char*, int, const xsd__decimal_ *, const char*);
SOAP_FMAC3 xsd__decimal_ * SOAP_FMAC4 soap_get_xsd__decimal_(struct soap*, xsd__decimal_ *, const char*, const char*);
SOAP_FMAC3 xsd__decimal_ * SOAP_FMAC4 soap_in_xsd__decimal_(struct soap*, const char*, xsd__decimal_ *, const char*);

SOAP_FMAC5 xsd__decimal_ * SOAP_FMAC6 soap_new_xsd__decimal_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__decimal_(struct soap*, xsd__decimal_*);
SOAP_FMAC5 xsd__decimal_ * SOAP_FMAC6 soap_instantiate_xsd__decimal_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__decimal_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__time_
#define SOAP_TYPE_xsd__time_ (35)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__time_(struct soap*, const char*, int, const xsd__time_ *, const char*);
SOAP_FMAC3 xsd__time_ * SOAP_FMAC4 soap_get_xsd__time_(struct soap*, xsd__time_ *, const char*, const char*);
SOAP_FMAC3 xsd__time_ * SOAP_FMAC4 soap_in_xsd__time_(struct soap*, const char*, xsd__time_ *, const char*);

SOAP_FMAC5 xsd__time_ * SOAP_FMAC6 soap_new_xsd__time_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__time_(struct soap*, xsd__time_*);
SOAP_FMAC5 xsd__time_ * SOAP_FMAC6 soap_instantiate_xsd__time_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__time_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__float_
#define SOAP_TYPE_xsd__float_ (32)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__float_(struct soap*, const char*, int, const xsd__float_ *, const char*);
SOAP_FMAC3 xsd__float_ * SOAP_FMAC4 soap_get_xsd__float_(struct soap*, xsd__float_ *, const char*, const char*);
SOAP_FMAC3 xsd__float_ * SOAP_FMAC4 soap_in_xsd__float_(struct soap*, const char*, xsd__float_ *, const char*);

SOAP_FMAC5 xsd__float_ * SOAP_FMAC6 soap_new_xsd__float_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__float_(struct soap*, xsd__float_*);
SOAP_FMAC5 xsd__float_ * SOAP_FMAC6 soap_instantiate_xsd__float_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__float_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__duration_
#define SOAP_TYPE_xsd__duration_ (28)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__duration_(struct soap*, const char*, int, const xsd__duration_ *, const char*);
SOAP_FMAC3 xsd__duration_ * SOAP_FMAC4 soap_get_xsd__duration_(struct soap*, xsd__duration_ *, const char*, const char*);
SOAP_FMAC3 xsd__duration_ * SOAP_FMAC4 soap_in_xsd__duration_(struct soap*, const char*, xsd__duration_ *, const char*);

SOAP_FMAC5 xsd__duration_ * SOAP_FMAC6 soap_new_xsd__duration_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__duration_(struct soap*, xsd__duration_*);
SOAP_FMAC5 xsd__duration_ * SOAP_FMAC6 soap_instantiate_xsd__duration_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__duration_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__double_
#define SOAP_TYPE_xsd__double_ (25)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__double_(struct soap*, const char*, int, const xsd__double_ *, const char*);
SOAP_FMAC3 xsd__double_ * SOAP_FMAC4 soap_get_xsd__double_(struct soap*, xsd__double_ *, const char*, const char*);
SOAP_FMAC3 xsd__double_ * SOAP_FMAC4 soap_in_xsd__double_(struct soap*, const char*, xsd__double_ *, const char*);

SOAP_FMAC5 xsd__double_ * SOAP_FMAC6 soap_new_xsd__double_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__double_(struct soap*, xsd__double_*);
SOAP_FMAC5 xsd__double_ * SOAP_FMAC6 soap_instantiate_xsd__double_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__double_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__dateTime_
#define SOAP_TYPE_xsd__dateTime_ (21)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__dateTime_(struct soap*, const char*, int, const xsd__dateTime_ *, const char*);
SOAP_FMAC3 xsd__dateTime_ * SOAP_FMAC4 soap_get_xsd__dateTime_(struct soap*, xsd__dateTime_ *, const char*, const char*);
SOAP_FMAC3 xsd__dateTime_ * SOAP_FMAC4 soap_in_xsd__dateTime_(struct soap*, const char*, xsd__dateTime_ *, const char*);

SOAP_FMAC5 xsd__dateTime_ * SOAP_FMAC6 soap_new_xsd__dateTime_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__dateTime_(struct soap*, xsd__dateTime_*);
SOAP_FMAC5 xsd__dateTime_ * SOAP_FMAC6 soap_instantiate_xsd__dateTime_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__dateTime_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__date_
#define SOAP_TYPE_xsd__date_ (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__date_(struct soap*, const char*, int, const xsd__date_ *, const char*);
SOAP_FMAC3 xsd__date_ * SOAP_FMAC4 soap_get_xsd__date_(struct soap*, xsd__date_ *, const char*, const char*);
SOAP_FMAC3 xsd__date_ * SOAP_FMAC4 soap_in_xsd__date_(struct soap*, const char*, xsd__date_ *, const char*);

SOAP_FMAC5 xsd__date_ * SOAP_FMAC6 soap_new_xsd__date_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__date_(struct soap*, xsd__date_*);
SOAP_FMAC5 xsd__date_ * SOAP_FMAC6 soap_instantiate_xsd__date_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__date_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__boolean_
#define SOAP_TYPE_xsd__boolean_ (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean_(struct soap*, const char*, int, const xsd__boolean_ *, const char*);
SOAP_FMAC3 xsd__boolean_ * SOAP_FMAC4 soap_get_xsd__boolean_(struct soap*, xsd__boolean_ *, const char*, const char*);
SOAP_FMAC3 xsd__boolean_ * SOAP_FMAC4 soap_in_xsd__boolean_(struct soap*, const char*, xsd__boolean_ *, const char*);

SOAP_FMAC5 xsd__boolean_ * SOAP_FMAC6 soap_new_xsd__boolean_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__boolean_(struct soap*, xsd__boolean_*);
SOAP_FMAC5 xsd__boolean_ * SOAP_FMAC6 soap_instantiate_xsd__boolean_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__boolean_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__anyURI_
#define SOAP_TYPE_xsd__anyURI_ (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyURI_(struct soap*, const char*, int, const xsd__anyURI_ *, const char*);
SOAP_FMAC3 xsd__anyURI_ * SOAP_FMAC4 soap_get_xsd__anyURI_(struct soap*, xsd__anyURI_ *, const char*, const char*);
SOAP_FMAC3 xsd__anyURI_ * SOAP_FMAC4 soap_in_xsd__anyURI_(struct soap*, const char*, xsd__anyURI_ *, const char*);

SOAP_FMAC5 xsd__anyURI_ * SOAP_FMAC6 soap_new_xsd__anyURI_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__anyURI_(struct soap*, xsd__anyURI_*);
SOAP_FMAC5 xsd__anyURI_ * SOAP_FMAC6 soap_instantiate_xsd__anyURI_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__anyURI_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__anySimpleType
#define SOAP_TYPE_xsd__anySimpleType (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anySimpleType(struct soap*, const char*, int, const xsd__anySimpleType *, const char*);
SOAP_FMAC3 xsd__anySimpleType * SOAP_FMAC4 soap_get_xsd__anySimpleType(struct soap*, xsd__anySimpleType *, const char*, const char*);
SOAP_FMAC3 xsd__anySimpleType * SOAP_FMAC4 soap_in_xsd__anySimpleType(struct soap*, const char*, xsd__anySimpleType *, const char*);

SOAP_FMAC5 xsd__anySimpleType * SOAP_FMAC6 soap_new_xsd__anySimpleType(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__anySimpleType(struct soap*, xsd__anySimpleType*);
SOAP_FMAC5 xsd__anySimpleType * SOAP_FMAC6 soap_instantiate_xsd__anySimpleType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__anySimpleType(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__anyType
#define SOAP_TYPE_xsd__anyType (6)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyType(struct soap*, const char*, int, const xsd__anyType *, const char*);
SOAP_FMAC3 xsd__anyType * SOAP_FMAC4 soap_get_xsd__anyType(struct soap*, xsd__anyType *, const char*, const char*);
SOAP_FMAC3 xsd__anyType * SOAP_FMAC4 soap_in_xsd__anyType(struct soap*, const char*, xsd__anyType *, const char*);

SOAP_FMAC5 xsd__anyType * SOAP_FMAC6 soap_new_xsd__anyType(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__anyType(struct soap*, xsd__anyType*);
SOAP_FMAC5 xsd__anyType * SOAP_FMAC6 soap_instantiate_xsd__anyType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__anyType(struct soap*, int, int, void*, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (138)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (136)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (135)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (133)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_message_desc
#define SOAP_TYPE_message_desc (132)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_message_desc(struct soap*, struct message_desc_t const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_message_desc(struct soap*, const struct message_desc_t *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_message_desc(struct soap*, struct message_desc_t *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_message_desc(struct soap*, const struct message_desc_t *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_message_desc(struct soap*, const char*, int, const struct message_desc_t *, const char*);
SOAP_FMAC3 struct message_desc_t * SOAP_FMAC4 soap_get_message_desc(struct soap*, struct message_desc_t *, const char*, const char*);
SOAP_FMAC1 struct message_desc_t * SOAP_FMAC2 soap_in_message_desc(struct soap*, const char*, struct message_desc_t *, const char*);

#ifndef SOAP_TYPE_param_error
#define SOAP_TYPE_param_error (115)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_param_error(struct soap*, struct param_error const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_param_error(struct soap*, const struct param_error *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_param_error(struct soap*, struct param_error *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_param_error(struct soap*, const struct param_error *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_param_error(struct soap*, const char*, int, const struct param_error *, const char*);
SOAP_FMAC3 struct param_error * SOAP_FMAC4 soap_get_param_error(struct soap*, struct param_error *, const char*, const char*);
SOAP_FMAC3 struct param_error * SOAP_FMAC4 soap_in_param_error(struct soap*, const char*, struct param_error *, const char*);

#ifndef SOAP_TYPE_SOAPComponentIdsList
#define SOAP_TYPE_SOAPComponentIdsList (110)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAPComponentIdsList(struct soap*, struct SOAPComponentIdsList const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAPComponentIdsList(struct soap*, struct SOAPComponentIdsList const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAPComponentIdsList(struct soap*, struct SOAPComponentIdsList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAPComponentIdsList(struct soap*, const struct SOAPComponentIdsList *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAPComponentIdsList(struct soap*, const char*, int, const struct SOAPComponentIdsList *, const char*);
SOAP_FMAC3 struct SOAPComponentIdsList * SOAP_FMAC4 soap_get_SOAPComponentIdsList(struct soap*, struct SOAPComponentIdsList *, const char*, const char*);
SOAP_FMAC3 struct SOAPComponentIdsList * SOAP_FMAC4 soap_in_SOAPComponentIdsList(struct soap*, const char*, struct SOAPComponentIdsList *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (140)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (139)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef SOAP_TYPE_PointerToparam__value
#define SOAP_TYPE_PointerToparam__value (127)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToparam__value(struct soap*, param__value *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToparam__value(struct soap*, param__value *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToparam__value(struct soap*, param__value *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToparam__value(struct soap*, const char *, int, param__value *const*, const char *);
SOAP_FMAC3 param__value ** SOAP_FMAC4 soap_get_PointerToparam__value(struct soap*, param__value **, const char*, const char*);
SOAP_FMAC3 param__value ** SOAP_FMAC4 soap_in_PointerToparam__value(struct soap*, const char*, param__value **, const char*);

#ifndef SOAP_TYPE_PointerToparam__node
#define SOAP_TYPE_PointerToparam__node (124)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToparam__node(struct soap*, param__node *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToparam__node(struct soap*, param__node *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToparam__node(struct soap*, param__node *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToparam__node(struct soap*, const char *, int, param__node *const*, const char *);
SOAP_FMAC3 param__node ** SOAP_FMAC4 soap_get_PointerToparam__node(struct soap*, param__node **, const char*, const char*);
SOAP_FMAC3 param__node ** SOAP_FMAC4 soap_in_PointerToparam__node(struct soap*, const char*, param__node **, const char*);

#ifndef SOAP_TYPE_PointerToparam__entry
#define SOAP_TYPE_PointerToparam__entry (122)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToparam__entry(struct soap*, param__entry *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToparam__entry(struct soap*, param__entry *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToparam__entry(struct soap*, param__entry *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToparam__entry(struct soap*, const char *, int, param__entry *const*, const char *);
SOAP_FMAC3 param__entry ** SOAP_FMAC4 soap_get_PointerToparam__entry(struct soap*, param__entry **, const char*, const char*);
SOAP_FMAC3 param__entry ** SOAP_FMAC4 soap_in_PointerToparam__entry(struct soap*, const char*, param__entry **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__anyType
#define SOAP_TYPE_PointerToxsd__anyType (119)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__anyType(struct soap*, xsd__anyType *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToxsd__anyType(struct soap*, xsd__anyType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__anyType(struct soap*, xsd__anyType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__anyType(struct soap*, const char *, int, xsd__anyType *const*, const char *);
SOAP_FMAC3 xsd__anyType ** SOAP_FMAC4 soap_get_PointerToxsd__anyType(struct soap*, xsd__anyType **, const char*, const char*);
SOAP_FMAC3 xsd__anyType ** SOAP_FMAC4 soap_in_PointerToxsd__anyType(struct soap*, const char*, xsd__anyType **, const char*);

#ifndef SOAP_TYPE_PointerToparam_error_loc
#define SOAP_TYPE_PointerToparam_error_loc (116)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToparam_error_loc(struct soap*, param_error_loc *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToparam_error_loc(struct soap*, param_error_loc *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToparam_error_loc(struct soap*, param_error_loc *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToparam_error_loc(struct soap*, const char *, int, param_error_loc *const*, const char *);
SOAP_FMAC3 param_error_loc ** SOAP_FMAC4 soap_get_PointerToparam_error_loc(struct soap*, param_error_loc **, const char*, const char*);
SOAP_FMAC3 param_error_loc ** SOAP_FMAC4 soap_in_PointerToparam_error_loc(struct soap*, const char*, param_error_loc **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__wstring
#define SOAP_TYPE_PointerToxsd__wstring (113)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__wstring(struct soap*, wchar_t **const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToxsd__wstring(struct soap*, wchar_t **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__wstring(struct soap*, wchar_t **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__wstring(struct soap*, const char *, int, wchar_t **const*, const char *);
SOAP_FMAC3 wchar_t *** SOAP_FMAC4 soap_get_PointerToxsd__wstring(struct soap*, wchar_t ***, const char*, const char*);
SOAP_FMAC3 wchar_t *** SOAP_FMAC4 soap_in_PointerToxsd__wstring(struct soap*, const char*, wchar_t ***, const char*);

#ifndef SOAP_TYPE_PointerToSOAPComponentId
#define SOAP_TYPE_PointerToSOAPComponentId (111)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAPComponentId(struct soap*, SOAPComponentId *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToSOAPComponentId(struct soap*, SOAPComponentId *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAPComponentId(struct soap*, SOAPComponentId *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAPComponentId(struct soap*, const char *, int, SOAPComponentId *const*, const char *);
SOAP_FMAC3 SOAPComponentId ** SOAP_FMAC4 soap_get_PointerToSOAPComponentId(struct soap*, SOAPComponentId **, const char*, const char*);
SOAP_FMAC3 SOAPComponentId ** SOAP_FMAC4 soap_in_PointerToSOAPComponentId(struct soap*, const char*, SOAPComponentId **, const char*);

#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (102)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);

#ifndef SOAP_TYPE_xsd__token
#define SOAP_TYPE_xsd__token (98)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__token(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__token(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__token(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__token(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__token(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__token(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__normalizedString
#define SOAP_TYPE_xsd__normalizedString (95)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__normalizedString(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__normalizedString(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__normalizedString(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__normalizedString(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__normalizedString(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__normalizedString(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (92)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__wstring
#define SOAP_TYPE_xsd__wstring (89)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__wstring(struct soap*, wchar_t *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__wstring(struct soap*, wchar_t *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__wstring(struct soap*, wchar_t *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__wstring(struct soap*, const char*, int, wchar_t*const*, const char*);
SOAP_FMAC3 wchar_t ** SOAP_FMAC4 soap_get_xsd__wstring(struct soap*, wchar_t **, const char*, const char*);
SOAP_FMAC3 wchar_t * * SOAP_FMAC4 soap_in_xsd__wstring(struct soap*, const char*, wchar_t **, const char*);

#ifndef SOAP_TYPE_wstring
#define SOAP_TYPE_wstring (88)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wstring(struct soap*, wchar_t *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_wstring(struct soap*, wchar_t *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_wstring(struct soap*, wchar_t *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wstring(struct soap*, const char*, int, wchar_t*const*, const char*);
SOAP_FMAC3 wchar_t ** SOAP_FMAC4 soap_get_wstring(struct soap*, wchar_t **, const char*, const char*);
SOAP_FMAC3 wchar_t * * SOAP_FMAC4 soap_in_wstring(struct soap*, const char*, wchar_t **, const char*);

#ifndef SOAP_TYPE_xsd__positiveInteger
#define SOAP_TYPE_xsd__positiveInteger (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__positiveInteger(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__positiveInteger(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__positiveInteger(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__positiveInteger(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__positiveInteger(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__positiveInteger(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__nonNegativeInteger
#define SOAP_TYPE_xsd__nonNegativeInteger (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__nonNegativeInteger(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__nonNegativeInteger(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__nonNegativeInteger(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__nonNegativeInteger(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__nonNegativeInteger(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__nonNegativeInteger(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__negativeInteger
#define SOAP_TYPE_xsd__negativeInteger (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__negativeInteger(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__negativeInteger(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__negativeInteger(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__negativeInteger(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__negativeInteger(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__negativeInteger(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__nonPositiveInteger
#define SOAP_TYPE_xsd__nonPositiveInteger (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__nonPositiveInteger(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__nonPositiveInteger(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__nonPositiveInteger(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__nonPositiveInteger(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__nonPositiveInteger(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__nonPositiveInteger(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__integer
#define SOAP_TYPE_xsd__integer (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__integer(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__integer(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__integer(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__integer(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__integer(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__integer(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__decimal
#define SOAP_TYPE_xsd__decimal (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__decimal(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__decimal(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__decimal(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__decimal(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__decimal(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__decimal(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__time
#define SOAP_TYPE_xsd__time (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__time(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__time(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__time(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__time(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__time(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__time(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__duration
#define SOAP_TYPE_xsd__duration (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__duration(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__duration(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__duration(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__duration(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__duration(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__duration(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__dateTime
#define SOAP_TYPE_xsd__dateTime (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__dateTime(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__dateTime(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__dateTime(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__dateTime(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__dateTime(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__dateTime(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__date
#define SOAP_TYPE_xsd__date (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__date(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__date(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__date(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__date(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__date(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__date(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__anyURI(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__anyURI(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__anyURI(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyURI(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__anyURI(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__anyURI(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

SOAP_END_NAMESPACE(soap)

#endif

/* end of soapH.h */
