// --------------------------------------------------------------------------------
// AVP Prague stamp begin( Interface header,  )
// -------- Wednesday,  15 October 2003,  19:27 --------
// File Name   -- rpc_gui.idl
// Copyright (c) Kaspersky Labs. 1996-2003.
// -------------------------------------------
// AVP Prague stamp end


#include "rpc_declare.h"
import "prague.h";
import "i_avs.h";

typedef rpcOBJECT	rpcAVS;
typedef rpcOBJECT	rpcAVSTREATS;

// --------------------------------------------------------------------------------
// AVP Prague stamp begin( Interface comment,  )
// GUI interface implementation
// Short comments -- 
// AVP Prague stamp end

// --------------------------------------------------------------------------------
// AVP Prague stamp begin( Interface function forward declarations,  )
[ uuid (EDC8CD42-CABF-4303-A0C6-73C2D7A736B9),
  version(1.0),
  pointer_default(unique)
]
interface rpc_avs {
	tERROR AVS_SetSettings		( rpcAVS _this, rpcSER(settings) );		// -- ;
	tERROR AVS_GetSettings		( rpcAVS _this, rpcSER(settings) );		// -- ;
	tERROR AVS_AskAction		( rpcAVS _this, tDWORD actionId, rpcSER(askinfo) );		// -- ;
	tERROR AVS_SetState			( rpcAVS _this, tDWORD state );		// -- ;
	tERROR AVS_GetStatistics	( rpcAVS _this, rpcSER(statistics) );		// -- ;
	tERROR AVS_GetTreats        ( rpcAVS _this, tDWORD taskid, [mout] rpcAVSTREATS* treats ) = 0;
	tERROR AVS_ReleaseTreats    ( rpcAVS _this, rpcAVSTREATS treats ) = 0;
	tERROR AVS_ProcessCancel    ( rpcAVS _this, tDWORD process_id ) = 0;
}
// AVP Prague stamp end

[ uuid (85D623B5-F2B7-4b6b-8A7B-3545E0561063),
  version(1.0),
  pointer_default(unique)
]
interface rpc_avstreats {
	tERROR AVSTreats_GetTreatInfo ( rpcAVSTREATS _this, tDWORD filter, tDWORD pos, rpcSER(info) ) = 0;
	tERROR AVSTreats_Process      ( rpcAVSTREATS _this, tDWORD filter, rpcSER(process_info) ) = 0;
	tERROR AVSTreats_GetInfo      ( rpcAVSTREATS _this, rpcSER(info) ) = 0;
	tERROR AVSTreats_ProcessCancel( rpcAVSTREATS _this ) = 0;
}
