ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=params

INCLUDES= \
	./rpc \
	../Include \
	../Include/iface \
	../../prague \
	../../prague/Include \
	./ \
	../../prague/Include/iface \
	../../Updater60/Include \
	../../CommonFiles

METAFILE=params.$(META)

VCPROJ=params.vcproj

SOURCESLIST=Sources.List

include $(ROOT)/Makefiles/Make.Plugin
