ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=klavcorelib

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/external/lzmalib

VCPROJ=klavcorelib.vcproj

SOURCESLIST=Sources.List

include $(ROOT)/Makefiles/Make.Archive

