ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=metadata

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/CommonFiles

SOURCESLIST=Sources.List

VCPROJ=metadata.vcproj

include $(ROOT)/Makefiles/Make.Archive
