#if !defined(__APPINFOID_H__)
#define __APPINFOID_H__

#include <property/property.h>


#define KL_PID_APPINFO_ROOT_ID		(1)
#define KL_PID_APPINFO_ROOT		MAKE_AVP_PID(KL_PID_APPINFO_ROOT_ID, 8, avpt_nothing, 0)
#define KL_PID_APPINFO_ROOT_UID2		(2)

 #define KL_PID_APPINFO_ID		(1)
 #define KL_PID_APPINFO		MAKE_AVP_PID(KL_PID_APPINFO_ID, 1, avpt_nothing, 0)
 #define KL_PID_APPINFO_UID3		(3)

  #define KL_PID_APPINFO_DESCRIPTION_ID		(1)
  #define KL_PID_APPINFO_DESCRIPTION		MAKE_AVP_PID(KL_PID_APPINFO_DESCRIPTION_ID, 1, avpt_str, 0)
  #define KL_PID_APPINFO_DESCRIPTION_UID7		(7)

  #define KL_PID_APPINFO_VERSION_ID		(2)
  #define KL_PID_APPINFO_VERSION		MAKE_AVP_PID(KL_PID_APPINFO_VERSION_ID, 1, avpt_dword, 0)
  #define KL_PID_APPINFO_VERSION_UID8		(8)

  #define KL_PID_APPINFO_DATECREATE_ID		(3)
  #define KL_PID_APPINFO_DATECREATE		MAKE_AVP_PID(KL_PID_APPINFO_DATECREATE_ID, 1, avpt_date, 0)
  #define KL_PID_APPINFO_DATECREATE_UID9		(9)

  #define KL_PID_APPINFO_APPID_ID		(4)
  #define KL_PID_APPINFO_APPID		MAKE_AVP_PID(KL_PID_APPINFO_APPID_ID, 1, avpt_dword, 0)
  #define KL_PID_APPINFO_APPID_UID10		(10)

  #define KL_PID_APPINFO_APPNAME_ID		(5)
  #define KL_PID_APPINFO_APPNAME		MAKE_AVP_PID(KL_PID_APPINFO_APPNAME_ID, 1, avpt_str, 0)
  #define KL_PID_APPINFO_APPNAME_UID11		(11)

  #define KL_PID_APPINFO_APPVERSION_ID		(6)
  #define KL_PID_APPINFO_APPVERSION		MAKE_AVP_PID(KL_PID_APPINFO_APPVERSION_ID, 1, avpt_str, 0)
  #define KL_PID_APPINFO_APPVERSION_UID12		(12)

  #define KL_PID_APPINFO_ISRELEASE_ID		(7)
  #define KL_PID_APPINFO_ISRELEASE		MAKE_AVP_PID(KL_PID_APPINFO_ISRELEASE_ID, 1, avpt_nothing, 0)
  #define KL_PID_APPINFO_ISRELEASE_UID13		(13)

 #define KL_PID_COMPONENTS_ID		(2)
 #define KL_PID_COMPONENTS		MAKE_AVP_PID(KL_PID_COMPONENTS_ID, 1, avpt_nothing, 0)
 #define KL_PID_COMPONENTS_UID4		(4)

  #define KL_PID_COMPONENTS_LEVEL_ID		(1)
  #define KL_PID_COMPONENTS_LEVEL		MAKE_AVP_PID(KL_PID_COMPONENTS_LEVEL_ID, 1, avpt_dword, 0)
  #define KL_PID_COMPONENTS_LEVEL_UID14		(14)

 #define KL_PID_PRODUCTS_ID		(3)
 #define KL_PID_PRODUCTS		MAKE_AVP_PID(KL_PID_PRODUCTS_ID, 1, avpt_nothing, 0)
 #define KL_PID_PRODUCTS_UID5		(5)

  #define KL_PID_PRODUCTS_NAME_ID		(1)
  #define KL_PID_PRODUCTS_NAME		MAKE_AVP_PID(KL_PID_PRODUCTS_NAME_ID, 1, avpt_str, 0)
  #define KL_PID_PRODUCTS_NAME_UID15		(15)

   #define KL_PID_PRODUCT_VERSION_ID		(1)
   #define KL_PID_PRODUCT_VERSION		MAKE_AVP_PID(KL_PID_PRODUCT_VERSION_ID, 1, avpt_str, 0)
   #define KL_PID_PRODUCT_VERSION_UID22		(22)

   #define KL_PID_PRODUCT_PUBLICKEY_ID		(2)
   #define KL_PID_PRODUCT_PUBLICKEY		MAKE_AVP_PID(KL_PID_PRODUCT_PUBLICKEY_ID, 1, avpt_dword, 0)
   #define KL_PID_PRODUCT_PUBLICKEY_UID23		(23)

 #define KL_PID_PUBLICKEYS_ID		(4)
 #define KL_PID_PUBLICKEYS		MAKE_AVP_PID(KL_PID_PUBLICKEYS_ID, 1, avpt_nothing, 0)
 #define KL_PID_PUBLICKEYS_UID6		(6)

  #define KL_PID_PUBLICKEYS_GUID_ID		(1)
  #define KL_PID_PUBLICKEYS_GUID		MAKE_AVP_PID(KL_PID_PUBLICKEYS_GUID_ID, 1, avpt_str, 0)
  #define KL_PID_PUBLICKEYS_GUID_UID16		(16)

   #define KL_PID_PUBLICKEY_ACCOUNT_ID		(1)
   #define KL_PID_PUBLICKEY_ACCOUNT		MAKE_AVP_PID(KL_PID_PUBLICKEY_ACCOUNT_ID, 1, avpt_str, 0)
   #define KL_PID_PUBLICKEY_ACCOUNT_UID17		(17)

   #define KL_PID_PUBLICKEY_B1_ID		(2)
   #define KL_PID_PUBLICKEY_B1		MAKE_AVP_PID(KL_PID_PUBLICKEY_B1_ID, 1, avpt_str, 0)
   #define KL_PID_PUBLICKEY_B1_UID18		(18)

   #define KL_PID_PUBLICKEY_B2_ID		(3)
   #define KL_PID_PUBLICKEY_B2		MAKE_AVP_PID(KL_PID_PUBLICKEY_B2_ID, 1, avpt_str, 0)
   #define KL_PID_PUBLICKEY_B2_UID19		(19)

   #define KL_PID_PUBLICKEY_B3_ID		(4)
   #define KL_PID_PUBLICKEY_B3		MAKE_AVP_PID(KL_PID_PUBLICKEY_B3_ID, 1, avpt_str, 0)
   #define KL_PID_PUBLICKEY_B3_UID20		(20)

   #define KL_PID_PUBLICKEY_B4_ID		(5)
   #define KL_PID_PUBLICKEY_B4		MAKE_AVP_PID(KL_PID_PUBLICKEY_B4_ID, 1, avpt_str, 0)
   #define KL_PID_PUBLICKEY_B4_UID21		(21)

 #define KL_PID_COMPATIBILITY_APPS_ID		(5)
 #define KL_PID_COMPATIBILITY_APPS	MAKE_AVP_PID(KL_PID_COMPATIBILITY_APPS_ID, 1, avpt_nothing, 0)
 #define KL_PID_COMPATIBILITY_APPS_UID22	(22)

  #define KL_PID_COMPATIBILITY_NAME_ID		(1)
  #define KL_PID_COMPATIBILITY_NAME		MAKE_AVP_PID(KL_PID_COMPATIBILITY_NAME_ID, 1, avpt_str, 0)
  #define KL_PID_COMPATIBILITY_NAME_UID23		(23)



#endif   // !defined(__APPINFO_H__)
