ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=qb

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/ProductCore \
	$(ROOT)/include/Extract \
	$(ROOT)/include/AV \
	$(ROOT)/CommonFiles

METAFILE=qb.$(META)

VCPROJ=qb.vcproj

SOURCESLIST=Sources.List

include $(ROOT)/Makefiles/Make.Plugin
