#ifndef __CONST_H
#define __CONST_H

#define GUID_SIZE		50
#define CTL_DEVICE_KLFLTDEV	0x00008300

#define NTDEVICE_NAME_STRING      L"\\Device\\KLFltDev"
#define SYMBOLIC_NAME_STRING      L"\\DosDevices\\KLFltDev"

#define DEV_TYPE_OTHER							L"OtherTypes"
#define DEV_TYPE_USB_CLASS_RESERVED				L"USB\\CLASS_00"
#define DEV_TYPE_USB_CLASS_AUDIO				L"USB\\CLASS_01"
#define DEV_TYPE_USB_CLASS_COMMUNICATIONS		L"USB\\CLASS_02"
#define DEV_TYPE_USB_CLASS_HUMAN_INTERFACE		L"USB\\CLASS_03"
#define DEV_TYPE_USB_CLASS_MONITOR				L"USB\\CLASS_04"
#define DEV_TYPE_USB_CLASS_PHYSICAL_INTERFACE	L"USB\\CLASS_05"
#define DEV_TYPE_USB_CLASS_POWER				L"USB\\CLASS_06"
#define DEV_TYPE_USB_CLASS_PRINTER				L"USB\\CLASS_07"
#define DEV_TYPE_USB_CLASS_STORAGE				L"USB\\CLASS_08"
#define DEV_TYPE_USB_CLASS_HUB					L"USB\\CLASS_09"
#define DEV_TYPE_USB_CLASS_VENDOR_SPECIFIC		L"USB\\CLASS_FF"

#endif