#define VER_INTERNALNAME_STR		"KLFLTDEV" 
#define VER_FILEDESCRIPTION_STR		"KLFLTDEV Pnp device filter"
#define VER_INTERNALEXTENSION_STR	"SYS"

#define VER_FILETYPE				VFT_DRV
#define VER_FILESUBTYPE				VFT2_DRV_SYSTEM

#define VER_FILEVERSION_HIGH		8
#define VER_FILEVERSION_LOW		0
#define VER_FILEVERSION_BUILD		0
#define VER_FILEVERSION_COMPILATION	14

#include <version/ver_product.h>
