ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=vmarea_test

INCLUDES= \
	$(ROOT)/include/Prague \
	$(ROOT)/include \
	$(ROOT)/CommonFiles

SOURCES= \
	vmarea_test.cpp

STDLIBS=$(DSOLIB)

include $(ROOT)/Makefiles/Make.Executable
