ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=interlocked_test

INCLUDES= \
	$(ROOT)/include/Prague \
	$(ROOT)/include \
	$(ROOT)/CommonFiles

SOURCES= \
	interlocked_test.cpp

STDLIBS=$(DSOLIB)

include $(ROOT)/Makefiles/Make.Executable
