ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=compatutils

INCLUDES= \
	$(ROOT)/include


SOURCES= \
	itoa.cpp \
	ltoa.cpp \
	itow.cpp \
	ltow.cpp \
	wtol.cpp \
	stricmp.cpp \
	strlwr.cpp \
	strnicmp.cpp \
	wcsicmp.cpp \
	wcsnicmp.cpp \
	toucs2le.cpp \
	_snprintf_s.c \
	sprintf_s.c \
	strcpy_s.c \
	strcat_s.c \
	memcpy_s.c \
	strncpy_s.c \
	wcscpy_s.c \
	wcscat_s.c \
	wcstombs_s.c \
	mbstowcs_s.c \
	vsprintf_s.c


include $(ROOT)/Makefiles/Make.Archive
