ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

INCLUDES= \
	$(ROOT)/include \


TARGET=hashutil

VCPROJ=hashutil.vcproj

SOURCESLIST=Sources.List

include $(ROOT)/Makefiles/Make.Archive
