ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=cab

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/CommonFiles \
	$(ROOT)/Prague

METAFILE=CAB.$(META)

SOURCESLIST=Sources.List

VCPROJ=CAB.vcproj

include $(ROOT)/Makefiles/Make.Plugin
