//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by srvloc_common.rc
//
#define IDS_KLSRV_LICENCE_CHECK_90      1024
#define IDS_KLSRV_LICENCE_CHECK_100_110 1025
#define IDS_KLSRV_LICENCE_CHECK_MORE_110 1026
#define IDS_KLSRV_NEW_HOST_DETECTED     1027
#define IDS_KLSRV_NEW_HOST_REDIRECTED   1028
#define IDS_KLSRV_HOSTS_CONFLICT        1029
#define IDS_KLSRV_HOSTS_NOT_VISIBLE     1030
#define IDS_KLSRV_INVISIBLE_HOSTS_REMOVED 1031
#define IDS_KLSRV_NO_SPACE_ON_VOLUMES   1032
#define IDS_KLSRV_NO_SPACE_IN_DATABASE  1033
#define IDS_KLSRV_DISK_FULL             1034
#define IDS_KLSRV_SHARED_FOLDER_UNAVAILABLE 1035
#define IDS_KLSRV_DATABASE_UNAVAILABLE  1036
#define IDS_KLSRV_DATABASE_FULL         1037
#define IDS_KLSRV_HOST_OUT_CONTROL      1039
#define IDS_KLSRV_HOST_MAY_BE_OUT_CONTROL 1040
#define IDS_KLSRV_HOST_STATUS_CRITICAL_0 1041
#define IDS_KLSRV_HOST_STATUS_CRITICAL_1 1042
#define IDS_KLSRV_HOST_STATUS_CRITICAL_2 1043
#define IDS_KLSRV_HOST_STATUS_CRITICAL_3 1044
#define IDS_KLSRV_HOST_STATUS_CRITICAL_4 1045
#define IDS_KLSRV_HOST_STATUS_CRITICAL_5 1046
#define IDS_KLSRV_HOST_STATUS_CRITICAL_6 1047
#define IDS_KLSRV_HOST_STATUS_CRITICAL_7 1048
#define IDS_KLSRV_HOST_STATUS_CRITICAL_8 1049
#define IDS_KLSRV_HOST_STATUS_WARNING_0 1050
#define IDS_KLSRV_HOST_STATUS_WARNING_1 1051
#define IDS_KLSRV_HOST_STATUS_WARNING_2 1052
#define IDS_KLSRV_HOST_STATUS_WARNING_3 1053
#define IDS_KLSRV_HOST_STATUS_WARNING_4 1054
#define IDS_KLSRV_HOST_STATUS_WARNING_5 1055
#define IDS_KLSRV_HOST_STATUS_WARNING_6 1056
#define IDS_KLSRV_HOST_STATUS_WARNING_7 1057
#define IDS_KLSRV_HOST_STATUS_WARNING_8 1058
#define IDS_KLSRV_HOST_STATUS_CRITICAL_9 1075
#define IDS_KLSRV_HOST_STATUS_WARNING_9 1076
#define IDS_KLSRV_LICENCE_CHECK_90_DN   4096
#define IDS_KLSRV_LICENCE_CHECK_100_110_DN 4097
#define IDS_KLSRV_LICENCE_CHECK_MORE_110_DN 4098
#define IDS_KLSRV_NEW_HOST_DETECTED_DN  4099
#define IDS_KLSRV_NEW_HOST_REDIRECTED_DN 4100
#define IDS_KLSRV_HOSTS_CONFLICT_DN     4101
#define IDS_KLSRV_HOSTS_NOT_VISIBLE_DN  4102
#define IDS_KLSRV_INVISIBLE_HOSTS_REMOVED_DN 4103
#define IDS_KLSRV_NO_SPACE_ON_VOLUMES_DN 4104
#define IDS_KLSRV_NO_SPACE_IN_DATABASE_DN 4105
#define IDS_KLSRV_DISK_FULL_DN          4106
#define IDS_KLSRV_SHARED_FOLDER_UNAVAILABLE_DN 4107
#define IDS_KLSRV_DATABASE_UNAVAILABLE_DN 4108
#define IDS_KLSRV_DATABASE_FULL_DN      4109
#define IDS_KLSRV_HOST_OUT_CONTROL_DN   4110
#define IDS_KLSRV_HOST_MAY_BE_OUT_CONTROL_DN 4111
#define IDS_KLSRV_HOST_STATUS_CRITICAL_DN 4112
#define IDS_KLSRV_HOST_STATUS_WARNING_DN 4113
#define IDS_KLAUD_SERVERCONNECT         4114
#define IDS_KLAUD_SERVERCONNECT_FORMAT  4115
#define IDS_KLAUD_EV_OBJECTMODIFY       4116
#define IDS_KLAUD_EV_OBJECTMODIFY_TASK_MODIFY 4117
#define IDS_KLAUD_EV_OBJECTMODIFY_TASK_ADDED 4118
#define IDS_KLAUD_EV_OBJECTMODIFY_TASK_DELETED 4119
#define IDS_KLAUD_EV_OBJECTMODIFY_GROUPTASK_MODIFY 4124
#define IDS_KLAUD_EV_OBJECTMODIFY_GROUPTASK_ADDED 4125
#define IDS_KLAUD_EV_OBJECTMODIFY_GROUPTASK_DELETED 4126
#define IDS_KLAUD_EV_OBJECTMODIFY_POLICY_MODIFY 4127
#define IDS_KLAUD_EV_OBJECTMODIFY_POLICY_ADDED 4128
#define IDS_KLAUD_EV_OBJECTMODIFY_POLICY_DELETED 4129
#define IDS_KLAUD_EV_OBJECTMODIFY_COMPONENT_MODIFY 4130
#define IDS_KLAUD_EV_OBJECTMODIFY_SERVER_MODIFY 4131
#define IDS_KLAUD_EV_OBJECT_STATE_CHANGED 4132
#define IDS_KLAUD_EV_OBJECT_TASK_STATE_CHANGED_RUN 4133
#define IDS_KLAUD_EV_OBJECT_TASK_STATE_CHANGED_STOP 4134
#define IDS_KLAUD_EV_OBJECT_TASK_STATE_CHANGED_SUSPEND 4135
#define IDS_KLAUD_EV_OBJECT_TASK_STATE_CHANGED_RESUME 4136
#define IDS_KLAUD_EV_OBJECT_GROUPTASK_STATE_CHANGED_RUN 4137
#define IDS_KLAUD_EV_OBJECT_GROUPTASK_STATE_CHANGED_STOP 4138
#define IDS_KLAUD_EV_OBJECT_GROUPTASK_STATE_CHANGED_SUSPEND 4139
#define IDS_KLAUD_EV_OBJECT_GROUPTASK_STATE_CHANGED_RESUME 4140
#define IDS_KLAUD_EV_OBJECT_COMPONENT_STATE_CHANGED_RUN 4141
#define IDS_KLAUD_EV_OBJECT_COMPONENT_STATE_CHANGED_STOP 4142
#define IDS_KLAUD_EV_ADMGROUP_CHANGED   4143
#define IDS_KLAUD_EV_ADMGROUP_CHANGED_MODIFY 4144
#define IDS_KLAUD_EV_ADMGROUP_CHANGED_ADDED 4145
#define IDS_KLAUD_EV_ADMGROUP_CHANGED_DELETED 4146
#define IDS_KLAUD_EV_ADMGROUP_CHANGED_HOST_ADDED 4147
#define IDS_KLAUD_EV_ADMGROUP_CHANGED_HOST_DELETED 4148
#define IDS_KLAUD_EV_OBJECTMODIFY_HOST_MODIFY 4149

#define IDS_KLBKP_RC_INVALID_CMDLINE 4150
#define IDS_KLBKP_RC_INVALID_PASSWORD 4151
#define IDS_KLBKP_RC_FAILED_OPEN_SCM 4152
#define IDS_KLBKP_RC_FAILED_STOP_SERVICE 4153
#define IDS_KLBKP_RC_FAILED_START_SERVICE 4154
#define IDS_KLBKP_RC_INVALID_DST_PATH 4155
#define IDS_KLBKP_RC_DST_NOT_EMPTY 4156
#define IDS_KLBKP_RC_DB_BACKUP_FAILED 4157
#define IDS_KLBKP_RC_UNEXPECTED 4158
#define IDS_KLBKP_RC_ALREADY_RUNNING 4159

#define IDS_KLAUD_EV_OBJECT_GLOBALTASK_STATE_CHANGED_RUN 4183
#define IDS_KLAUD_EV_OBJECT_GLOBALTASK_STATE_CHANGED_STOP 4184
#define IDS_KLAUD_EV_OBJECT_GLOBALTASK_STATE_CHANGED_SUSPEND 4185
#define IDS_KLAUD_EV_OBJECT_GLOBALTASK_STATE_CHANGED_RESUME 4186
#define IDS_KLAUD_EV_OBJECTMODIFY_GLOBALTASK_MODIFY 4180
#define IDS_KLAUD_EV_OBJECTMODIFY_GLOBALTASK_ADDED 4181
#define IDS_KLAUD_EV_OBJECTMODIFY_GLOBALTASK_DELETED 4182

#define IDS_KLAUD_EV_OBJECTMODIFY_REPORT_MODIFY 4190
#define IDS_KLAUD_EV_OBJECTMODIFY_REPORT_ADDED 4191
#define IDS_KLAUD_EV_OBJECTMODIFY_REPORT_DELETED 4192
#define IDS_KLAUD_EV_OBJECTMODIFY_REPORT_STATE_CHANGED_RUN 4193
#define IDS_KLAUD_EV_OBJECTMODIFY_IPDIAPASON_ADDED 4194
#define IDS_KLAUD_EV_OBJECTMODIFY_IPDIAPASON_MODIFY 4195
#define IDS_KLAUD_EV_OBJECTMODIFY_IPDIAPASON_DELETED 4196

#define IDS_KLAUD_EV_OBJECT_NETWORKLIST_STATE_CHANGED 4197
#define IDS_KLAUD_EV_NETWORK_LIST_TASK_RESTORE 4198
#define IDS_KLAUD_EV_NETWORK_LIST_TASK_DELETE 4199
#define IDS_KLAUD_EV_NETWORK_LIST_TASK_SCAN 4200
#define IDS_KLAUD_EV_NETWORK_LIST_QUARANTINE 4201
#define IDS_KLAUD_EV_NETWORK_LIST_BACKUP 4202

#define IDS_KLSRV_HOST_MOVED_WITH_RULE_EX  4203

#define IDS_KLAUD_SECURITYPOLICY_CHANGED 4300

#define IDS_PKGEL_ERR_SHOULD_STOP_CATCHED_TASK 50601

#define IDS_STDEL_FILE_OPEN_ERROR	50001
#define IDS_STDEL_FILE_IO_ERROR		50002
#define IDS_STDEL_FILESYSTEM_ERROR	50003
#define IDS_STDEL_FILE_MOVE_ERROR	50004
#define IDS_STDEL_FILE_COPY_ERROR	50005
#define IDS_STDEL_FILE_DELETE_ERROR	50006
#define IDS_STDEL_DIR_DELETE_ERROR	50007
#define IDS_STDEL_ERROR_INFO		50008
#define IDS_STDEL_APP_PENDING		50009
#define IDS_STDEL_MISSING_ARG       50010
#define IDS_STDEL_UNKNOWN_ARG       50011
#define IDS_STDEL_INVALID_ARG       50012

#define IDS_TREL_TR_CONN_BROKEN				50101
#define IDS_TREL_TR_METHOD_NOT_FOUND		50102
#define IDS_TREL_TR_TIMEOUT					50103
#define IDS_TREL_TR_TRANSPORT_ERROR			50104

#define IDS_PRCIEL_TASK_IS_RUNNING			50201

#define IDS_PRCPEL_ERR_CANT_CONNECT			50301
#define IDS_PRCPEL_ERR_UNEXPECTED_STOP			50302
#define IDS_PRCPEL_TR_GENERAL				50303
#define IDS_PRCPEL_TR_WRONG_ADDR			50304
#define IDS_PRCPEL_TR_REMOTE_CONN_ALREADY_EXISTS	50305
#define IDS_PRCPEL_TR_MAX_CONNECTIONS			50306
#define IDS_PRCPEL_TR_AUTHENTICATION_FAILED		50307
#define IDS_PRCPEL_TR_SSL_CONNECT_ERR			50308
#define IDS_PRCPEL_TR_SSL_SERVER_AUTH_ERR		50309
#define IDS_PRCPEL_TR_HOST_NOT_FOUND			50310
#define IDS_PRCPEL_TR_SOCKET_NOBUFS			50311

#define IDS_AGINSTEL_RUN_TASK_LOGONUSER_ERROR	50401
#define IDS_AGINSTEL_START_COMPONENT_WRONG_REGISTRATION		50402
#define IDS_AGINSTEL_START_COMPONENT_CANT_LOAD_BIN_MODULE	50403

#define IDS_NAGEL_WFW_FAILED_ACCESS_FM		50501
#define IDS_NAGEL_WFW_FAILED_ADD_PORT		50502
#define IDS_NAGEL_WFW_FAILED_REMOVE_PORT	50503
#define IDS_NAGEL_WFW_FAILED_GENERAL		50504
#define IDS_NAGNF_FULLSCAN_SENDING			50505
#define IDS_NAGNF_FULLSCAN_SENT				50506
#define IDS_NAGNF_PRES_ERROR				50507
#define IDS_NAGNF_TSK_TSK_CANCELED_BY_USER      50508
#define IDS_NAGNF_TSK_CANCELED_BY_NAGENT_STOP   50509

#define IDS_HSTGRPEL_ERR_NO_HOST_ADDRESS		50701
#define IDS_HSTGRPEL_ERR_HOST_NOT_RESPONDING		50702
#define IDS_HSTGRPEL_ERR_NO_NAGENT_PACKAGE		50703
#define IDS_HSTGRPEL_ERR_SLAVE_NOT_CONNECTED		50704
#define IDS_HSTGRPEL_ERR_FAILED_TO_SYNC_WITH_HOST	50705
#define IDS_HSTGRPEL_ERR_FAILED_TO_REPLICATE		50706
#define IDS_HSTGRPEL_ERR_FAILED_TO_SYNCHRONIZE		50707
#define IDS_HSTGRPEL_ERR_FAILED_TO_MERGE_POLICY		50708
#define IDS_HSTGRPEL_ERR_STOP_DUE_TO_ERROR		50709
#define IDS_HSTGRPEL_ERR_FAILED_TO_ACCESS_DB		50710
#define IDS_HSTGRPEL_ERR_INVALID_IP_RESOLUTION		50711

#define IDS_PRSSEL_STORAGE_CORRUPT	50801

#define IDS_CONNEL_FAILED_LOAD_CONNECTOR			50901
#define IDS_CONNEL_FAILED_INIT_CONNECTOR			50902
#define IDS_CONNEL_PRODUCT_SIDE_SETTINGS_CHANGED	50903
#define IDS_CONNEL_SERVER_SIDE_SETTINGS_CHANGED		50904
#define IDS_CONNEL_REPLICATION_FAILED				50905
#define IDS_CONNEL_REPLICATION_FAILED_FROM_PRODOUCT	50906
#define IDS_UPD_BINARY_5_0				50907

#define IDS_KLBKEL_INVALID_PASSWORD         51001
#define IDS_KLBKEL_FAILED_STOP_SERVICES     51002
#define IDS_KLBKEL_FAILED_START_SERVICES    51003
#define IDS_KLBKEL_INVALID_DST_PATH         51004
#define IDS_KLBKEL_DST_NOT_EMPTY            51005
#define IDS_KLBKEL_DB_BACKUP_FAILED         51006
#define IDS_KLBKEL_DB_BACKUP_FAILED_FILE    51007
#define IDS_KLBKEL_DB_RESTORE_FAILED_FILE   51008
#define IDS_KLBKEL_DB_ALREADY_RUNNING       51009
#define IDS_KLBKEL_DB_UNEXPECTED            51010
#define IDS_KLBKEL_DOWNGRADE                51011
#define IDS_KLBKEL_INCOMPATIBLE_DB_SERVERS  51012
#define IDS_KLBKEL_NO_FILE                  51013
#define IDS_KLBKEL_DB_NAME                  51014
#define IDS_KLBKEL_FULL_SUCCESS             51015
#define IDS_KLBKEL_ENTER_PASSWORD           51016
#define IDS_KLBKEL_REENTER_PASSWORD         51017
#define IDS_KLBKEL_ENTERED_PASSWORDS_DIFFER 51018
#define IDS_KLBKEL_DB_RESTORE_FAILED        51019
#define IDS_KLBKEL_PRC_SAVING_RESULTS               51020
#define IDS_KLBKEL_PRC_STARTING_KLBACKUP            51021
#define IDS_KLBKEL_PRC_INIT_DCOM                    51022
#define IDS_KLBKEL_PRC_INIT_LIBS                    51023
#define IDS_KLBKEL_PRC_CHECKING_ARGS                51024
#define IDS_KLBKEL_PRC_CHECKING_PATHS               51025
#define IDS_KLBKEL_PRC_OPENING_SCM                  51026
#define IDS_KLBKEL_PRC_PREPARING                    51027
#define IDS_KLBKEL_PRC_BACKUP_SAVING_SETTINGS       51028
#define IDS_KLBKEL_PRC_BACKUP_SAVING_DB             51029
#define IDS_KLBKEL_PRC_BACKUP_RESTORING_SETTINGS    51030
#define IDS_KLBKEL_PRC_BACKUP_RESTORING_DB          51031
#define IDS_KLBKEL_PRC_BACKUP_STARTING_SERVICE      51032
#define IDS_KLBKEL_PRC_BACKUP_STOPPING_SERVICE      51033
#define IDS_KLBKEL_FAILED                           51034


// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         80001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
