/* Generated by Together */

#ifndef _AG_AUTHTOKEN_H_
#define _AG_AUTHTOKEN_H_

namespace OnlineActivation
{
/** 
 * Authentication token interface.
 * @interface 
 */
class AuthToken
{
public:

	/** 
	 * Sets credentials.
	 */
	virtual void SetCredentials(const char* userName, const char* passWord) = 0;

protected:

	/**
	 * Destruction via delete is not allowed. 
	 */
	~AuthToken() {}
};
} // namespace OnlineActivation

#endif // _AG_AUTHTOKEN_H_
