ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=deflate

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/CommonFiles \

METAFILE=deflate_trans.$(META)

SOURCESLIST=Sources.List

VCPROJ=deflate.vcproj

include $(ROOT)/Makefiles/Make.Plugin
