ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=basework

INCLUDES= \
	. \
	../ \
	../include \
	../../CommonFiles

VCPROJ=BaseWork.vcproj

SOURCESLIST=Sources.List

include $(ROOT)/Makefiles/Make.Archive


