#if !defined(AFX_CONTROLTREECTRL_H__0E24BC46_DAE9_11D3_96B1_00D0B71DDDF6__INCLUDED_)
#define AFX_CONTROLTREECTRL_H__0E24BC46_DAE9_11D3_96B1_00D0B71DDDF6__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CControlTreeCtrl wrapper class

class CControlTreeCtrl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CControlTreeCtrl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xd2b34ae8, 0xb9cf, 0x11d2, { 0x96, 0xb0, 0x0, 0x10, 0x4b, 0x5b, 0x66, 0xaa } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	short GetBorderStyle();
	void SetBorderStyle(short);
	short GetAppearance();
	void SetAppearance(short);
	BOOL GetShowSelectionAlways();
	void SetShowSelectionAlways(BOOL);
	BOOL GetKeepExpandingStatus();
	void SetKeepExpandingStatus(BOOL);
	BOOL GetEnableChangeItemsState();
	void SetEnableChangeItemsState(BOOL);
	BOOL GetEnableOperationsOnDisabledItems();
	void SetEnableOperationsOnDisabledItems(BOOL);
	BOOL GetSaveExpandingStatus();
	void SetSaveExpandingStatus(BOOL);
	BOOL GetExpandSimpleLabelOnStart();
	void SetExpandSimpleLabelOnStart(BOOL);
	BOOL GetExpandCheckableItemOnCheck();
	void SetExpandCheckableItemOnCheck(BOOL);

// Operations
public:
	SCODE InitControl();
	SCODE SetPropertyTree(long hTree, long bRootIncluded);
	SCODE PurposeToChangeTree(long hNodeData);
	SCODE SetPropertyTreeEnabled(long bEnable);
	SCODE MergeDataTreeAndPattern(long hTreeData, long hPatternData, long* phResultData);
	SCODE ExtractValuesDataTree(long hTreeData, long* phResultData, long* pPropInclude);
	SCODE ChangeDisplayStrings();
	SCODE ExtractExpandingStatus(long hTreeData, long* phResultData);
	SCODE MergeDataTreeAndExpandingStatus(long hTreeData, long hStatusData);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CONTROLTREECTRL_H__0E24BC46_DAE9_11D3_96B1_00D0B71DDDF6__INCLUDED_)
