//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VisualEditor.rc
//
#define IDR_MAINFRAME                   1
#define IDI_INTERFACEENABLEDICON        2
#define IDI_INTERFACEDISABLEDICON       3
#define IDD_VISUALEDITOR_DIALOG         102
#define IDR_DIALOG_ACCELERATORS         129
#define IDR_MENUTOOLBAR                 130
#define IDR_DIALOG_MENU                 131
#define IDD_LARGECOMMENT_DLG            132
#define IDD_SELECTGENERATOR_DLG         133
#define IDD_CODEGENERATIONWIZARD_DLG    134
#define IDD_GENERATOROPTIONS_DLG        135
#define IDD_CODEGENGENERAL_DLG          137
#define IDD_SUMMARYINFO_DLG             138
#define IDD_PROPMEMBER_DLG              139
#define IDD_OPTIONSFILE_DLG             140
#define IDD_IMPORTDEF_DLG               141
#define IDD_HEADERGENERATIONWIZARD_DLG  142
#define IDD_SELECTINTERFACES_DLG        143
#define IDD_SELECTLOADEDINTERFACES_DLG  144
#define IDD_INTERFACENAME_DLG           146
#define IDD_RENAMEINTRELATED_DLG        147
#define IDD_CHOOSE_NAME_FROM_LIST_DLG   148
#define IDD_OPTIONS                     149
#define IDD_METHOD_DESCRIPTION          151
#define IDR_ACCELERATOR1                152
#define IDC_SPLITTER                    1000
#define IDC_INTERFACES_TREE             1001
#define IDC_IF_DESCRIPTION_TREE         1002
#define IDC_LARGECOMMENT_EDIT           1003
#define IDC_FILENAME                    1004
#define IDC_PM_STRUCTTREE               1005
#define IDC_PM_CLEANUP                  1006
#define IDC_CG_OBJECTS                  1007
#define IDC_CG_OBJINFO                  1008
#define IDC_CGW_DLGFRAME                1009
#define IDC_CGW_NEXT                    1010
#define IDC_CGW_BACK                    1011
#define IDC_CGW_FINISH                  1012
#define IDC_CGO_CTTCONTROL              1013
#define IDC_CGO_TITLE                   1014
#define IDC_CGG_SINGLEFILE_RBTN         1015
#define IDC_CGG_DIFFERENTFILE_RBTN      1016
#define IDC_CGS_EDITVIEW                1017
#define IDC_CGS_EDITFILENAME            1018
#define IDC_CGS_SAVEBUTTON              1019
#define IDC_CGS_AUTOSAVE                1020
#define IDC_CGOF_NEWSESSION_RBTN        1021
#define IDC_CGOF_USEFILE_RBTN           1022
#define IDC_CGOF_FILENAME               1023
#define IDC_CGOF_BROWSE                 1024
#define IDC_CGOF_LOADSTATUS             1025
#define IDC_CGOF_OUTPUTDIR              1026
#define IDC_CGOF_OUTPUTBROWSE           1027
#define IDC_CGOF_INCLUDEDIR             1028
#define IDC_CGOF_INCLUDEBROWSE          1029
#define IDC_HGW_FINISH                  1030
#define IDC_HGW_NEXT                    1031
#define IDC_HGW_BACK                    1032
#define IDC_HGW_DLGFRAME                1033
#define IDC_HGG_CTTCONTROL              1034
#define IDC_HGG_CTTTREE                 1035
#define IDC_IDF_LINKTOFILE_CBTN         1036
#define IDC_LARGECOMMENT_FONT_BUTTON    1037
#define IDC_SID_CTTTREE                 1038
#define IDC_NIN_NAMEEDIT                1040
#define IDC_RELATED_1_CHECK             1041
#define IDC_RELATED_2_CHECK             1042
#define IDC_RELATED_3_CHECK             1043
#define IDC_CG_ADDGENERATOR             1044
#define IDC_SB_TEXT                     1045
#define IDC_LIST_OF_NAMES               1047
#define IDC_OPTIONS_BOX                 1048
#define IDC_S_OUTPUT                    1049
#define IDC_S_INCLUDE                   1050
#define IDC_CG_REMOVE_GENERATOR         1051
#define IDC_CG_UPDATE_GENERATOR_LIST    1052
#define IDC_G_OBJECTS                   1053
#define IDC_FOLDER_BOX                  1054
#define IDC_USE_REGISTRY_NOT_SQL        1055
#define IDC_CB_RET_VAL                  1056
#define IDC_ED_NAME                     1057
#define IDC_PAR_LIST                    1059
#define IDC_ED_COMM_VAL                 1060
#define IDC_ED_COMM_SHORT               1061
#define IDC_ED_COMM_LARGE               1062
#define IDC_ED_COMM_BEHAV               1063
#define IDC_BT_PAR_ADD                  1064
#define IDC_BT_PAR_DEL                  1065
#define IDC_ED_PAR_COMM_SHORT           1066
#define IDC_RET_DEF_VAL                 1067
#define IDC_ED_PAR_COMM_LARGE           1068
#define IDC_ED_PAR_COMM_BEHAV           1069
#define IDC_BT_PAR_CHANGE               1070
#define IDC_CB_LANG                     1071
#define ID_FILE_EXIT                    32771
#define ID_FILE_SAVEAS                  32772
#define ID_EMPTY                        32773
#define ID_FILE_NEWIMP                  32774
#define ID_FILE_SRCGEN                  32775
#define ID_FILE_IMPORTDEF               32776
#define ID_FILE_SYNCHRONIZE             32777
#define ID_FILE_REINITISERVER           32778
#define ID_FILE_ADDDEF                  32779
#define ID_FILE_NEWDEF_BYBASE           32780
#define IDS_INTERFACESCLIPBOARDFORMAT   32790
#define IDS_DESCRIPTIONSCLIPBOARDFORMAT 32791
#define IDS_MAINTITLE                   32792
#define IDS_WINDOWTITLE                 32793
#define IDS_OCX_FILTER                  32794
#define IDS_COM_FILTER                  32795
#define IDS_MENU_EDIT_CUT               32796
#define IDS_MENU_EDIT_COPY              32797
#define IDS_MENU_EDIT_PASTE             32798
#define IDS_DATASTRUCTURE               32800
#define IDS_DATASTRUCTUREMEMBERS        32802
#define IDS_PROPERTIES                  32803
#define IDS_METHODS                     32804
#define IDS_SYSMETHODS                  32805
#define IDS_TYPES                       32806
#define IDS_CONSTANTS                   32807
#define IDS_INCLUDES                    32808
#define IDS_ERRORCODES                  32809
#define IDS_NEWINTERFACE                32810
#define IDS_NEWPROPERTY                 32811
#define IDS_NEWMETHOD                   32812
#define IDS_NEWMETHODPARAMETER          32813
#define IDS_NEWDATASRUCTURE             32814
#define IDS_NEWDATASRUCTUREMEMBER       32815
#define IDS_NEWTYPE                     32816
#define IDS_NEWCONSTANT                 32817
#define IDS_NEWERRORCODE                32818
#define IDS_METHODDESCRIPTION           32820
#define IDS_MNEMONIC_ID                 32821
#define IDS_INCLUDEFILE                 32822
#define IDS_OBJECTTYPE                  32823
#define IDS_PROPLOCAL                   32824
#define IDS_PROPSHARED                  32825
#define IDS_PROPREQUIRED                32826
#define IDS_PROPNONE                    32827
#define IDS_PROPREAD                    32828
#define IDS_PROPWRITE                   32829
#define IDS_PROPREADWRITE               32830
#define IDS_PROPPOINTER                 32831
#define IDS_MEMBERISARRAY               32832
#define IDS_PLUGIN                      32833
#define IDS_CONST                       32834
#define IDS_PLMNEMONIC_ID               32835
#define IDS_STATIC                      32836
#define IDS_PROPFORWRITE                32837
#define IDS_TRANSFERPROPUP              32838
#define IDS_LASTCALLPROP                32839
#define IDS_INTERFACEFLAGS              32840
#define IDS_NONSWAPABLE                 32841
#define IDS_POINTER                     32842
#define IDS_IFACE_FLAG_SYNCHRONIZED     32843
#define IDS_PROPWRITABLEDURINGINIT      32844
#define IDS_IFACE_FLAG_CS               32845
#define IDS_IFACE_FLAG_MUTEX            32846
#define IDS_SYSTEM                      32847
#define IDS_MNEMONICID_PREFIX           32850
#define IDS_DIGITALID_PREFIX            32851
#define IDS_REVISIONID_PREFIX           32852
#define IDS_CREATIONDATE_PREFIX         32853
#define IDS_INCLUDEFILE_PREFIX          32854
#define IDS_OBJECTTYPE_PREFIX           32855
#define IDS_SHORTCOMMENT_PREFIX         32856
#define IDS_LARGECOMMENT_PREFIX         32857
#define IDS_BEHAVIORCOMMENT_PREFIX      32858
#define IDS_VALUECOMMENT_PREFIX         32859
#define IDS_RESULTNAME_PREFIX           32860
#define IDS_RESULTDEFVALUE_PREFIX       32861
#define IDS_PARAMTYPENAME_PREFIX        32862
#define IDS_PROPTYPENAME_PREFIX         32863
#define IDS_DSMTYPENAME_PREFIX          32864
#define IDS_PLSMEMBER_PREFIX            32865
#define IDS_PLSREADFUNC_PREFIX          32866
#define IDS_PLSWRITEFUNC_PREFIX         32867
#define IDS_PROPVARIABLE_PREFIX         32868
#define IDS_PROPDEFVALUE_PREFIX         32870
#define IDS_DSMARRAYBOUND_PREFIX        32871
#define IDS_PLNAME_PREFIX               32872
#define IDS_PLDIGITALID_PREFIX          32873
#define IDS_PLVERSION_PREFIX            32874
#define IDS_SUBTYPEID_PREFIX            32875
#define IDS_AUTORNAME_PREFIX            32876
#define IDS_BASETYPENAME_PREFIX         32877
#define IDS_CONSTTYPENAME_PREFIX        32878
#define IDS_VALUE_PREFIX                32879
#define IDS_PLVENDORID_PREFIX           32880
#define IDS_PLCODEPAGE_PREFIX           32881
#define IDS_PLDATEFORMAT_PREFIX         32882
#define IDS_OUTPUTFILE_PREFIX           32883
#define IDS_PLAUTHORNAME_PREFIX         32884
#define IDS_PLPROJECTNAME_PREFIX        32885
#define IDS_PLSUBPROJECTNAME_PREFIX     32886
#define IDS_FILE_GENERATEHEADER         32890
#define IDS_FILE_GENERATESOURCE         32891
#define IDS_IPP_DEFEXTENTION            32892
#define IDS_IPI_DEFEXTENTION            32893
#define IDS_IPI_FILTER                  32894
#define IDS_IPP_FILTER                  32895
#define IDS_IP_FILTER                   32896
#define IDS_CGO_DEFEXTENTION            32897
#define IDS_CGO_FILTER                  32898
#define IDS_HGO_DEFEXTENTION            32899
#define IDS_HGO_FILTER                  32900
#define IDS_SM_NEWOBJECT                32901
#define IDS_SM_RECOGNIZE                32902
#define IDS_SM_CLOSE                    32903
#define IDS_SM_INIT                     32904
#define IDS_SM_INIT_DONE                32905
#define IDS_SM_RECEIVEMSG               32906
#define IDS_SM_IFACETRANSFER            32907
#define IDS_CG_OD_DESCRIPTION           32910
#define IDS_CG_OD_VENDOR                32911
#define IDS_CG_OD_VERSION               32912
#define IDS_CG_OAI_CATEGORY             32913
#define IDS_CG_OAI_VALUE                32914
#define IDS_CGW_NEXTBTN                 32920
#define IDS_CGW_FINISHBTN               32921
#define IDS_CGW_SEVERALINT              32922
#define IDS_CGW_ERR_NOINTERFACES        32923
#define IDS_CGW_ERR_GENERATION          32924
#define IDS_CGW_ERR_GENERATION_FALSE    32925
#define IDS_CGW_ERR_SUCCEEDED           32926
#define IDS_CGW_ERR_SOMEERROR           32927
#define IDS_CGW_ERR_SETTYPES            32928
#define IDS_CGW_ERR_NOGENERATORS        32929
#define IDS_CGW_ERR_INITFAILED          32930
#define IDS_CGO_TITLE                   32932
#define IDS_CGO_DLGFILTER               32933
#define IDS_CGO_DLGSUBFILTER_1          32934
#define IDS_CGO_DLGSUBFILTER_2          32935
#define IDS_CGO_DLGSUBFILTER_3          32936
#define IDS_CGS_INTERFACENAME           32937
#define IDS_CGOF_LOADED                 32938
#define IDS_CGOF_NOTLOADED              32939
#define IDS_HGW_ERR_NOINTERFACES        32940
#define IDS_HGW_ERR_GENERATION          32941
#define IDS_HGW_ERR_GENERATION_FALSE    32942
#define IDS_HGW_ERR_SUCCEEDED           32943
#define IDS_HGW_ERR_SOMEERROR           32944
#define IDS_HGW_ERR_SETTYPES            32945
#define IDS_HGW_ERR_INITFAILED          32946
#define IDS_LET_LARGECOMMENT            32950
#define IDS_LET_BEHAVIORCOMMENT         32952
#define IDS_LET_VALUECOMMENT            32953
#define IDS_FILESYNCHRONIZATIONCOMPLETED 32954
#define IDS_SYNCHRONIZATIONCOMPLETED    32955
#define IDS_NOUIDSFORSYNCHRONIZATION    32956
#define IDS_ERRORISWARNING              32957
#define IDS_METHODPARAMETERS            32958
#define IDS_AUTOSTART                   32959
#define IDS_CG_DEFEXTENTION             32960
#define IDS_CG_FILTER                   32961
#define IDS_OUPUTFILE                   32999
#define IDS_ERR_SAVEREQUEST             33000
#define IDS_ERR_CANCLOSE                33001
#define IDS_ERR_OPENCLIPBOARD           33002
#define IDS_ERR_EMPTYCLIPBOARD          33003
#define IDS_ERR_SETCLIPDATA             33004
#define IDS_ERR_CLIPRECURSION           33005
#define IDS_ERR_CLIPIDALREADYEXISTS     33006
#define IDS_ERR_INCORRECTIDVALUE        33007
#define IDS_ERR_IFALREADYEXISTS         33008
#define IDS_ERR_INCORRECTNAMEVALUE      33009
#define IDS_ERR_IFMALREADYEXISTS        33010
#define IDS_ERR_IFMPALREADYEXISTS       33011
#define IDS_ERR_IFPALREADYEXISTS        33012
#define IDS_ERR_IFPIDALREADYEXISTS      33013
#define IDS_ERR_WRITEFILE               33014
#define IDS_ERR_READFILE                33015
#define IDS_ERR_INCORRECTPASTE          33016
#define IDS_ERR_INCORRECTFILETYPE       33017
#define IDS_ERR_IFONAMEALREADYEXISTS    33018
#define IDS_ERR_IFONAMEUSED             33019
#define IDS_ERR_NODENOTMEMBER           33020
#define IDS_ERR_DIFFERENTTYPES          33021
#define IDS_ERR_LOADINTERFACEFAILED     33022
#define IDS_ERR_DUPLICATEINTNAME        33023
#define IDS_ERR_ALREADYIMPORTED         33024
#define IDS_ERR_REMOVELINKED            33025
#define IDS_ERR_IFTALREADYEXISTS        33026
#define IDS_ERR_IFCALREADYEXISTS        33027
#define IDS_ERR_IFPIDOUTOFRANGE         33028
#define IDS_ERR_PIDS_ERROR              33029
#define IDS_ERR_IDALREADYUSED           33030
#define IDS_ERR_VALUEOUTOFRANGE         33031
#define IDS_ERR_INCORRECTVALUE          33032
#define IDS_ERR_DISCARDDEFVALUE         33033
#define IDS_ERR_MERGEDISCARDDEFVALUE    33034
#define IDS_ERR_TYPENAMEUSED            33035
#define IDS_ERR_TYPENAMEUSEDDEL         33036
#define IDS_ERR_OCXNOTREGISTERED        33038
#define IDS_ERR_OCXREGISTRATION         33039
#define IDS_ERR_OPENOCXTITLE            33040
#define IDS_ERR_COMNOTREGISTERED        33041
#define IDS_ERR_COMREGISTRATION         33042
#define IDS_ERR_OPENCOMTITLE            33043
#define IDS_ERR_FILEEXISTS              33044
#define IDS_ERR_MERGEDISCARDCONSTANT    33045
#define IDS_ERR_IFEXISTS                33046
#define IDS_ERR_VALUEOUTOFLENGTH        33047
#define IDS_ERR_INCOMPATIBLEFILES       33048
#define IDS_ERR_PIS_ERROR               33049
#define IDS_ERR_MERGEDISCARDERRCODE     33050
#define IDS_ERR_MERGEDISCARDTYPE        33051
#define IDS_TITLE_CHOOSE_TYPE_DLG       33052
#define IDS_MESSAGES                    33053
#define IDS_NEW_MESSAGE_CLASS           33054
#define IDS_NEW_MESSAGE                 33055
#define IDS_MSG_CONTEXT_PREFIX          33056
#define IDS_MSG_DATA_PREFIX             33057
#define IDS_IDENTIFICATOR_PREFIX        33058
#define IDS_ERR_IFCNALREADYEXISTS       33059
#define IDS_ERR_IFMNALREADYEXISTS       33060
#define IDS_CLASSES_OF_MESSAGES         33061
#define IDS_MSG_SEND_POINT_PREFIX       33062
#define IDS_LET_MSG_SEND_POINT          33063
#define IDS_LET_MSG_CONTEXT             33064
#define IDS_LET_MSG_DATA                33065
#define IDS_DEFAULT_PLUGIN_NAME_WARNING 33066
#define IDS_DEFAULT_PLUGIN_PID_WARNING  33067
#define ID_OPTIONS                      33068
#define IDS_OPTIONS_SAVE_FAILED         33068
#define ID_ACCEL33069                   33069
#define IDS_IMPLCOMMENT_PREFIX          33069
#define IDS_LET_IMPLCOMMENT             33070
#define IDS_NEWINCLUDE                  33071

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         33071
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
