# THE file to change VERSION information			 
								
PRODUCT_NAME_STR=Kaspersky Anti-Virus
PRODUCT_VERSION_HIGH=8
PRODUCT_VERSION_LOW=0
PRODUCT_BUILD=0
PRODUCT_COMPILATION=168
PRODUCT_STATE=Beta

PRODUCT_VERSION_STR=$(PRODUCT_VERSION_HIGH).$(PRODUCT_VERSION_LOW).$(PRODUCT_BUILD).$(PRODUCT_COMPILATION)
								
