ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=base64

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/CommonFiles

METAFILE=base64.$(META)

SOURCESLIST=Sources.List

VCPROJ=base64.vcproj

include $(ROOT)/Makefiles/Make.Plugin
