ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=explode

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/CommonFiles

METAFILE=explode_trans.$(META)

SOURCESLIST=Sources.List

VCPROJ=Explode.vcproj

include $(ROOT)/Makefiles/Make.Plugin
