ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=unlzx

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/CommonFiles \

METAFILE=UnLZX.$(META)

SOURCESLIST=Sources.List

VCPROJ=unlzx.vcproj

include $(ROOT)/Makefiles/Make.Plugin
