ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=metautils

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/CommonFiles

SOURCESLIST=Sources.List

VCPROJ=metautils.vcproj

HOSTONLY=1

include $(ROOT)/Makefiles/Make.Archive
