ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=dmap

INCLUDES= \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/include \
	$(ROOT)/CommonFiles

METAFILE=dmap.$(META)

SOURCESLIST=Sources.List

VCPROJ=dmap.vcproj

include $(ROOT)/Makefiles/Make.Plugin
