ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=buffer

INCLUDES= \
	$(ROOT)/include/Prague \
	$(ROOT)/include \
	$(ROOT)/CommonFiles

METAFILE=buffer.$(META)

SOURCESLIST=Sources.List

VCPROJ=buffer.vcproj

include $(ROOT)/Makefiles/Make.Plugin
