// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "coolbarctrl.h"

/////////////////////////////////////////////////////////////////////////////
// CCoolBarCtrl

IMPLEMENT_DYNCREATE(CCoolBarCtrl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CCoolBarCtrl properties

short CCoolBarCtrl::GetAppearance()
{
	short result;
	GetProperty(DISPID_APPEARANCE, VT_I2, (void*)&result);
	return result;
}

void CCoolBarCtrl::SetAppearance(short propVal)
{
	SetProperty(DISPID_APPEARANCE, VT_I2, propVal);
}

short CCoolBarCtrl::GetBorderStyle()
{
	short result;
	GetProperty(DISPID_BORDERSTYLE, VT_I2, (void*)&result);
	return result;
}

void CCoolBarCtrl::SetBorderStyle(short propVal)
{
	SetProperty(DISPID_BORDERSTYLE, VT_I2, propVal);
}

BOOL CCoolBarCtrl::GetHighlightSelectedItem()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CCoolBarCtrl::SetHighlightSelectedItem(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

BOOL CCoolBarCtrl::GetAnimation()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CCoolBarCtrl::SetAnimation(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL CCoolBarCtrl::GetDisplayFolders()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CCoolBarCtrl::SetDisplayFolders(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

BOOL CCoolBarCtrl::GetSmallIconView()
{
	BOOL result;
	GetProperty(0x12, VT_BOOL, (void*)&result);
	return result;
}

void CCoolBarCtrl::SetSmallIconView(BOOL propVal)
{
	SetProperty(0x12, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CCoolBarCtrl operations

SCODE CCoolBarCtrl::AddFolder(long nFolderNameID, LPCTSTR pFolderName, long* pnFolderIndex)
{
	SCODE result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_PI4;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_ERROR, (void*)&result, parms,
		nFolderNameID, pFolderName, pnFolderIndex);
	return result;
}

SCODE CCoolBarCtrl::AddFolderItem(long nFolderIndex, long hItemIcon, long nItemNameID, LPCTSTR pItemName, long nItemID)
{
	SCODE result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_BSTR VTS_I4;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_ERROR, (void*)&result, parms,
		nFolderIndex, hItemIcon, nItemNameID, pItemName, nItemID);
	return result;
}

SCODE CCoolBarCtrl::InsertFolderItem(long nFolderIndex, long nItemIndex, long hItemIcon, long nItemNameID, LPCTSTR pItemName, long nItemID)
{
	SCODE result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_BSTR VTS_I4;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_ERROR, (void*)&result, parms,
		nFolderIndex, nItemIndex, hItemIcon, nItemNameID, pItemName, nItemID);
	return result;
}

SCODE CCoolBarCtrl::RemoveFolder(long nFolderIndex)
{
	SCODE result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_ERROR, (void*)&result, parms,
		nFolderIndex);
	return result;
}

SCODE CCoolBarCtrl::RemoveFolderItem(long nFolderIndex, long nItemIndex)
{
	SCODE result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_ERROR, (void*)&result, parms,
		nFolderIndex, nItemIndex);
	return result;
}

SCODE CCoolBarCtrl::SetFolderName(long nFolderIndex, long nFolderNameID, LPCTSTR pFolderName)
{
	SCODE result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BSTR;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_ERROR, (void*)&result, parms,
		nFolderIndex, nFolderNameID, pFolderName);
	return result;
}

SCODE CCoolBarCtrl::SetFolderItemName(long nFolderIndex, long nItemIndex, long nItemNameID, LPCTSTR pItemName)
{
	SCODE result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_BSTR;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_ERROR, (void*)&result, parms,
		nFolderIndex, nItemIndex, nItemNameID, pItemName);
	return result;
}

SCODE CCoolBarCtrl::SetFolderItemID(long nFolderIndex, long nItemIndex, long nItemID)
{
	SCODE result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_ERROR, (void*)&result, parms,
		nFolderIndex, nItemIndex, nItemID);
	return result;
}

SCODE CCoolBarCtrl::ReplaceFolderItemID(long nFolderIndex, long nOldItemID, long nNewItemID)
{
	SCODE result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_ERROR, (void*)&result, parms,
		nFolderIndex, nOldItemID, nNewItemID);
	return result;
}

SCODE CCoolBarCtrl::SetActiveFolder(long nFolderIndex, long nItemIndex)
{
	SCODE result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_ERROR, (void*)&result, parms,
		nFolderIndex, nItemIndex);
	return result;
}

SCODE CCoolBarCtrl::ChangeLocalization()
{
	SCODE result;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_ERROR, (void*)&result, NULL);
	return result;
}

SCODE CCoolBarCtrl::GetActiveFolder(long* pnFolderIndex, long* pnItemIndex)
{
	SCODE result;
	static BYTE parms[] =
		VTS_PI4 VTS_PI4;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_ERROR, (void*)&result, parms,
		pnFolderIndex, pnItemIndex);
	return result;
}

SCODE CCoolBarCtrl::SetSelectedFolder(long nFolderIndex)
{
	SCODE result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_ERROR, (void*)&result, parms,
		nFolderIndex);
	return result;
}

SCODE CCoolBarCtrl::GetDisplayIconStatus(long* nStatus)
{
	SCODE result;
	static BYTE parms[] =
		VTS_PI4;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_ERROR, (void*)&result, parms,
		nStatus);
	return result;
}

SCODE CCoolBarCtrl::GetFolderCount(long* nCount)
{
	SCODE result;
	static BYTE parms[] =
		VTS_PI4;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_ERROR, (void*)&result, parms,
		nCount);
	return result;
}

SCODE CCoolBarCtrl::GetFolderItemCount(long nFolderIndex, long* nCount)
{
	SCODE result;
	static BYTE parms[] =
		VTS_I4 VTS_PI4;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_ERROR, (void*)&result, parms,
		nFolderIndex, nCount);
	return result;
}
