//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AvpgCfg.rc
//
#define IDS_ERROR                       1
#define IDS_REPORT_DATETIME             2
#define IDS_REPORT_DESCRIPTION          3
#define IDS_REPORT_ACTION               4
#define IDS_REPORT_INFO                 5
#define IDS_REPORT_APPNAME              6
#define IDS_REPORT_FUNCTION             7
#define IDD_DIALOG_TREEMODE             4000
#define IDB_HELP                        4001
#define IDR_MENU_POPUP                  4002
#define IDB_WAS_CTRLTREEIMAGE           4003
#define IDR_MENU_POPUP_DEBUG            4003
#define IDD_DIALOG_CONFIG               4004
#define IDC_TREE                        4005
#define IDD_DIALOG_LOG                  4005
#define IDD_DIALOG_ADDDEFAULTFILTER     4006
#define IDD_DIALOG_LISTMODE             4007
#define IDC_TAB                         4008
#define IDC_LIST                        4009
#define ID_ICON_CHANGEDEFFILTERS        4011
#define IDC_AVPCOOLBAR                  4012
#define ID_ICON_LOG                     4012
#define IDC_STATIC_FRAME                4013
#define ID_ICON_TREEVIEW                4013
#define ID_ICON_DYNAMICINFO             4015
#define IDD_DIALOG_ADDNEWFILTER         4017
#define IDC_AVPREPORTVIEW               4017
#define IDD_DIALOG_EDITPARAM            4018
#define IDC_CHECK_AUTOTRACKING          4018
#define IDC_COMBO_SESSIONS              4020
#define IDC_EDIT_APPID                  4021
#define IDD_DIALOG_APPID                4022
#define IDC_RADIO_POSITION              4022
#define IDC_RADIO_POS2                  4023
#define IDD_DIALOG_OAS                  4023
#define IDC_COMBO_PROCESS               4023
#define IDC_RADIO_POS3                  4024
#define IDD_DIALOG_CLIENT_INFO          4024
#define IDC_CHECK_REG_CREATE            4025
#define IDC_CHECK_REG_OPEN              4026
#define IDC_CHECK_REG_QUERY             4027
#define IDC_CHECK_REG_SETVALUE          4028
#define IDC_EDIT_REG_MASK               4029
#define IDC_CHECK_FO_CREATE             4030
#define IDC_CHECK_FO_CLOSE              4031
#define IDC_CHECK_FO_READ               4032
#define IDC_CHECK_FO_WRITE              4033
#define IDC_EDIT_FO_MASK                4034
#define IDC_EDIT_LOGFILENAME            4035
#define IDC_COMBO_STATUS                4040
#define IDC_STATIC_TOTALEVENTS          4041
#define IDC_STATIC_MARKEDEVENTS         4042
#define IDC_STATIC_UNMARKEDEVENTS       4043
#define IDC_STATIC_REPLYWAITERENTERS    4044
#define IDC_STATIC_DEADLOCKCOUNT        4045
#define IDC_BUTTON_REFRESH              4046
#define IDC_STATIC_FILTEREVENTENTERSCOUNT 4047
#define IDS_TREEROOT                    6301
#define IDS_REQUESTTIMEOUTFMT           6302
#define IDS_MENU_DDELETECURRENTFILTER   6303
#define IDS_MENU_REFRESHFILTERTREE      6304
#define IDS_FILE_OP                     6305
#define IDS_EXE_FILE_LIST               6306
#define IDS_EXE_FILE_NEW                6307
#define IDS_FILEOP_DENY_W               6308
#define IDS_FILEOP_DENY_D               6309
#define IDS_FILEOP_DENY_R               6310
#define IDS_DISK_OP                     6311
#define IDS_DISK_DENY_W_MB              6312
#define IDS_DISK_DENY_W_B               6313
#define IDS_DISK_DENY_F                 6314
#define IDS_REG_OP                      6315
#define IDS_DENY_CREATE_AUTOSTART       6316
#define IDS_DENY_CREATE_NEW_S_D         6317
#define IDS_DENY                        6318
#define IDS_PROMPT                      6319
#define IDS_LOGTHISEVENT                6320
#define IDS_AVPI_SIMPLEMODE             6321
#define IDS_AVPI_ADVANCEDMODE           6322
#define IDS_AVPI_CHANGEDEFFILTERS       6323
#define IDS_TREEMODE                    6324
#define IDS_LISTMODE                    6325
#define IDS_MENU_ADDNEWFILTER           6326
#define ID_ICON_LISTVIEW                6327
#define IDS_DYNAMICINFO                 6328
#define IDS_LOG                         6329
#define IDS_DEFAULTPERMIT               6330
#define IDS_DEFAULTDENY                 6331
#define IDS_PERMIT                      6332
#define IDS_REQUESTTIMEOUT              6333
#define IDS_OBJECTFMT                   6334
#define IDS_PROCESSFMT                  6335
#define IDS_FILTEREXPIREDFMT            6336
#define IDS_ERRORMSG                    6337
#define IDS_STRINGLENGTHFMT             6338
#define IDS_EXPECTEDNUMBER              6339
#define IDS_TIMEOUTRANGE                6340
#define	IDS_IPFMT_SRC					6341
#define	IDS_IPFMT_DST					6342
#define IDS_IPPORTFMT					6343
#define IDS_PORTRANGE					6344
#define IDMI_EXIT                       32772
#define IDMI_WIZARD                     32773
#define IDMI_CHANGEAPPID                32774
#define IDMI_WIZARD_DEF_FILTERS         32775
#define IDMI_CLIENTINFO                 32776
#define IDMI_REFRESHFILTERTREE          43773
#define IDMI_ADDNEWFILTER               43774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4026
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         4047
#define _APS_NEXT_SYMED_VALUE           4000
#endif
#endif
