ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=treesearchlib

INCLUDES= \
	$(ROOT)/include


VCPROJ=TreeSearchLib.vcproj

SOURCESLIST=Sources.List

include $(ROOT)/Makefiles/Make.Archive

