ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=thpoolimp

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/CommonFiles

STDLIBS=$(THREADSLIB)

METAFILE=thpoolimp.$(META)

SOURCESLIST=Sources.List

VCPROJ=thpoolimp.vcproj

include $(ROOT)/Makefiles/Make.Plugin
