//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by COMMON.rc
//
#define IDS_COMMON_PRODUCT_NAME         7000
#define IDS_COM_ALL_FILE_MASK           7001
#define IDS_COM_ALL_FILES               7002
#define IDS_COM_ALL_MASKS               7003
#define IDS_COM_HELP                    7004
#define IDS_COM_NOMAPI                  7005
#define IDS_COM_MAPI_ERROR              7006
#define IDS_COMMON_BUTTON_OK_STR        7007
#define IDS_COMMON_BUTTON_CANCEL_STR    7008
#define IDS_COMMON_BUTTON_YES_STR       7009
#define IDS_COMMON_BUTTON_NO_STR        7010
#define IDS_COM_MAPIDLL_NOT_FOUND       7017
#define IDS_COMMON_SOUND_EVENT_INFECTED 7018
#define IDS_COMMON_SOUND_EVENT_PASSWORD_REQUEST 7020
#define IDS_COMMON_SOUND_EVENT_PRODUCT_START 7021
#define IDS_COMMON_SOUND_EVENT_PRODUCT_FINISH 7022
#define IDS_COMMON_BUTTON_CHOOSE_STR    7023
#define IDS_COMMON_STATIC_FILE_TYPE_STR 7024
#define IDS_COMMON_STATIC_FILE_NAME_STR 7025
#define IDS_COMMON_STATIC_LOOK_IN_STR   7026
#define IDS_COMMON_TITLE_INVALID_SYMBOL 7027
#define IDS_COMMON_ONLY_NUMBERS_ALLOWED 7028
#define IDS_COMMON_CANNOT_FIND_KAVSEND  7029
#define IDS_COMMON_CANNOT_SEND_MAIL     7030
#define IDS_COMMON_CANNOT_FIND_ATTACH   7031
#define IDS_COMMON_KAVSEND_CORRUPTED    7035
#define IDC_KAP_LINKHAND                7040
#define IDI_KAP_HELP                    7041
#define IDB_COMMON_SORT_UP              7042
#define IDB_COMMON_SORT_DOWN            7043
#define IDR_COMMON_PNG_ERROR_SMALL      7044
#define IDR_COMMON_PNG_ERROR_BIG        7045
#define IDR_COMMON_PNG_WARN_SMALL       7046
#define IDR_COMMON_PNG_WARN_BIG         7047
#define IDR_COMMON_PNG_INFO_SMALL       7048
#define IDR_COMMON_PNG_INFO_BIG         7049
#define IDR_COMMON_PNG_OK_SMALL         7050
#define IDR_COMMON_PNG_OK_BIG           7051
#define IDB_COMMON_FEWER_INFO_ARROWS    7052
#define IDB_COMMON_MORE_INFO_ARROWS     7053
#define IDR_COMMON_PNG_PAUSE_SMALL      7054
#define IDR_COMMON_PNG_PAUSE_BIG        7055
#define IDB_COMMON_LOCK_BITMAP          7057
#define IDB_COMMON_LOCK_BITMAP_MASK     7059
#define IDI_COMMON_CTRL_LOCK            7060
#define IDS_COMMON_SOUND_EVENT_ODS_TASK_STARTED_BY_USER 7061
#define IDI_COMMON_FEWER_INFO_ARROWS    7061
#define IDS_COMMON_SOUND_EVENT_ODS_TASK_STARTED_BY_SCHEDULER 7062
#define IDI_COMMON_MORE_INFO_ARROWS     7062
#define IDS_COMMON_SOUND_EVENT_ODS_TASK_COMPLETED 7063
#define IDS_COMMON_SOUND_EVENT_ODS_TASK_FAILED 7064
#define IDS_COMMON_SOUND_EVENT_UPDATER_TASK_STARTED_BY_USER 7065
#define IDS_COMMON_SOUND_EVENT_UPDATER_TASK_STARTED_BY_SCHEDULER 7066
#define IDS_COMMON_SOUND_EVENT_UPDATER_TASK_COMPLETED 7067
#define IDS_COMMON_SOUND_EVENT_UPDATER_TASK_FAILED 7068
#define IDS_COMMON_SOUND_EVENT_RTP_TASK_STARTED 7069
#define IDS_COMMON_SOUND_EVENT_RTP_TASK_COMPLETED 7070
#define IDS_COMMON_SOUND_EVENT_RTP_TASK_FAILED 7071
#define IDS_COMMON_SOUND_EVENT_ATTACK_DETECTED 7072

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        7062
#define _APS_NEXT_COMMAND_VALUE         35000
#define _APS_NEXT_CONTROL_VALUE         7054
#define _APS_NEXT_SYMED_VALUE           7054
#endif
#endif
