ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=nfio_test

INCLUDES= \
	$(ROOT)/include/Prague \
	$(ROOT)/include \
	$(ROOT)/CommonFiles

SOURCES= \
	nfio_test.cpp

STDLIBS=$(DSOLIB)

include $(ROOT)/Makefiles/Make.Executable
