ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=hashcontainer

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/AV \
	$(ROOT)/include/Extract \
	$(ROOT)/include/ProductCore \
	$(ROOT)/CommonFiles

METAFILE=hashcont.$(META)

SOURCESLIST=Sources.List

VCPROJ=hashcontainer.vcproj

include $(ROOT)/Makefiles/Make.Plugin
