/*!
 * (C) 2002 "Kaspersky Lab"
 *
 * \file errintervals.h
 * \author Андрей Кулага
 * \date 2002
 * \brief Диапазоны ошибок для модулей продуктов компании "Лаборатория Касперского".
 *
 */

#ifndef KL_ERRINTERVALS_H
#define KL_ERRINTERVALS_H

// Определения диапазонов ошибок для отдельных подсистем продуктов.

// Диапазон ошибок для проекта CS Admin Kit 1000-2000
#define KLCSADMINKITERRSTART 1000

// Диапазон ошибок для проекта Updater 2000-2100
#define KLUPDATERERRSTART  2000

// Определения диапазонов ошибок для модулей проекта CS Admin Kit

#define KLEVERRSTART        (KLCSADMINKITERRSTART+20)
#define KLPARERRSTART       (KLCSADMINKITERRSTART+40)
#define KLPRCIERRSTART      (KLCSADMINKITERRSTART+60)
#define KLPRCPERRSTART      (KLCSADMINKITERRSTART+80)
#define KLPRESERRSTART      (KLCSADMINKITERRSTART+100)
#define KLPRSSERRSTART      (KLCSADMINKITERRSTART+120)
#define KLPRTSERRSTART      (KLCSADMINKITERRSTART+140)
#define KLSCHERRSTART       (KLCSADMINKITERRSTART+160)
#define KLSTDERRSTART       (KLCSADMINKITERRSTART+180)
#define KLTRERRSTART        (KLCSADMINKITERRSTART+250)
#define KLAGINSTERRSTART    (KLCSADMINKITERRSTART+320)
#define KLPKGERRSTART       (KLCSADMINKITERRSTART+340)
#define KLFUERRSTART        (KLCSADMINKITERRSTART+360)
#define KLEVPERRSTART       (KLCSADMINKITERRSTART+380)
#define KLTSKERRSTART       (KLCSADMINKITERRSTART+400)
#define KLJRNLERRSTART      (KLCSADMINKITERRSTART+420)
#define KLWATERRSTART       (KLCSADMINKITERRSTART+440)
#define KLAVTERRSTART       (KLCSADMINKITERRSTART+460)
#define KLPOLERRSTART       (KLCSADMINKITERRSTART+480)
#define KLLICERRSTART       (KLCSADMINKITERRSTART+500)
#define KLRPTERRSTART       (KLCSADMINKITERRSTART+520)
#define KLNAGINSTERRSTART   (KLCSADMINKITERRSTART+540)
#define KLSRVERRSTART       (KLCSADMINKITERRSTART+560)
#define KLPRSSSRVSTART      (KLCSADMINKITERRSTART+580)
#define KLFTSTART			(KLCSADMINKITERRSTART+680)
#define KLSRVHSTART			(KLCSADMINKITERRSTART+780)
#define KLMAILSTART			(KLCSADMINKITERRSTART+880)
#define KLWINFSTART			(KLCSADMINKITERRSTART+900)
#define KLDBSTART			(KLCSADMINKITERRSTART+950)
#define KLSPLSTART			(KLCSADMINKITERRSTART+1000)
#define KLNETSTART			(KLCSADMINKITERRSTART+1050)
#define KLNLSTSTART			(KLCSADMINKITERRSTART+1100)
#define KLNAGNLSTSTART		(KLCSADMINKITERRSTART+1150)
#define KLFTSSTART			(KLCSADMINKITERRSTART+1200)
#define KLSTDCONFSTART		(KLCSADMINKITERRSTART+1300)
#define KLOLASTART		    (KLCSADMINKITERRSTART+1350)



#endif // KL_ERRINTERVALS_H
