#define TDIPF_BUILDNUM 2
#define TDIPF_NAME	L"TDIPF"
#define AVPGNAME	L"AVPG"

#define TDIPF_FILE_DEVICE_SECTION  0x00008005

#define TDIPF_IOCTL_INDEX  0x739
//
// Define our own private IOCTL
//

#define TDIPF_GET_VERSION			CTL_CODE(TDIPF_FILE_DEVICE_SECTION ,				 \
							TDIPF_IOCTL_INDEX,    \
							METHOD_BUFFERED,\
							FILE_ANY_ACCESS)

#define TDIPF_HOOK_IP_IOCTL		CTL_CODE(TDIPF_FILE_DEVICE_SECTION ,				 \
							TDIPF_IOCTL_INDEX+1,    \
							METHOD_BUFFERED,\
							FILE_ANY_ACCESS)

#define TDIPF_HOOK_TCP_IOCTL		CTL_CODE(TDIPF_FILE_DEVICE_SECTION ,				 \
							TDIPF_IOCTL_INDEX+2,    \
							METHOD_BUFFERED,\
							FILE_ANY_ACCESS)

#define TDIPF_HOOK_UDP_IOCTL		CTL_CODE(TDIPF_FILE_DEVICE_SECTION ,				 \
							TDIPF_IOCTL_INDEX+3,    \
							METHOD_BUFFERED,\
							FILE_ANY_ACCESS)

#define TDIPF_UNHOOK_ALL_IOCTL	CTL_CODE(TDIPF_FILE_DEVICE_SECTION ,				 \
							TDIPF_IOCTL_INDEX+4,    \
							METHOD_BUFFERED,\
							FILE_ANY_ACCESS)

#define TDIPF_FIND_AVPG_IOCTL		CTL_CODE(TDIPF_FILE_DEVICE_SECTION ,				 \
							TDIPF_IOCTL_INDEX+5,    \
							METHOD_BUFFERED,\
							FILE_ANY_ACCESS)

#define TDIPF_START_FILTER		CTL_CODE(TDIPF_FILE_DEVICE_SECTION ,				 \
								TDIPF_IOCTL_INDEX+6,    \
								METHOD_BUFFERED,\
								FILE_ANY_ACCESS)

#define TDIPF_STOP_FILTER		CTL_CODE(TDIPF_FILE_DEVICE_SECTION ,				 \
								TDIPF_IOCTL_INDEX+7,    \
								METHOD_BUFFERED,\
								FILE_ANY_ACCESS)
#pragma pack(1)
typedef struct _CONN_ELEMENT	{
	CHAR	ProcessName[PROCNAMELEN];
	UCHAR	Protocol;
	ULONG	LocalIP;
	USHORT	LocalPORT;
	ULONG	RemoteIP;
	USHORT	RemotePORT;
	ULONG	State;
} CONN_ELEMENT, *PCONN_ELEMENT;
#pragma pack()

#define TDIPF_GET_OBJECTS	CTL_CODE(TDIPF_FILE_DEVICE_SECTION ,				 \
								TDIPF_IOCTL_INDEX+8,    \
								METHOD_BUFFERED,\
								FILE_ANY_ACCESS)

#define TDIPF_GET_CONN_OBJECTS	CTL_CODE(TDIPF_FILE_DEVICE_SECTION ,				 \
								TDIPF_IOCTL_INDEX+9,    \
								METHOD_BUFFERED,\
								FILE_ANY_ACCESS)


#pragma pack(1)
typedef struct _MAKE_DISCONNECT_STRUCT	{
	USHORT	LocalPort;
	ULONG	RemoteIp;
	USHORT	RemotePort;	
} MAKE_DISCONNECT_STRUCT, *PMAKE_DISCONNECT_STRUCT;
#pragma pack()
#define TDIPF_MAKE_DISCONNECT	CTL_CODE(TDIPF_FILE_DEVICE_SECTION ,				 \
								TDIPF_IOCTL_INDEX+10,    \
								METHOD_BUFFERED,\
								FILE_ANY_ACCESS)


#ifndef IOCTL_DEBUG__
#define IOCTL_DEBUG__
// DWORD in
#define IOCTL_SET_DEBUG_LEVEL		CTL_CODE(TDIPF_FILE_DEVICE_SECTION ,				 \
									TDIPF_IOCTL_INDEX+100,    \
									METHOD_BUFFERED,\
									FILE_ANY_ACCESS)
// DWORD out
#define IOCTL_GET_DEBUG_LEVEL		CTL_CODE(TDIPF_FILE_DEVICE_SECTION ,				 \
									TDIPF_IOCTL_INDEX+101,    \
									METHOD_BUFFERED,\
									FILE_ANY_ACCESS)

// DWORD in
#define IOCTL_SET_DEBUG_MASK		CTL_CODE(TDIPF_FILE_DEVICE_SECTION ,				 \
									TDIPF_IOCTL_INDEX+102,    \
									METHOD_BUFFERED,\
									FILE_ANY_ACCESS)

// DWORD out
#define IOCTL_GET_DEBUG_MASK		CTL_CODE(TDIPF_FILE_DEVICE_SECTION ,				 \
									TDIPF_IOCTL_INDEX+103,    \
									METHOD_BUFFERED,\
									FILE_ANY_ACCESS)
#endif


