ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=stored

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/CommonFiles

METAFILE=stored_trans.$(META)

SOURCESLIST=Sources.List

VCPROJ=stored.vcproj

include $(ROOT)/Makefiles/Make.Plugin
