ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=lha

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/CommonFiles

METAFILE=lha.$(META)

SOURCESLIST=Sources.List

VCPROJ=lha.vcproj

include $(ROOT)/Makefiles/Make.Plugin
