ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=propertiesmap_test

INCLUDES= \
	$(ROOT)/include/Prague \
	$(ROOT)/include \
	$(ROOT)/CommonFiles

SOURCESLIST=Sources.List

VCPROJ=propertiesmap_test.vcproj

STDLIBS=$(DSOLIB)

include $(ROOT)/Makefiles/Make.Executable
