ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=arjpack

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/CommonFiles \

METAFILE=arjpack.$(META)

SOURCESLIST=Sources.List

VCPROJ=arjpack.vcproj

include $(ROOT)/Makefiles/Make.Plugin
