//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Avpm.rc
//
#define IDD_MAINDIAL                    1
#define IDR_MAINFRAME                   1
#define IDR_AVPICON                     2
#define IDC_SETGENERALBUTTONS           101
#define IDD_ABOUTBOX                    102
#define IDD_SETTDLG                     104
#define IDD_GENERAL                     104
#define IDR_MAINICODIS                  105
#define IDB_DAVID                       109
#define IDB_EYE                         110
#define IDD_OBJECTS                     112
#define IDD_ACTIONS                     113
#define IDD_OPTIONS                     114
#define IDD_DIALOG1                     115
#define IDD_STATISTICS                  115
#define IDD_ACTIONS1                    116
#define IDD_GENERAL1                    117
#define IDD_OBJECTS1                    118
#define IDD_SUPPORT_DIALOG              118
#define IDD_OPTIONS1                    119
#define IDD_STATISTICS1                 120
#define IDD_GENERAL2                    121
#define IDB_KL                          123
#define IDD_ALERT                       125
#define IDB_MEDIA1                      126
#define IDD_ABOUT                       126
#define IDB_MEDIA2                      127
#define IDD_SPLASH                      127
#define IDR_KEY                         130
#define IDC_HIDE                        1000
#define IDC_DISCHECK                    1001
#define IDC_SETTINGS                    1002
#define IDC_STATISTICS                  1003
#define IDC_S_OBJECTS                   1004
#define IDC_S_INFECTED                  1005
#define IDC_S_DISINFECTED               1006
#define IDC_S_DELETED                   1007
#define IDC_S_LASTFILE                  1008
#define IDC_OBJECTS                     1009
#define IDC_INFECTED                    1010
#define IDC_DISINFECTED                 1011
#define IDC_WARNINGS1                   1011
#define IDC_DELETED                     1012
#define IDC_SUSPICIONS                  1012
#define IDC_LASTFILE                    1013
#define IDC_WARNINGS                    1014
#define IDC_DISINFECTED2                1015
#define IDC_DELETED2                    1016
#define IDC_FILEMASK                    1020
#define IDC_PACKED                      1021
#define IDC_ANALYSER                    1022
#define IDC_ARCHIVES                    1022
#define IDC_S_VIRNAME                   1023
#define IDC_MAILBASES                   1023
#define IDC_VIRNAME                     1024
#define IDC_MAILPLAIN                   1024
#define IDC_S_SKIPPED                   1025
#define IDC_SKIPPED                     1026
#define IDC_S_LASTINFECTED              1027
#define IDC_LASTINFECTED                1028
#define IDC_DENY                        1029
#define IDC_CURE                        1030
#define IDC_DELETE                      1031
#define IDC_ACTIONS                     1033
#define IDC_S_ABOUT                     1043
#define IDC_S_ACTIVITY                  1044
#define IDC_ENABLE                      1045
#define IDC_G_ICON                      1046
#define IDC_S_LAST_OBJ                  1048
#define MI_ENABLE                       1049
#define MI_PROPERTIES                   1050
#define IDC_EXIT                        1050
#define IDC_UNLOAD                      1050
#define MI_ABOUT                        1051
#define IDB_S_WARNINGS                  1051
#define IDC_S_WARNINGS                  1051
#define MI_EXIT                         1052
#define IDB_S_SUSPICIONS                1052
#define IDC_S_SUSPICIONS                1052
#define IDC_USERMASK                    1054
#define IDC_REPORT                      1065
#define IDC_REPORTFILE                  1066
#define IDC_APPEND                      1067
#define IDC_LIMIT                       1068
#define IDC_LIMITSIZE                   1069
#define IDC_UPDATE                      1072
#define IDC_SUPPORT                     1073
#define IDC_REPORT_FRAME                1096
#define IDC_S_NAME                      1097
#define IDC_S_REG                       1098
#define IDC_S_ORG                       1099
#define IDC_S_REGNUMBER                 1100
#define IDC_COPYINFO                    1101
#define IDC_NAME                        1103
#define IDC_ORG                         1104
#define IDC_REGNUMBER                   1105
#define IDC_SMARTMASK                   1106
#define IDC_PROGRAMS                    1107
#define IDC_ALLFILES                    1108
#define IDC_USERDEF                     1109
#define IDC_UPDATENOW                   1110
#define IDC_LIMITCOMPOUND               1111
#define IDC_SCAN                        1111
#define IDC_LIMITCOMPOUNDSIZE           1112
#define IDC_PAUSE                       1112
#define IDC_COMPOUNDFILES               1113
#define IDC_BUILD                       1114
#define IDC_VERSION                     1114
#define IDC_ALERT                       1115
#define IDC_ALERT_MESSAGE               1116
#define IDC_TRY_TO_DISINFECT            1117
#define IDC_LIST_KEYS                   1117
#define IDC_DAVID                       1118
#define MI_DISABLE                      1119
#define IDC_PROGRESS                    1123
#define IDC_EXCLUDE                     1124
#define IDC_EDIT_EXCLUDE                1125
#define IDC_COPYRIGHT                   1126
#define IDC_PRODUCTNAME                 1127
#define IDS_LIMITED_FLAG                32000
#define IDS_ENABLE                      32772
#define IDS_DISABLE                     32773
#define IDS_SETTINGS                    32774
#define IDS_CHECKED                     32775
#define IDS_INFECTED                    32776
#define IDS_DISINFECTED                 32777
#define IDS_DELETED                     32778
#define IDS_SKIPPED                     32779
#define IDS_LAST_CHOBJECT               32780
#define IDS_LAST_VIRUSN                 32781
#define IDS_LAST_INFOBJECT              32782
#define IDS_ACTIONS                     32783
#define IDS_PROMPT_USER                 32784
#define IDS_DISINF_AUTO                 32785
#define IDS_DELETE_AUTO                 32786
#define IDS_DENY                        32787
#define IDS_FILE_MASK                   32788
#define IDS_SMART                       32789
#define IDS_ALLFILES                    32790
#define IDS_PACKED                      32791
#define IDS_CA                          32792
#define IDS_SHURE_DELETEALL             32793
#define IDS_SHURE_EXIT                  32794
#define IDS_RESTORE                     32795
#define IDS_ABOUT                       32796
#define IDS_EXIT                        32797
#define IDS_ABOUT_BOX                   32798
#define IDS_FULL_NAME                   32799
#define IDS_SETTINGS_BOX                32800
#define IDS_AVPM_ERROR                  32801
#define IDS_DRV_FAILED                  32802
#define IDS_ERRLOADVXD                  32803
#define IDS_TIP_DISABLE                 32804
#define IDS_TIP_ENABLE                  32805
#define IDS_MINIMIZE                    32806
#define IDS_ALERT_TEXT                  32807
#define IDS_VERSION                     32808
#define IDS_ARCHIVES                    32809
#define IDS_WARNINGS                    32810
#define IDS_SUSPIC                      32811
#define IDS_CORRUPTED                   32812
#define IDS_REMOTE_LAUNCH               32813
#define IDS_KEY_PLATHFORM_NT            32814
#define IDS_KEY_PLATHFORM_95            32815
#define IDS_KEY_ABSENT                  32816
#define IDS_LAST_UPDATE                 32817
#define IDS_FINDNEXT                    32818
#define IDS_FIND                        32819
#define IDS_CANCEL                      32820
#define IDS_NAME                        32821
#define IDS_ORGANIZATION                32822
#define IDS_REGNUMBER                   32823
#define IDS_REGISTERINFO                32824
#define IDS_SUPPORT_DLG                 32825
#define IDS_EXPIR_ALARM                 32826
#define IDS_EXPIRIED                    32827
#define IDS_SET_OUTOFDATE               32828
#define IDS_UNLOAD                      32829
#define IDS_LIMIT                       32830
#define IDS_COPYINFO                    32831
#define IDS_REPORT                      32832
#define IDS_SUSPICIONS                  32833
#define IDS_GENERAL                     32834
#define IDS_OBJECTS                     32835
#define IDS_ACTIONS1                    32836
#define IDS_OPTIONS                     32837
#define IDS_STATISTICS                  32838
#define IDS_ALERT_SUSP                  32839
#define IDS_ALERT_WARNING               32840
#define IDS_WARNING                     32841
#define IDS_PROGRAMS                    32842
#define IDS_USERDEF                     32843
#define IDS_DRV_FAIL_TRY_MORE           32844
#define IDS_UPDATENOW                   32845
#define IDS_MAILBASES                   32846
#define IDS_MAILPLAIN                   32847
#define IDS_ARCHIVE                     32848
#define IDS_LIMITCOMPOUND               32849
#define IDS_COMPOUNDFILES               32850
#define IDS_MEMORY                      32851
#define IDS_MBR                         32852
#define IDS_BOOTSECTOR                  32853
#define IDS_SELF_DISINFECTED            32854
#define IDS_SELF_DISINFECTION_FAILED    32855
#define IDS_ALERT_MB_CAPTION            32856
#define IDS_TRY_TO_DISINFECT            32857
#define IDS_ALERT                       32858
#define IDS_ALERT_MB_INTRO              32859
#define IDS_ALERT_MB_2_DETECTED         32860
#define IDS_ALERT_MB_2_DISINFECTED      32861
#define IDS_ALERT_MB_2_DELETED          32862
#define IDS_ALERT_MB_3_DETECTED         32863
#define IDS_ALERT_MB_3_DISINFECTED      32864
#define IDS_ALERT_MB_3_DELETED          32865
#define IDS_ALERT_MB_3_FAILED           32866
#define IDS_ALERT_MB_2_FAILED           32867
#define IDS_ALERT_MB_4_VIRUS            32868
#define IDS_ALERT_MB_1_VIRUS            32869
#define IDS_ALERT_MB_1_SUSPICION        32870
#define IDS_ALERT_MB_1_WARNING          32871
#define IDS_ALERT_MB_4_DANGER           32872
#define IDS_REP_DETECTED                32873
#define IDS_REP_DISINFECTED             32874
#define IDS_REP_DISINFECT_FAILED        32875
#define IDS_REP_DELETED                 32876
#define IDS_REP_DELETE_FAILED           32877
#define IDS_REP_WARNING                 32878
#define IDS_REP_SUSPICION               32879
#define IDS_REP_IO_ERROR                32880
#define IDS_ALERT_MB_3_IO_ERROR         32881
#define IDS_REP_TRUNCATED               32882
#define IDS_REP_LOADED                  32883
#define IDS_REP_UNLOADED                32884
#define IDS_REP_ENABLED                 32885
#define IDS_REP_DISABLED                32886
#define IDS_ERROR_OPEN_FILE             32887
#define IDS_AUTH_FAILED                 32888
#define IDS_AUTH_CONTINUE               32889
#define IDS_SCAN_START                  32890
#define IDS_SCAN_STOP                   32891
#define IDS_SCAN_PAUSE                  32892
#define IDS_SCAN_CONTINUE               32893
#define IDS_SCAN_PAUSED                 32894
#define IDS_SCANNING                    32895
#define IDS_EXCLUDE                     32896
#define IDS_LIST_KEYS_NUMBER            32897
#define IDS_LIST_KEYS_DESCRIPTION       32898
#define IDS_LIST_KEYS_FILE              32899
#define IDS_LIST_KEYS_EXPIRATION        32900
#define IDS_LIST_KEYS_PLNAME            32901
#define IDS_STRING32902                 32902
#define IDS_KEY_PLATHFORM_NT_SERVER     32902
#define IDS_UPDATE_EXPIRED              32903
#define IDS_STARTED                     32904
#define IDS_VERSION_NEW                 32905
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1128
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
