ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=ntreelink

INCLUDES= \
	$(ROOT)/include \
	..

LIBRARIES= \
	ntreelib \
	klavcorelib

DEPS= \
	../ \
	../../klavcorelib

VCPROJ=ntreelink.vcproj

SOURCESLIST=Sources.List

include $(ROOT)/Makefiles/Make.Library
