#include <std/base/klstd.h>
#include <std/init/init_std.h>
#include <std/klcspwd/klcspwdr.h>

DECLARE_MODULE_INIT_DEINIT(KLSTD)
DECLARE_MODULE_INIT_DEINIT(KLPAR)
DECLARE_MODULE_INIT_DEINIT(KLTP)
DECLARE_MODULE_INIT_DEINIT(KLTMSG)

IMPLEMENT_MODULE_INIT_DEINIT(KLCSSTD)

IMPLEMENT_MODULE_INIT_BEGIN(KLCSSTD)
        KLCSPWD::initialize(false);
		CALL_MODULE_INIT(KLSTD);
		CALL_MODULE_INIT(KLPAR);
		CALL_MODULE_INIT(KLTP);
        CALL_MODULE_INIT(KLTMSG);
IMPLEMENT_MODULE_INIT_END()

IMPLEMENT_MODULE_DEINIT_BEGIN(KLCSSTD)
		CALL_MODULE_DEINIT(KLTMSG);
        CALL_MODULE_DEINIT(KLTP);
        CALL_MODULE_DEINIT(KLPAR);
		CALL_MODULE_DEINIT(KLSTD);
        KLCSPWD::deinitialize();
IMPLEMENT_MODULE_DEINIT_END()

