ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=propertiesmap

INCLUDES= \
	$(ROOT)/include/Prague \
	$(ROOT)/include \
	$(ROOT)/CommonFiles \
	$(ROOT)/Prague/Core/String

DEPS= \
	$(ROOT)/klava/kernel/klavprlib

SOURCESLIST=Sources.List

VCPROJ=propertiesmap.vcproj

include $(ROOT)/Makefiles/Make.Plugin
