# -*- Makefile -*- Time-stamp: <03/07/11 13:08:45 ptr>
# $Id: Makefile.inc,v 1.20 2004/04/08 09:20:26 ptr Exp $

LIBNAME = conn_prod
MAJOR = 0
MINOR = 1
PATCH = 0
SRC_CC = ../../../testproducts/conn_prod/appguicalls.cpp \
         ../../../testproducts/conn_prod/appsynchronizer.cpp \
         ../../../testproducts/conn_prod/connectorimp.cpp \
         ../../../testproducts/conn_prod/main.cpp \
         ../../../testproducts/conn_prod/policysyncimp.cpp \
         ../../../testproducts/conn_prod/settingssyncimp.cpp \
         ../../../testproducts/conn_prod/tasksettingssynchronizerimp.cpp \
         ../../../testproducts/conn_prod/taskssynchronizerimp.cpp 
