ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=format_test

INCLUDES= \
	$(ROOT)/include

LIBRARIES= \
	klavcorelib

DEPS= \
	../../klavcorelib

VCPROJ=format_test.vcproj

SOURCESLIST=Sources.List

include $(ROOT)/Makefiles/Make.Executable

