ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=vmarea

INCLUDES= \
	$(ROOT)/include/Prague \
	$(ROOT)/include \
	$(ROOT)/CommonFiles

LIBRARIES= \
	klsys

DEPS= \
	$(ROOT)/CommonFiles/klsys

VCPROJ=vmarea.vcproj

SOURCESLIST=Sources.List

include $(ROOT)/Makefiles/Make.Plugin
