ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=inflate

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/CommonFiles \

METAFILE=inflate_trans.$(META)

SOURCESLIST=Sources.List

VCPROJ=Inflate.vcproj

include $(ROOT)/Makefiles/Make.Plugin
