ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=hccompare

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/AV \
	$(ROOT)/include/Extract \
	$(ROOT)/include/ProductCore \
	$(ROOT)/CommonFiles

METAFILE=compare.$(META)

SOURCESLIST=Sources.List

VCPROJ=hccompare.vcproj

include $(ROOT)/Makefiles/Make.Plugin
