ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=seqio

INCLUDES= \
	$(ROOT)/include/Prague \
	$(ROOT)/include \
	$(ROOT)/CommonFiles

METAFILE=SeqIO.$(META)

SOURCESLIST=Sources.List

VCPROJ=seqio.vcproj

include $(ROOT)/Makefiles/Make.Plugin
