ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=rar

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/CommonFiles \
	$(ROOT)/Prague

METAFILE=rar.$(META)

SOURCESLIST=Sources.List

VCPROJ=rar.vcproj

include $(ROOT)/Makefiles/Make.Plugin
