/* soapH.h
   Generated by gSOAP 2.7.0d from soapheader.h
   Copyright (C) 2001-2004 Genivia, Inc. All Rights Reserved.
   This software is released under one of the following three licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
   See README.txt for further details.
*/
#ifndef soapH_H
#define soapH_H
#include "soapStub.h"

SOAP_BEGIN_NAMESPACE(soap)
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_resolve_attachments(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);

SOAP_FMAC3 void SOAP_FMAC4 soap_fdelete(struct soap_clist*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_byte(struct soap*, char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_int(struct soap*, int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__int(struct soap*, long *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__int(struct soap*, long const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__int(struct soap*, const long *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__int(struct soap*, const char*, int, const long *, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_get_xsd__int(struct soap*, long *, const char*, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_in_xsd__int(struct soap*, const char*, long *, const char*);

#ifndef SOAP_TYPE_long
#define SOAP_TYPE_long (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_long(struct soap*, long *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_long(struct soap*, long const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_long(struct soap*, const long *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_long(struct soap*, const char*, int, const long *, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_get_long(struct soap*, long *, const char*, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_in_long(struct soap*, const char*, long *, const char*);

#ifndef SOAP_TYPE_xsd__long
#define SOAP_TYPE_xsd__long (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__long(struct soap*, LONG64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__long(struct soap*, LONG64 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__long(struct soap*, const LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__long(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_xsd__long(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_xsd__long(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_LONG64(struct soap*, LONG64 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_xsd__unsignedByte
#define SOAP_TYPE_xsd__unsignedByte (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__unsignedByte(struct soap*, unsigned char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__unsignedByte(struct soap*, const unsigned char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_xsd__unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_xsd__unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_unsignedByte(struct soap*, unsigned char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_unsignedInt(struct soap*, unsigned int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE_xsd__unsignedLong
#define SOAP_TYPE_xsd__unsignedLong (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__unsignedLong(struct soap*, ULONG64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__unsignedLong(struct soap*, ULONG64 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__unsignedLong(struct soap*, const ULONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__unsignedLong(struct soap*, const char*, int, const ULONG64 *, const char*);
SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_get_xsd__unsignedLong(struct soap*, ULONG64 *, const char*, const char*);
SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_in_xsd__unsignedLong(struct soap*, const char*, ULONG64 *, const char*);

#ifndef SOAP_TYPE_unsignedLONG64
#define SOAP_TYPE_unsignedLONG64 (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedLONG64(struct soap*, ULONG64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_unsignedLONG64(struct soap*, ULONG64 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedLONG64(struct soap*, const ULONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedLONG64(struct soap*, const char*, int, const ULONG64 *, const char*);
SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_get_unsignedLONG64(struct soap*, ULONG64 *, const char*, const char*);
SOAP_FMAC3 ULONG64 * SOAP_FMAC4 soap_in_unsignedLONG64(struct soap*, const char*, ULONG64 *, const char*);

#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__boolean(struct soap*, bool *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__boolean(struct soap*, bool const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap_xsd__boolean2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2xsd__boolean(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_bool(struct soap*, bool const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2bool(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_xsd__long_
#define SOAP_TYPE_xsd__long_ (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__long_(struct soap*, const char*, int, const xsd__long_ *, const char*);
SOAP_FMAC3 xsd__long_ * SOAP_FMAC4 soap_get_xsd__long_(struct soap*, xsd__long_ *, const char*, const char*);
SOAP_FMAC3 xsd__long_ * SOAP_FMAC4 soap_in_xsd__long_(struct soap*, const char*, xsd__long_ *, const char*);

SOAP_FMAC5 xsd__long_ * SOAP_FMAC6 soap_new_xsd__long_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__long_(struct soap*, xsd__long_*);
SOAP_FMAC5 xsd__long_ * SOAP_FMAC6 soap_instantiate_xsd__long_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__long_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__integer_
#define SOAP_TYPE_xsd__integer_ (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__integer_(struct soap*, const char*, int, const xsd__integer_ *, const char*);
SOAP_FMAC3 xsd__integer_ * SOAP_FMAC4 soap_get_xsd__integer_(struct soap*, xsd__integer_ *, const char*, const char*);
SOAP_FMAC3 xsd__integer_ * SOAP_FMAC4 soap_in_xsd__integer_(struct soap*, const char*, xsd__integer_ *, const char*);

SOAP_FMAC5 xsd__integer_ * SOAP_FMAC6 soap_new_xsd__integer_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__integer_(struct soap*, xsd__integer_*);
SOAP_FMAC5 xsd__integer_ * SOAP_FMAC6 soap_instantiate_xsd__integer_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__integer_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__decimal_
#define SOAP_TYPE_xsd__decimal_ (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__decimal_(struct soap*, const char*, int, const xsd__decimal_ *, const char*);
SOAP_FMAC3 xsd__decimal_ * SOAP_FMAC4 soap_get_xsd__decimal_(struct soap*, xsd__decimal_ *, const char*, const char*);
SOAP_FMAC3 xsd__decimal_ * SOAP_FMAC4 soap_in_xsd__decimal_(struct soap*, const char*, xsd__decimal_ *, const char*);

SOAP_FMAC5 xsd__decimal_ * SOAP_FMAC6 soap_new_xsd__decimal_(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__decimal_(struct soap*, xsd__decimal_*);
SOAP_FMAC5 xsd__decimal_ * SOAP_FMAC6 soap_instantiate_xsd__decimal_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__decimal_(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__anySimpleType
#define SOAP_TYPE_xsd__anySimpleType (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anySimpleType(struct soap*, const char*, int, const xsd__anySimpleType *, const char*);
SOAP_FMAC3 xsd__anySimpleType * SOAP_FMAC4 soap_get_xsd__anySimpleType(struct soap*, xsd__anySimpleType *, const char*, const char*);
SOAP_FMAC3 xsd__anySimpleType * SOAP_FMAC4 soap_in_xsd__anySimpleType(struct soap*, const char*, xsd__anySimpleType *, const char*);

SOAP_FMAC5 xsd__anySimpleType * SOAP_FMAC6 soap_new_xsd__anySimpleType(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__anySimpleType(struct soap*, xsd__anySimpleType*);
SOAP_FMAC5 xsd__anySimpleType * SOAP_FMAC6 soap_instantiate_xsd__anySimpleType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__anySimpleType(struct soap*, int, int, void*, const void*, size_t);

#ifndef SOAP_TYPE_xsd__anyType
#define SOAP_TYPE_xsd__anyType (6)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyType(struct soap*, const char*, int, const xsd__anyType *, const char*);
SOAP_FMAC3 xsd__anyType * SOAP_FMAC4 soap_get_xsd__anyType(struct soap*, xsd__anyType *, const char*, const char*);
SOAP_FMAC3 xsd__anyType * SOAP_FMAC4 soap_in_xsd__anyType(struct soap*, const char*, xsd__anyType *, const char*);

SOAP_FMAC5 xsd__anyType * SOAP_FMAC6 soap_new_xsd__anyType(struct soap*, int);

SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__anyType(struct soap*, xsd__anyType*);
SOAP_FMAC5 xsd__anyType * SOAP_FMAC6 soap_instantiate_xsd__anyType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC5 void SOAP_FMAC6 soap_copy_xsd__anyType(struct soap*, int, int, void*, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef SOAP_TYPE_klftbridge_ReleaseReceiver
#define SOAP_TYPE_klftbridge_ReleaseReceiver (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_klftbridge_ReleaseReceiver(struct soap*, struct klftbridge_ReleaseReceiver const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_klftbridge_ReleaseReceiver(struct soap*, const struct klftbridge_ReleaseReceiver *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_klftbridge_ReleaseReceiver(struct soap*, struct klftbridge_ReleaseReceiver *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_klftbridge_ReleaseReceiver(struct soap*, const struct klftbridge_ReleaseReceiver *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_klftbridge_ReleaseReceiver(struct soap*, const char*, int, const struct klftbridge_ReleaseReceiver *, const char*);
SOAP_FMAC3 struct klftbridge_ReleaseReceiver * SOAP_FMAC4 soap_get_klftbridge_ReleaseReceiver(struct soap*, struct klftbridge_ReleaseReceiver *, const char*, const char*);
SOAP_FMAC3 struct klftbridge_ReleaseReceiver * SOAP_FMAC4 soap_in_klftbridge_ReleaseReceiver(struct soap*, const char*, struct klftbridge_ReleaseReceiver *, const char*);

#ifndef SOAP_TYPE_klftbridge_ReleaseReceiverResponse
#define SOAP_TYPE_klftbridge_ReleaseReceiverResponse (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_klftbridge_ReleaseReceiverResponse(struct soap*, struct klftbridge_ReleaseReceiverResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_klftbridge_ReleaseReceiverResponse(struct soap*, const struct klftbridge_ReleaseReceiverResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_klftbridge_ReleaseReceiverResponse(struct soap*, struct klftbridge_ReleaseReceiverResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_klftbridge_ReleaseReceiverResponse(struct soap*, const struct klftbridge_ReleaseReceiverResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_klftbridge_ReleaseReceiverResponse(struct soap*, const char*, int, const struct klftbridge_ReleaseReceiverResponse *, const char*);
SOAP_FMAC3 struct klftbridge_ReleaseReceiverResponse * SOAP_FMAC4 soap_get_klftbridge_ReleaseReceiverResponse(struct soap*, struct klftbridge_ReleaseReceiverResponse *, const char*, const char*);
SOAP_FMAC3 struct klftbridge_ReleaseReceiverResponse * SOAP_FMAC4 soap_in_klftbridge_ReleaseReceiverResponse(struct soap*, const char*, struct klftbridge_ReleaseReceiverResponse *, const char*);

#ifndef SOAP_TYPE_klftbridge_GetNextFileChunk
#define SOAP_TYPE_klftbridge_GetNextFileChunk (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_klftbridge_GetNextFileChunk(struct soap*, struct klftbridge_GetNextFileChunk const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_klftbridge_GetNextFileChunk(struct soap*, const struct klftbridge_GetNextFileChunk *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_klftbridge_GetNextFileChunk(struct soap*, struct klftbridge_GetNextFileChunk *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_klftbridge_GetNextFileChunk(struct soap*, const struct klftbridge_GetNextFileChunk *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_klftbridge_GetNextFileChunk(struct soap*, const char*, int, const struct klftbridge_GetNextFileChunk *, const char*);
SOAP_FMAC3 struct klftbridge_GetNextFileChunk * SOAP_FMAC4 soap_get_klftbridge_GetNextFileChunk(struct soap*, struct klftbridge_GetNextFileChunk *, const char*, const char*);
SOAP_FMAC3 struct klftbridge_GetNextFileChunk * SOAP_FMAC4 soap_in_klftbridge_GetNextFileChunk(struct soap*, const char*, struct klftbridge_GetNextFileChunk *, const char*);

#ifndef SOAP_TYPE_klftbridge_GetNextFileChunkResponse
#define SOAP_TYPE_klftbridge_GetNextFileChunkResponse (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_klftbridge_GetNextFileChunkResponse(struct soap*, struct klftbridge_GetNextFileChunkResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_klftbridge_GetNextFileChunkResponse(struct soap*, const struct klftbridge_GetNextFileChunkResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_klftbridge_GetNextFileChunkResponse(struct soap*, struct klftbridge_GetNextFileChunkResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_klftbridge_GetNextFileChunkResponse(struct soap*, const struct klftbridge_GetNextFileChunkResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_klftbridge_GetNextFileChunkResponse(struct soap*, const char*, int, const struct klftbridge_GetNextFileChunkResponse *, const char*);
SOAP_FMAC3 struct klftbridge_GetNextFileChunkResponse * SOAP_FMAC4 soap_get_klftbridge_GetNextFileChunkResponse(struct soap*, struct klftbridge_GetNextFileChunkResponse *, const char*, const char*);
SOAP_FMAC3 struct klftbridge_GetNextFileChunkResponse * SOAP_FMAC4 soap_in_klftbridge_GetNextFileChunkResponse(struct soap*, const char*, struct klftbridge_GetNextFileChunkResponse *, const char*);

#ifndef SOAP_TYPE_klftbridge_GetFileInfo
#define SOAP_TYPE_klftbridge_GetFileInfo (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_klftbridge_GetFileInfo(struct soap*, struct klftbridge_GetFileInfo const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_klftbridge_GetFileInfo(struct soap*, const struct klftbridge_GetFileInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_klftbridge_GetFileInfo(struct soap*, struct klftbridge_GetFileInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_klftbridge_GetFileInfo(struct soap*, const struct klftbridge_GetFileInfo *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_klftbridge_GetFileInfo(struct soap*, const char*, int, const struct klftbridge_GetFileInfo *, const char*);
SOAP_FMAC3 struct klftbridge_GetFileInfo * SOAP_FMAC4 soap_get_klftbridge_GetFileInfo(struct soap*, struct klftbridge_GetFileInfo *, const char*, const char*);
SOAP_FMAC3 struct klftbridge_GetFileInfo * SOAP_FMAC4 soap_in_klftbridge_GetFileInfo(struct soap*, const char*, struct klftbridge_GetFileInfo *, const char*);

#ifndef SOAP_TYPE_klftbridge_GetFileInfoResponse
#define SOAP_TYPE_klftbridge_GetFileInfoResponse (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_klftbridge_GetFileInfoResponse(struct soap*, struct klftbridge_GetFileInfoResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_klftbridge_GetFileInfoResponse(struct soap*, const struct klftbridge_GetFileInfoResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_klftbridge_GetFileInfoResponse(struct soap*, struct klftbridge_GetFileInfoResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_klftbridge_GetFileInfoResponse(struct soap*, const struct klftbridge_GetFileInfoResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_klftbridge_GetFileInfoResponse(struct soap*, const char*, int, const struct klftbridge_GetFileInfoResponse *, const char*);
SOAP_FMAC3 struct klftbridge_GetFileInfoResponse * SOAP_FMAC4 soap_get_klftbridge_GetFileInfoResponse(struct soap*, struct klftbridge_GetFileInfoResponse *, const char*, const char*);
SOAP_FMAC3 struct klftbridge_GetFileInfoResponse * SOAP_FMAC4 soap_in_klftbridge_GetFileInfoResponse(struct soap*, const char*, struct klftbridge_GetFileInfoResponse *, const char*);

#ifndef SOAP_TYPE_klftbridge_Connect
#define SOAP_TYPE_klftbridge_Connect (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_klftbridge_Connect(struct soap*, struct klftbridge_Connect const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_klftbridge_Connect(struct soap*, const struct klftbridge_Connect *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_klftbridge_Connect(struct soap*, struct klftbridge_Connect *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_klftbridge_Connect(struct soap*, const struct klftbridge_Connect *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_klftbridge_Connect(struct soap*, const char*, int, const struct klftbridge_Connect *, const char*);
SOAP_FMAC3 struct klftbridge_Connect * SOAP_FMAC4 soap_get_klftbridge_Connect(struct soap*, struct klftbridge_Connect *, const char*, const char*);
SOAP_FMAC3 struct klftbridge_Connect * SOAP_FMAC4 soap_in_klftbridge_Connect(struct soap*, const char*, struct klftbridge_Connect *, const char*);

#ifndef SOAP_TYPE_klftbridge_ConnectResponse
#define SOAP_TYPE_klftbridge_ConnectResponse (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_klftbridge_ConnectResponse(struct soap*, struct klftbridge_ConnectResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_klftbridge_ConnectResponse(struct soap*, const struct klftbridge_ConnectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_klftbridge_ConnectResponse(struct soap*, struct klftbridge_ConnectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_klftbridge_ConnectResponse(struct soap*, const struct klftbridge_ConnectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_klftbridge_ConnectResponse(struct soap*, const char*, int, const struct klftbridge_ConnectResponse *, const char*);
SOAP_FMAC3 struct klftbridge_ConnectResponse * SOAP_FMAC4 soap_get_klftbridge_ConnectResponse(struct soap*, struct klftbridge_ConnectResponse *, const char*, const char*);
SOAP_FMAC3 struct klftbridge_ConnectResponse * SOAP_FMAC4 soap_in_klftbridge_ConnectResponse(struct soap*, const char*, struct klftbridge_ConnectResponse *, const char*);

#ifndef SOAP_TYPE_klftbridge_CreateReceiver
#define SOAP_TYPE_klftbridge_CreateReceiver (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_klftbridge_CreateReceiver(struct soap*, struct klftbridge_CreateReceiver const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_klftbridge_CreateReceiver(struct soap*, const struct klftbridge_CreateReceiver *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_klftbridge_CreateReceiver(struct soap*, struct klftbridge_CreateReceiver *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_klftbridge_CreateReceiver(struct soap*, const struct klftbridge_CreateReceiver *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_klftbridge_CreateReceiver(struct soap*, const char*, int, const struct klftbridge_CreateReceiver *, const char*);
SOAP_FMAC3 struct klftbridge_CreateReceiver * SOAP_FMAC4 soap_get_klftbridge_CreateReceiver(struct soap*, struct klftbridge_CreateReceiver *, const char*, const char*);
SOAP_FMAC3 struct klftbridge_CreateReceiver * SOAP_FMAC4 soap_in_klftbridge_CreateReceiver(struct soap*, const char*, struct klftbridge_CreateReceiver *, const char*);

#ifndef SOAP_TYPE_klftbridge_CreateReceiverResponse
#define SOAP_TYPE_klftbridge_CreateReceiverResponse (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_klftbridge_CreateReceiverResponse(struct soap*, struct klftbridge_CreateReceiverResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_klftbridge_CreateReceiverResponse(struct soap*, const struct klftbridge_CreateReceiverResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_klftbridge_CreateReceiverResponse(struct soap*, struct klftbridge_CreateReceiverResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_klftbridge_CreateReceiverResponse(struct soap*, const struct klftbridge_CreateReceiverResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_klftbridge_CreateReceiverResponse(struct soap*, const char*, int, const struct klftbridge_CreateReceiverResponse *, const char*);
SOAP_FMAC3 struct klftbridge_CreateReceiverResponse * SOAP_FMAC4 soap_get_klftbridge_CreateReceiverResponse(struct soap*, struct klftbridge_CreateReceiverResponse *, const char*, const char*);
SOAP_FMAC3 struct klftbridge_CreateReceiverResponse * SOAP_FMAC4 soap_in_klftbridge_CreateReceiverResponse(struct soap*, const char*, struct klftbridge_CreateReceiverResponse *, const char*);

#ifndef SOAP_TYPE_klft_file_info_t
#define SOAP_TYPE_klft_file_info_t (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_klft_file_info_t(struct soap*, struct klft_file_info_t const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_klft_file_info_t(struct soap*, const struct klft_file_info_t *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_klft_file_info_t(struct soap*, struct klft_file_info_t *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_klft_file_info_t(struct soap*, const struct klft_file_info_t *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_klft_file_info_t(struct soap*, const char*, int, const struct klft_file_info_t *, const char*);
SOAP_FMAC3 struct klft_file_info_t * SOAP_FMAC4 soap_get_klft_file_info_t(struct soap*, struct klft_file_info_t *, const char*, const char*);
SOAP_FMAC3 struct klft_file_info_t * SOAP_FMAC4 soap_in_klft_file_info_t(struct soap*, const char*, struct klft_file_info_t *, const char*);

#ifndef SOAP_TYPE_klft_file_chunk_t
#define SOAP_TYPE_klft_file_chunk_t (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_klft_file_chunk_t(struct soap*, struct klft_file_chunk_t const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_klft_file_chunk_t(struct soap*, const struct klft_file_chunk_t *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_klft_file_chunk_t(struct soap*, struct klft_file_chunk_t *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_klft_file_chunk_t(struct soap*, const struct klft_file_chunk_t *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_klft_file_chunk_t(struct soap*, const char*, int, const struct klft_file_chunk_t *, const char*);
SOAP_FMAC3 struct klft_file_chunk_t * SOAP_FMAC4 soap_get_klft_file_chunk_t(struct soap*, struct klft_file_chunk_t *, const char*, const char*);
SOAP_FMAC3 struct klft_file_chunk_t * SOAP_FMAC4 soap_in_klft_file_chunk_t(struct soap*, const char*, struct klft_file_chunk_t *, const char*);

#ifndef SOAP_TYPE_xsd__klft_file_chunk_buff
#define SOAP_TYPE_xsd__klft_file_chunk_buff (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__klft_file_chunk_buff(struct soap*, struct xsd__klft_file_chunk_buff const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__klft_file_chunk_buff(struct soap*, struct xsd__klft_file_chunk_buff const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__klft_file_chunk_buff(struct soap*, struct xsd__klft_file_chunk_buff *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__klft_file_chunk_buff(struct soap*, const struct xsd__klft_file_chunk_buff *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__klft_file_chunk_buff(struct soap*, const char*, int, const struct xsd__klft_file_chunk_buff *, const char*);
SOAP_FMAC3 struct xsd__klft_file_chunk_buff * SOAP_FMAC4 soap_get_xsd__klft_file_chunk_buff(struct soap*, struct xsd__klft_file_chunk_buff *, const char*, const char*);
SOAP_FMAC3 struct xsd__klft_file_chunk_buff * SOAP_FMAC4 soap_in_xsd__klft_file_chunk_buff(struct soap*, const char*, struct xsd__klft_file_chunk_buff *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_message_desc
#define SOAP_TYPE_message_desc (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_message_desc(struct soap*, struct message_desc_t const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_message_desc(struct soap*, const struct message_desc_t *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_message_desc(struct soap*, struct message_desc_t *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_message_desc(struct soap*, const struct message_desc_t *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_message_desc(struct soap*, const char*, int, const struct message_desc_t *, const char*);
SOAP_FMAC3 struct message_desc_t * SOAP_FMAC4 soap_get_message_desc(struct soap*, struct message_desc_t *, const char*, const char*);
SOAP_FMAC1 struct message_desc_t * SOAP_FMAC2 soap_in_message_desc(struct soap*, const char*, struct message_desc_t *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef SOAP_TYPE_PointerToxsd__unsignedByte
#define SOAP_TYPE_PointerToxsd__unsignedByte (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__unsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToxsd__unsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__unsignedByte(struct soap*, unsigned char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__unsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerToxsd__unsignedByte(struct soap*, unsigned char **, const char*, const char*);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerToxsd__unsignedByte(struct soap*, const char*, unsigned char **, const char*);

#ifndef SOAP_TYPE_xsd__wstring
#define SOAP_TYPE_xsd__wstring (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__wstring(struct soap*, wchar_t *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__wstring(struct soap*, wchar_t *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__wstring(struct soap*, wchar_t *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__wstring(struct soap*, const char*, int, wchar_t*const*, const char*);
SOAP_FMAC3 wchar_t ** SOAP_FMAC4 soap_get_xsd__wstring(struct soap*, wchar_t **, const char*, const char*);
SOAP_FMAC3 wchar_t * * SOAP_FMAC4 soap_in_xsd__wstring(struct soap*, const char*, wchar_t **, const char*);

#ifndef SOAP_TYPE_wstring
#define SOAP_TYPE_wstring (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wstring(struct soap*, wchar_t *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_wstring(struct soap*, wchar_t *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_wstring(struct soap*, wchar_t *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wstring(struct soap*, const char*, int, wchar_t*const*, const char*);
SOAP_FMAC3 wchar_t ** SOAP_FMAC4 soap_get_wstring(struct soap*, wchar_t **, const char*, const char*);
SOAP_FMAC3 wchar_t * * SOAP_FMAC4 soap_in_wstring(struct soap*, const char*, wchar_t **, const char*);

#ifndef SOAP_TYPE_xsd__integer
#define SOAP_TYPE_xsd__integer (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__integer(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__integer(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__integer(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__integer(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__integer(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__integer(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__decimal
#define SOAP_TYPE_xsd__decimal (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__decimal(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__decimal(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__decimal(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__decimal(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__decimal(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__decimal(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

SOAP_END_NAMESPACE(soap)

#endif

/* end of soapH.h */
