/* soapServerLib.cpp
   Generated by gSOAP 2.7.0d from soapheader.h
   Copyright (C) 2001-2004 Genivia, Inc. All Rights Reserved.
   This software is released under one of the following three licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
   See README.txt for further details.
*/
#define WITH_NOGLOBAL
#define SOAP_FMAC3 static
#include "soapC.cpp"
#include "soapServer.cpp"

/* end of soapServerLib.cpp */
