#ifndef Operations_hpp
#define Operations_hpp

namespace idl { namespace parser {

struct Operations {
	enum Op {
	/* 0*/Add,
				And,
				As,
				BitAnd,
				BitInv,
				BitOr,
				BitXor,
				Block,
				Component,
				ComponentId,
	/*10*/ComponentVendor,
				ComponentVersion,
				ComponentRequiredInterface,
				ComponentRequires,
				Const,
				ConstType,
				DataStruct,
				Dot,
				Div,
				Enum,
	/*20*/EnumEntry,
				Eq,
				ErrorDef,
				ExternMethod,
				ForwardIFace,
				ForwardStruct,
				FunCall,
				Ge,
				Gt,
				Implementation,
	/*30*/ImportName,
				ImportNameAsType,
				Interface,
				InterfaceId,
				Le,
				Let,
				Lt,
				Message,
				MessageAdd,
				MessageClass,
	/*40*/MessageClassExtend,
				Method,
				MethodArg,
				Mul,
				Namespace,
				Ne,
				Neg,
				Nop,
				Not,
				Or,
	/*50*/Property,
				PropertyDecl,
				PropertyPlugin,
				PropertyPluginAdd,
				RefType,
				Shared,
				ShiftLeft,
				ShiftRight,
				String,
				Struct,
	/*60*/StructEntry,
				Sub,
				SysMethod,
				Typedef,
				Typecast,
				VarArg,
				Vendor,
				VendorId,
	};
};

}} //namespace idl::parser

#endif //Operations_hpp
