ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=multidmap

INCLUDES= \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/include \
	$(ROOT)/CommonFiles

METAFILE=mdmap.$(META)

SOURCESLIST=Sources.List

VCPROJ=MultiDMAP.vcproj

include $(ROOT)/Makefiles/Make.Plugin
