/*!
 * (C) "Kaspersky Lab"
 *
 * \file cleanersoapstub.h
 * \author Generated by createsoapheader.pl
 * \brief SOAP stub declaration and registration code
 */

#include "soapH.h"

#include "std/gsoap/stubrouter.h"

/* Declaration of functions */

int klcmptrsft_GetCompetitorSoftwareListStub(  struct soap *soap,  
	struct klcmptrsft_GetCompetitorSoftwareLisResponse&r);

int klcmptrsft_GetHostCompetitorSoftwareListStub(  struct soap *soap,  
	xsd__int	hostId,
	struct klcmptrsft_GetHostCompetitorSoftwareListResponse&r);

namespace KLCLEANER
{

	struct KLSTRT::SOAPStubFunc cleaner_funcs_ptrs[3]=
	{
		{ L"klcmptrsft_GetCompetitorSoftwareList",		 (void*)klcmptrsft_GetCompetitorSoftwareListStub },
		{ L"klcmptrsft_GetHostCompetitorSoftwareList",		 (void*)klcmptrsft_GetHostCompetitorSoftwareListStub },
		{ L"", NULL },
	};

	void RegisterGSOAPStubFunctions()
	{
		KLSTRT::RegisterGSOAPStubFunctions( cleaner_funcs_ptrs, (sizeof(cleaner_funcs_ptrs)/sizeof(cleaner_funcs_ptrs[0])) );
	}

	void UnregisterGSOAPStubFunctions()
	{
		KLSTRT::UnregisterGSOAPStubFunctions( cleaner_funcs_ptrs, (sizeof(cleaner_funcs_ptrs)/sizeof(cleaner_funcs_ptrs[0])) );
	}

} // end namespace KLCLEANER
