/*!
 * (C) "Kaspersky Lab"
 *
 * \file evsoapstub.h
 * \author Generated by createsoapheader.pl
 * \brief SOAP stub declaration and registration code
 */

#include "soapH.h"

#include "std/gsoap/stubrouter.h"

/* Declaration of functions */

int ev_RemoteSubscribeStub(  struct soap *soap,  xsd__int subsId, xsd__wstring localCompName, 
		SOAPComponentId *subscriber, SOAPComponentId *publisher, 
		xsd__wstring eventType, param__params eventBodyFilter, int sendToAgentSubs,
		int useOnlyLocalConnsFlag,
		int *result );

int ev_RemoteUnsubscribeStub(  struct soap *soap,  xsd__int remoteSubsId, int *result );

int ev_PublishEventStub(  struct soap *soap,  SOAPComponentId *eventPublisher, xsd__wstring	eventType, 
					param__params eventBody, time_t eventBirthTime, int eventLifeTime,
					struct SOAPComponentIdsList *processedCompsList, 
					struct SOAPSubsIdsList *remoteSubsIdsList,
					int *result );

namespace KLEV
{

	struct KLSTRT::SOAPStubFunc ev_funcs_ptrs[4]=
	{
		{ L"ev_RemoteSubscribe",		 (void*)ev_RemoteSubscribeStub },
		{ L"ev_RemoteUnsubscribe",		 (void*)ev_RemoteUnsubscribeStub },
		{ L"ev_PublishEvent",		 (void*)ev_PublishEventStub },
		{ L"", NULL },
	};

	void RegisterGSOAPStubFunctions()
	{
		KLSTRT::RegisterGSOAPStubFunctions( ev_funcs_ptrs, (sizeof(ev_funcs_ptrs)/sizeof(ev_funcs_ptrs[0])) );
	}

	void UnregisterGSOAPStubFunctions()
	{
		KLSTRT::UnregisterGSOAPStubFunctions( ev_funcs_ptrs, (sizeof(ev_funcs_ptrs)/sizeof(ev_funcs_ptrs[0])) );
	}

} // end namespace KLEV
