/*!
 * (C) "Kaspersky Lab"
 *
 * \file ftbridgesoapstub.h
 * \author Generated by createsoapheader.pl
 * \brief SOAP stub declaration and registration code
 */

#include "soapH.h"

#include "std/gsoap/stubrouter.h"

/* Declaration of functions */

int klftbridge_CreateReceiverStub(  struct soap *soap,  xsd__boolean		useUpdaterFolder,
						struct klftbridge_CreateReceiverResponse
							&r );

int klftbridge_ConnectStub(  struct soap *soap,  xsd__wstring			receiverId,
					    xsd__boolean			toMasterServer,
						struct klftbridge_ConnectResponse
							&r );

int klftbridge_GetFileInfoStub(  struct soap *soap, 
						xsd__wstring	receiverId,
						xsd__wstring	fileName,
						struct klftbridge_GetFileInfoResponse
							&r );

int klftbridge_GetNextFileChunkStub(  struct soap *soap, 
						xsd__wstring	receiverId,
						xsd__wstring	fileName,						
						xsd__unsignedLong	startFilePos,
						xsd__unsignedLong	neededSize,						
						struct klftbridge_GetNextFileChunkResponse
							&r );

int klftbridge_ReleaseReceiverStub(  struct soap *soap,  xsd__wstring			receiverId,
						struct klftbridge_ReleaseReceiverResponse
							&r );

namespace KLFTBRIDGE
{

	struct KLSTRT::SOAPStubFunc ftbridge_funcs_ptrs[6]=
	{
		{ L"klftbridge_CreateReceiver",		 (void*)klftbridge_CreateReceiverStub },
		{ L"klftbridge_Connect",		 (void*)klftbridge_ConnectStub },
		{ L"klftbridge_GetFileInfo",		 (void*)klftbridge_GetFileInfoStub },
		{ L"klftbridge_GetNextFileChunk",		 (void*)klftbridge_GetNextFileChunkStub },
		{ L"klftbridge_ReleaseReceiver",		 (void*)klftbridge_ReleaseReceiverStub },
		{ L"", NULL },
	};

	void RegisterGSOAPStubFunctions()
	{
		KLSTRT::RegisterGSOAPStubFunctions( ftbridge_funcs_ptrs, (sizeof(ftbridge_funcs_ptrs)/sizeof(ftbridge_funcs_ptrs[0])) );
	}

	void UnregisterGSOAPStubFunctions()
	{
		KLSTRT::UnregisterGSOAPStubFunctions( ftbridge_funcs_ptrs, (sizeof(ftbridge_funcs_ptrs)/sizeof(ftbridge_funcs_ptrs[0])) );
	}

} // end namespace KLFTBRIDGE
