/*!
 * (C) "Kaspersky Lab"
 *
 * \file gsynsoapstub.h
 * \author Generated by createsoapheader.pl
 * \brief SOAP stub declaration and registration code
 */

#include "soapH.h"

#include "std/gsoap/stubrouter.h"

/* Declaration of functions */

int klgsyn_GetNextItemsStub(  struct soap *soap, 
						xsd__wstring wstrIterator,
						xsd__int	nCount,
						struct klgsyn_GetNextItemsResponse& r);

int klgsyn_ReleaseIteratorStub(  struct soap *soap, 
						xsd__wstring wstrIterator,
						struct klgsyn_ReleaseIteratorResponse& r);

int klgsyn_AddSyncObjGStub(  struct soap *soap, 
					xsd__wstring	szwName,
					xsd__wstring	wstrSyncObjPath,
					xsd__int		nDirection,
					xsd__int		lGroup,
					xsd__int		lElapse,
					xsd__boolean	bCutoffChildren,
					struct klgsyn_AddSyncObjGResponse& r);

int klgsyn_AddSyncObjHStub(  struct soap *soap, 
					xsd__wstring		szwName,
					xsd__wstring		wstrSyncObjPath,
					xsd__int			nDirection,
					klgsyn_hostids		arrHosts,
					xsd__int			lElapse,					
					struct klgsyn_AddSyncObjHResponse& r);

int klgsyn_GetSyncInfoStub(  struct soap *soap, 
					long				lSync,
					klgsyn_wstrings		arrFields,
					struct klgsyn_GetSyncInfoResponse& r);

int klgsyn_RemoveSyncObjStub(  struct soap *soap, 
					xsd__int	lSync,
					struct klgsyn_RemoveSyncObjResponse& r);

int klgsyn_GetSyncHostsInfoStub(  struct soap *soap, 
					xsd__int			lSync, 
					klgsyn_wstrings		arrFields,
					xsd__int			lTimeout,
					struct klgsyn_GetSyncHostsInfoResponse& r);

int klgsyn_FindHostsStub(  struct soap *soap, 
					xsd__int			lSync, 
					xsd__wstring		wstrFilter,
					klgsyn_wstrings		arrFields,
					xsd__int			lTimeout,
					struct klgsyn_FindHostsResponse& r);

int klgsyn_GetSyncHostsInfo2Stub(  struct soap *soap, 
					xsd__int			lSync, 
					klgsyn_wstrings		arrFields,
					klgsyn_field_order_array arrFieldsToOrder,
					xsd__int			lTimeout,
					struct klgsyn_GetSyncHostsInfo2Response& r);

int klgsyn_FindHosts2Stub(  struct soap *soap, 
					xsd__int			lSync, 
					xsd__wstring		wstrFilter,
					klgsyn_wstrings		arrFields,
					klgsyn_field_order_array arrFieldsToOrder,
					xsd__int			lTimeout,
					struct klgsyn_FindHosts2Response& r);

int klgsyn_GetItemsCountStub(  struct soap *soap, 
						xsd__wstring wstrAccessor,
						struct klgsyn_GetItemsCountResponse& r);

int klgsyn_GetItemsChunkStub(  struct soap *soap, 
						xsd__wstring wstrAccessor,
						xsd__int	nStart,
						xsd__int	nCount,
						struct klgsyn_GetItemsChunkResponse& r);

int klgsyn_ReleaseChunkAccessorStub(  struct soap *soap, 
						xsd__wstring wstrAccessor,
						struct klgsyn_ReleaseChunkAccessorResponse& r);

namespace KLGSYN
{

	struct KLSTRT::SOAPStubFunc gsyn_funcs_ptrs[14]=
	{
		{ L"klgsyn_GetNextItems",		 (void*)klgsyn_GetNextItemsStub },
		{ L"klgsyn_ReleaseIterator",		 (void*)klgsyn_ReleaseIteratorStub },
		{ L"klgsyn_AddSyncObjG",		 (void*)klgsyn_AddSyncObjGStub },
		{ L"klgsyn_AddSyncObjH",		 (void*)klgsyn_AddSyncObjHStub },
		{ L"klgsyn_GetSyncInfo",		 (void*)klgsyn_GetSyncInfoStub },
		{ L"klgsyn_RemoveSyncObj",		 (void*)klgsyn_RemoveSyncObjStub },
		{ L"klgsyn_GetSyncHostsInfo",		 (void*)klgsyn_GetSyncHostsInfoStub },
		{ L"klgsyn_FindHosts",		 (void*)klgsyn_FindHostsStub },
		{ L"klgsyn_GetSyncHostsInfo2",		 (void*)klgsyn_GetSyncHostsInfo2Stub },
		{ L"klgsyn_FindHosts2",		 (void*)klgsyn_FindHosts2Stub },
		{ L"klgsyn_GetItemsCount",		 (void*)klgsyn_GetItemsCountStub },
		{ L"klgsyn_GetItemsChunk",		 (void*)klgsyn_GetItemsChunkStub },
		{ L"klgsyn_ReleaseChunkAccessor",		 (void*)klgsyn_ReleaseChunkAccessorStub },
		{ L"", NULL },
	};

	void RegisterGSOAPStubFunctions()
	{
		KLSTRT::RegisterGSOAPStubFunctions( gsyn_funcs_ptrs, (sizeof(gsyn_funcs_ptrs)/sizeof(gsyn_funcs_ptrs[0])) );
	}

	void UnregisterGSOAPStubFunctions()
	{
		KLSTRT::UnregisterGSOAPStubFunctions( gsyn_funcs_ptrs, (sizeof(gsyn_funcs_ptrs)/sizeof(gsyn_funcs_ptrs[0])) );
	}

} // end namespace KLGSYN
