/*!
 * (C) "Kaspersky Lab"
 *
 * \file nagnlstsoapstub.h
 * \author Generated by createsoapheader.pl
 * \brief SOAP stub declaration and registration code
 */

#include "soapH.h"

#include "std/gsoap/stubrouter.h"

/* Declaration of functions */

int klnagnlst_CallNetworkListTaskStub(  struct soap *soap, 
		xsd__wstring				listName,
		xsd__wstring				itemId,
		xsd__wstring				taskName,
		param__params				taskParams,
		struct klnagnlst_CallNetworkListTaskResponse&r);

int klnagnlst_GetItemFileInfoStub(  struct soap *soap, 
		xsd__wstring				listName,
		xsd__wstring				itemId,
		struct klnagnlst_GetItemFileInfoResponse&r);

int klnagnlst_GetItemFileChunkStub(  struct soap *soap, 
		xsd__wstring				listName,
		xsd__wstring				itemId,
		xsd__unsignedLong			startPos,
		xsd__unsignedLong			neededSize,
		struct klnagnlst_GetItemFileChunkResponse&r);

namespace KLNAGNLST
{

	struct KLSTRT::SOAPStubFunc nagnlst_funcs_ptrs[4]=
	{
		{ L"klnagnlst_CallNetworkListTask",		 (void*)klnagnlst_CallNetworkListTaskStub },
		{ L"klnagnlst_GetItemFileInfo",		 (void*)klnagnlst_GetItemFileInfoStub },
		{ L"klnagnlst_GetItemFileChunk",		 (void*)klnagnlst_GetItemFileChunkStub },
		{ L"", NULL },
	};

	void RegisterGSOAPStubFunctions()
	{
		KLSTRT::RegisterGSOAPStubFunctions( nagnlst_funcs_ptrs, (sizeof(nagnlst_funcs_ptrs)/sizeof(nagnlst_funcs_ptrs[0])) );
	}

	void UnregisterGSOAPStubFunctions()
	{
		KLSTRT::UnregisterGSOAPStubFunctions( nagnlst_funcs_ptrs, (sizeof(nagnlst_funcs_ptrs)/sizeof(nagnlst_funcs_ptrs[0])) );
	}

} // end namespace KLNAGNLST
