/*!
 * (C) "Kaspersky Lab"
 *
 * \file ptchsoapstub.h
 * \author Generated by createsoapheader.pl
 * \brief SOAP stub declaration and registration code
 */

#include "soapH.h"

#include "std/gsoap/stubrouter.h"

/* Declaration of functions */

int klptch_get_nagent_latest_patch_infoStub(  struct soap *soap, 
	param__params	nagent_data,
	struct klptch_get_nagent_latest_patch_infoResponse&r);

namespace KLPTCH
{

	struct KLSTRT::SOAPStubFunc ptch_funcs_ptrs[2]=
	{
		{ L"klptch_get_nagent_latest_patch_info",		 (void*)klptch_get_nagent_latest_patch_infoStub },
		{ L"", NULL },
	};

	void RegisterGSOAPStubFunctions()
	{
		KLSTRT::RegisterGSOAPStubFunctions( ptch_funcs_ptrs, (sizeof(ptch_funcs_ptrs)/sizeof(ptch_funcs_ptrs[0])) );
	}

	void UnregisterGSOAPStubFunctions()
	{
		KLSTRT::UnregisterGSOAPStubFunctions( ptch_funcs_ptrs, (sizeof(ptch_funcs_ptrs)/sizeof(ptch_funcs_ptrs[0])) );
	}

} // end namespace KLPTCH
