/*!
 * (C) "Kaspersky Lab"
 *
 * \file snmpagtsoapstub.h
 * \author Generated by createsoapheader.pl
 * \brief SOAP stub declaration and registration code
 */

#include "soapH.h"

#include "std/gsoap/stubrouter.h"

/* Declaration of functions */

int klsnmpagt_PutServerEventStub(  struct soap *soap, 
        struct klsnmpagt_event	event,
		struct klsnmpagt_PutServerEventResponse&r);

int klsnmpagt_SetAgentConnectionStub(  struct soap *soap, 
        xsd__wstring	wstrLocalName,
		xsd__wstring	wstrRemoteName,
		struct klsnmpagt_SetAgentConnectionResponse&r);

namespace KLSNMPAGT
{

	struct KLSTRT::SOAPStubFunc snmpagt_funcs_ptrs[3]=
	{
		{ L"klsnmpagt_PutServerEvent",		 (void*)klsnmpagt_PutServerEventStub },
		{ L"klsnmpagt_SetAgentConnection",		 (void*)klsnmpagt_SetAgentConnectionStub },
		{ L"", NULL },
	};

	void RegisterGSOAPStubFunctions()
	{
		KLSTRT::RegisterGSOAPStubFunctions( snmpagt_funcs_ptrs, (sizeof(snmpagt_funcs_ptrs)/sizeof(snmpagt_funcs_ptrs[0])) );
	}

	void UnregisterGSOAPStubFunctions()
	{
		KLSTRT::UnregisterGSOAPStubFunctions( snmpagt_funcs_ptrs, (sizeof(snmpagt_funcs_ptrs)/sizeof(snmpagt_funcs_ptrs[0])) );
	}

} // end namespace KLSNMPAGT
