/*!
 * (C) "Kaspersky Lab"
 *
 * \file srvstgssoapstub.h
 * \author Generated by createsoapheader.pl
 * \brief SOAP stub declaration and registration code
 */

#include "soapH.h"

#include "std/gsoap/stubrouter.h"

/* Declaration of functions */

int klsrvs_GetSharedFolderStub(  struct soap *soap,  
					void* _,
					struct klsrvs_GetSharedFolderResponse&r);

int klsrvs_ChangeSharedFolderStub(  struct soap *soap, 
					xsd__wstring		wstrFolder,
					struct klsrvs_ChangeSharedFolderResponse&r);

namespace KLSRVSTGS
{

	struct KLSTRT::SOAPStubFunc srvstgs_funcs_ptrs[3]=
	{
		{ L"klsrvs_GetSharedFolder",		 (void*)klsrvs_GetSharedFolderStub },
		{ L"klsrvs_ChangeSharedFolder",		 (void*)klsrvs_ChangeSharedFolderStub },
		{ L"", NULL },
	};

	void RegisterGSOAPStubFunctions()
	{
		KLSTRT::RegisterGSOAPStubFunctions( srvstgs_funcs_ptrs, (sizeof(srvstgs_funcs_ptrs)/sizeof(srvstgs_funcs_ptrs[0])) );
	}

	void UnregisterGSOAPStubFunctions()
	{
		KLSTRT::UnregisterGSOAPStubFunctions( srvstgs_funcs_ptrs, (sizeof(srvstgs_funcs_ptrs)/sizeof(srvstgs_funcs_ptrs[0])) );
	}

} // end namespace KLSRVSTGS
