/*!
 * (C) "Kaspersky Lab"
 *
 * \file syncsoapstub.h
 * \author Generated by createsoapheader.pl
 * \brief SOAP stub declaration and registration code
 */

#include "soapH.h"

#include "std/gsoap/stubrouter.h"

/* Declaration of functions */

int sync_putDataStub(  struct soap *soap, 
				xsd__wstring wstrID,
				param__params data,
				struct sync_putDataResponse &r);

int sync_CallStub(  struct soap *soap, 
				xsd__wstring wstrIDTo,
				xsd__wstring wstrIDFrom,
				param__params parInputData,
				struct sync_CallResponse &r);

int sync_startStub(  struct soap *soap, 
				xsd__wstring wstrType,
				xsd__wstring wstrIDFrom,
				param__params parOptions,
				struct sync_startResponse &r);

namespace KLSYNC
{

	struct KLSTRT::SOAPStubFunc sync_funcs_ptrs[4]=
	{
		{ L"sync_putData",		 (void*)sync_putDataStub },
		{ L"sync_Call",		 (void*)sync_CallStub },
		{ L"sync_start",		 (void*)sync_startStub },
		{ L"", NULL },
	};

	void RegisterGSOAPStubFunctions()
	{
		KLSTRT::RegisterGSOAPStubFunctions( sync_funcs_ptrs, (sizeof(sync_funcs_ptrs)/sizeof(sync_funcs_ptrs[0])) );
	}

	void UnregisterGSOAPStubFunctions()
	{
		KLSTRT::UnregisterGSOAPStubFunctions( sync_funcs_ptrs, (sizeof(sync_funcs_ptrs)/sizeof(sync_funcs_ptrs[0])) );
	}

} // end namespace KLSYNC
