ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=registrymapper

INCLUDES= \
	$(ROOT)/include/Prague \
	$(ROOT)/include \
	$(ROOT)/CommonFiles

METAFILE=regmap.$(META)

SOURCESLIST=Sources.List

VCPROJ=registrymapper.vcproj

include $(ROOT)/Makefiles/Make.Plugin
