#ifndef _MAILCHECKER_RETURN_CODES_H_
#define _MAILCHECKER_RETURN_CODES_H_

#define MC_OK					1

#define MC_SIGN_CHECK_ERR		2
#define MC_GET_FILE_NAME_ERR	3
#define MC_UNKNOWN_ERR			4
#define MC_CREATE_HANDLE_ERR	5
#define MC_CLOSE_HANDLE_ERR		6
#define MC_WSASTARTUP_ERR		7
#define MC_START_SERVER_ERR		8
#define MC_START_GUARD_ERR		9
#define MC_FSDRVINIT_ERR		10
#define MC_GETOSVERINFO_ERR		11
#define MC_DRVREGFAILED_ERR		12
#define MC_SEND_SOCKET_ERR		13
#define MC_RECV_SOCKET_ERR		14
#define MC_CHANGEDRV_STATE_ERR	15
#define MC_SOCKET_ERR			16
#define MC_BIND_ERR				17
#define MC_LISTEN_ERR			18
#define MC_SCAN_PORTS_ERR		19
#define MC_LOADMAL_ERR			20
#define MC_INITMAL_ERR			21
#define MC_CREATEWND_ERR		22
#define MC_ASYNSELECT_ERR		23

#endif