ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=filemap

INCLUDES= \
	$(ROOT)/include/Prague \
	$(ROOT)/include \
	$(ROOT)/CommonFiles

LIBRARIES= \
	klsys

DEPS= \
	$(ROOT)/CommonFiles/klsys

METAFILE=filemap.$(META)

SOURCESLIST=Sources.List

VCPROJ=filemap.vcproj

include $(ROOT)/Makefiles/Make.Plugin
