ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=uniarc

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/include/AV \
	$(ROOT)/CommonFiles

METAFILE=uniarc.$(META)

SOURCESLIST=Sources.List

VCPROJ=UniArc.vcproj

include $(ROOT)/Makefiles/Make.Plugin
