ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=l_llio

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/AV \
	$(ROOT)/include/Extract \
	$(ROOT)/include/ProductCore \
	$(ROOT)/CommonFiles

METAFILE=l_llio.$(META)

SOURCESLIST=Sources.List

VCPROJ=l_llio.vcproj

include $(ROOT)/Makefiles/Make.Plugin
