#define tag_port			'ccLK'
#define tag_env_param		'peLK'
//#define tag_inv_item		'iiLK'
//#define tag_pointer_page	'ppLK'
#define tag_sys_params		'psLK'
#define tag_proc_item		'piLK'
#define tag_proc_info		'PiLK'
#define tag_pl_200			'p2LK'
#define tag_active_image	'iaLK'
#define tag_get_ustring		'guLK'
#define tag_modinfo			'imLK'
#define tag_event			'beLK'
#define tag_instance_ctx	'ciLK'
#define tag_volume_ctx		'cvLK'
#define tag_stream_ctx		'csLK'
#define tag_streamh_ctx		'hsLK'
#define tag_tran_ctx		'ctLK'
#define tag_enobj_info		'ieLK'
//#define tag_tran_enfile	'ftLK'
#define tag_table_sys		'stLK'
#define tag_table_ev		'EtLK'
//#define tag_proc_info_path'tpLK'
//#define tag_proc_info_ex	'epLK'
#define tag_fid_request		'rfLK'
#define tag_name_norm		'nnLK'
#define tag_subcl_list		'lsLK'
#define tag_fid_tmp			'ttLK'
#define tag_user_buf		'buLK'
#define tag_table_reg		'rtLK'
#define tag_table_reg_ptr	'trLK'
#define tag_table_vol_ptr	'bvLK'
#define tag_lldisk			'llLK'
#define tag_read_buf		'rbLK'
#define tag_filter_tr		'tfLK'
#define tag_event_part		'egLK'
#define tag_object_request	'roLK'
#define tag_flt_event		'efLK'
#define tag_lldisk_id		'dlLK'
#define tag_user_buf_probe	'puLK'
#define tag_tmp_buf			'btLK'
#define tag_filters			'sfLK'
#define tag_filter			'ifLK'
#define tag_timing			'TTLK'
#define tag_timing_out		'oTLK'
#define tag_regkname		'nrLK'
#define tag_build_name		'nbLK'

#define tag_apprul1			'1rLK'
#define tag_apprul2			'2rLK'
#define tag_apprul3			'3rLK'
#define tag_apprul4			'4rLK'
#define tag_apprul5			'5rLK'
#define tag_apprul6			'6rLK'
#define tag_apprul7			'7rLK'
#define tag_apprul8			'8rLK'
#define tag_apprul9			'9rLK'
#define tag_apprulA			'ArLK'
#define tag_apprulB			'BrLK'
#define tag_apprulC			'CrLK'
#define tag_apprulD			'DrLK'
#define tag_addrule			'urLK'
#define tag_apprulF			'FrLK'

#define tag_client1			'1qLK'

#define tag_prepfltd1		'1wLK'

#define tag_specfunk1		'1xLK'
#define tag_specfunk2		'2xLK'
#define tag_specfunk3		'3xLK'
#define tag_specfunk4		'4xLK'

#define tag_sysio1			'1yLK'
#define tag_sysio2			'2yLK'
#define tag_sysio3			'3yLK'

#define tag_comm1			'1zLK'
#define tag_comm2			'2zLK'
#define tag_comm3			'3zLK'
#define tag_comm4			'YzLK'
#define tag_comm5			'ZzLK'
#define tag_comm6			'1aLK'

#define tag_operat1			'4zLK'
#define tag_operat2			'5zLK'

#define tag_operat3			'6zLK'
#define tag_operat4			'7zLK'
#define tag_env_param2		'8zLK'
#define tag_resolve1		'9zLK'
#define tag_resolve2		'AzLK'

#define tag_virt1			'BzLK'
#define tag_virt2			'CzLK'
#define tag_virt3			'DzLK'
#define tag_virt4			'CzLK'
#define tag_virt5			'DzLK'
#define tag_virt6			'EzLK'
#define tag_virt7			'FzLK'
#define tag_virt8			'GzLK'
#define tag_virt9			'HzLK'
#define tag_virtA			'IzLK'
#define tag_virtB			'KzLK'
#define tag_virtC			'LzLK'
#define tag_virtD			'MzLK'
#define tag_virtE			'NzLK'
#define tag_virtF			'OzLK'
#define tag_virtG			'VzLK'

#define tag_virtH			'QzLK'
#define tag_virtI			'RzLK'

#define tag_virtJ			'WzLK'

#define tag_prepflt1		'PzLK'
#define tag_prepflt2		'SzLK'
#define tag_prepflt3		'TzLK'
#define tag_prepflt4		'UzLK'
#define tag_prepflt5		'XzLK'
#define tag_prepflt6		'2aLK'
#define tag_prepflt7		'3aLK'
#define tag_prepflt8		'5aLK'
#define tag_prepflt9		'6aLK'
#define tag_prepfltA		'9aLK'
#define tag_prepfltB		'AaLK'
#define tag_prepfltC		'BaLK'
#define tag_prepfltD		'CaLK'

#define tag_set_sec_obj		'4aLK'
#define tag_crt_sect		'7aLK'
#define tag_crt_symb_lnk	'8aLK'




//last 'CaLK'


