ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=hashmd5

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/CommonFiles

METAFILE=hash_md5.$(META)

SOURCESLIST=Sources.List

VCPROJ=HashMD5.vcproj

include $(ROOT)/Makefiles/Make.Plugin
