; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.42 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	rdtick
_BSS	SEGMENT
?I@?1??rdtick@@9@9 DD 01H DUP (?)			; `rdtick'::`2'::I
; Function compile flags: /Odtp
_BSS	ENDS
_TEXT	SEGMENT
rdtick	PROC
	push	rdx
	rdtsc
	pop	rdx
	ret	0
rdtick	ENDP
_TEXT	ENDS
END
