ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=quantum

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/CommonFiles \

METAFILE=quantum.$(META)

SOURCESLIST=Sources.List

VCPROJ=quantum.vcproj

include $(ROOT)/Makefiles/Make.Plugin
