ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=base64p

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/CommonFiles

METAFILE=base64p.$(META)

SOURCESLIST=Sources.List

VCPROJ=base64p.vcproj

include $(ROOT)/Makefiles/Make.Plugin
