#include "avp_dos.h"
//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Avp32.rc
//
#define ID_AVP_SCANEND                  101
#define IDD_AVP32_DIALOG                102
#define ID_AVP_RELOADBASES              102
#define AVP_NEXTDISKDLG                 108
#define ID_AVP_START                    109
#define IDR_MAINFRAME                   128
#define IDD_TAB_PAGE1                   132
#define IDD_TAB_PAGE2                   133
#define IDD_TAB_PAGE3                   134
#define IDD_TAB_PAGE4                   135
#define IDD_TAB_PAGE5                   136
#define IDD_TAB_PAGE6                   137
#define IDI_ICON1                       138
#define IDI_ICON2                       139
#define IDI_ICON3                       140
#define IDI_ICON4                       141
#define IDI_ICON5                       142
#define IDI_ICON6                       143
#define IDI_ICON7                       144
#define IDI_ICON8                       145
#define IDI_ICON9                       146
#define IDI_ICON10                      147
#define IDI_ICON11                      148
#define IDI_ICON12                      149
#define IDD_FIND                        149
#define IDD_DIRECT_PATH                 150
#define IDI_ICON13                      150
#define IDD_DISINFECT                   152
#define IDD_ABOUT_DIALOG                153
#define IDR_AVI_SEARCH                  157
#define IDB_DAVID                       158
#define IDI_ICONOVERLAY                 160
#define IDD_SUPPORT_DIALOG              160
#define IDR_BIN_M                       161
#define IDD_CUSTOMIZE                   161
#define IDR_MAINFRAME2                  162
#define IDR_BIN_B                       162
#define IDR_AVI_OK                      177
#define IDR_AVI_INFECTED                178
#define IDR_POP_MENU                    181
#define IDB_KL                          183
#define IDI_ICON14                      184
#define IDD_DIALOG1                     185
#define IDC_TAB1                        1000
#define IDC_SCAN_NOW                    1001
#define IDC_STOP                        1002
#define IDC_TREE_COMP                   1010
#define IDC_CHECK_NETWORK               1011
#define IDC_NETWORK                     1011
#define IDC_CHECK_LOCAL                 1012
#define IDC_LOCAL                       1012
#define IDC_FLOPPY                      1013
#define IDC_COPYINFECTED                1014
#define IDC_WARNINGS                    1014
#define IDC_COPYSUSPICIOUS              1015
#define IDC_CA                          1015
#define IDC_ALL                         1015
#define IDC_REDUNDANT                   1016
#define IDC_PROGRAMS                    1017
#define IDC_DISINFECTDIALOG             1017
#define IDC_R_DISINFECT                 1017
#define IDC_DISINFECT_R                 1017
#define IDC_ALLFILES                    1018
#define IDC_R_SKIP                      1018
#define IDC_DISINFECT_D                 1018
#define IDC_USERDEF                     1019
#define IDC_DISINFECTAUTO               1019
#define IDC_R_DELETE                    1019
#define IDC_DISINFECT_DEL               1019
#define IDC_EDIT_EXT                    1020
#define IDC_DELETE                      1020
#define IDC_LIST1                       1021
#define IDC_REPORTONLY                  1021
#define IDC_STAT_LINE                   1023
#define IDC_ML                          1029
#define IDC_SOUND                       1030
#define IDC_TRACK                       1031
#define IDC_CUST_OTHER_MESSAGES         1031
#define IDC_SHOWOK                      1032
#define IDC_SMART                       1033
#define IDC_SHOWPACK                    1033
#define IDC_MEMORY                      1034
#define IDC_SECTORS                     1035
#define IDC_FILES                       1036
#define IDC_PACKED                      1037
#define IDC_EXTRACT                     1038
#define IDC_PROGRESS                    1039
#define IDC_MAILBASES                   1039
#define IDC_S_SECRORS                   1040
#define IDC_S_SECTORS                   1040
#define IDC_MAILPLAIN                   1040
#define IDC_S_FILES                     1041
#define IDC_S_DIRECTORIES               1042
#define IDC_S_ARCHIVES                  1043
#define IDC_S_PACKED                    1044
#define IDC_S_WARNING                   1045
#define IDC_S_SUSPICIOUS                1046
#define IDC_S_SUSPIC                    1046
#define IDC_S_VIRUS                     1047
#define IDC_S_BODIES                    1048
#define IDC_S_DISINFECTED               1049
#define IDC_S_CORRUPTED                 1050
#define IDC_S_ERRORS                    1051
#define IDC_S_IOERRORS                  1051
#define IDC_LIST_DISK                   1052
#define IDC_S_SPEED                     1052
#define IDC_S_DELETED                   1053
#define IDC_BUTTON_BROWSE               1055
#define IDC_COMBO_DIRECT_PATH           1056
#define IDC_OBJECT                      1057
#define IDC_VIRUS                       1058
#define IDC_INFECTFOLDER                1061
#define IDC_SUSPFOLDER                  1062
#define IDC_TIME                        1063
#define IDC_REPORT                      1065
#define IDC_REPORTFILE                  1066
#define IDC_APPEND                      1067
#define IDC_LIMIT                       1068
#define IDC_LIMITSIZE                   1069
#define ID_STATIC                       1070
#define ID_COPYRIGHT                    1070
#define IDC_VERSION                     1071
#define IDC_ANIMATE_SCAN                1072
#define IDC_UPDATE                      1072
#define IDC_SUPPORT                     1073
#define IDC_PRODUCT_NAME                1074
#define IDC_INFECTED_BY                 1075
#define IDC_ACTION_FRAME                1076
#define IDC_MASK_FRAME                  1077
#define IDC_SCANNED_FRAME               1078
#define IDC_FOUND_FRAME                 1079
#define IDC_STATIC_SECTORS              1080
#define IDC_STATIC_FILES                1081
#define IDC_STATIC_FOLDERS              1082
#define IDC_STATIC_ARCHIVES             1083
#define IDC_STATIC_PACKED               1084
#define IDC_STATIC_TIME                 1085
#define IDC_STATIC_VIRUSES              1086
#define IDC_STATIC_BODIES               1087
#define IDC_STATIC_DISINFECTED          1088
#define IDC_STATIC_WARNINGS             1089
#define IDC_STATIC_SUSPIC               1090
#define IDC_STATIC_CORRUPTED            1091
#define IDC_STATIC_IOERRORS             1092
#define IDC_INFECTED_OBJ                1093
#define IDC_STATIC_SPEED                1093
#define IDC_SUSP_OBJ                    1094
#define IDC_STATIC_DELETED              1094
#define IDC_REPORT_FRAME                1096
#define IDC_S_NAME                      1097
#define IDC_S_REG                       1098
#define IDC_S_ORG                       1099
#define IDC_S_REGNUMBER                 1100
#define IDC_COPYINFO                    1101
#define IDC_NAME                        1103
#define IDC_ORG                         1104
#define IDC_REGNUMBER                   1105
#define IDC_CUST_SINGLE_CLICK           1113
#define IDC_BUTTON_CUST                 1114
#define IDC_CHECK1                      1116
#define IDC_CUST_NEXT_DISK_PROMPT       1117
#define IDC_CUST_REDUNDANT_MESSAGE      1118
#define IDC_CUST_DELETE_ALL_MESSAGE     1119
#define IDC_CUST_STAT_AFTER_BEGIN       1120
#define IDC_CUST_STAT_AFTER_FINISH      1121
#define IDC_CUST_POPUP_AFTER_FINISH     1122
#define IDC_STRING                      1197
#define IDC_CASE                        1198
#define ID_FILE_LOADPROFILE             32772
#define ID_FILE_SAVEPROFILE             32773
#define ID_SCAN_SCANNOW                 32774
#define ID_SCAN_STOP                    32775
#define ID_AVP_CHANGETAB                32777
#define ID_HELP_ABOUTAVP32              32782
#define ID_SCAN_NOW                     32783
#define ID_STOP                         32784
#define ID_DISABLE_CONTROLS             32784
#define ID_FILE_SAVEPROFILEASDEFAULT    32785
#define ID_FIND                         32789
#define ID_FINDAGAIN                    32790
#define ID_ADD_DISKS                    32791
#define ID_TRACK                        32792
#define ID_POP_MARK                     32793
#define ID_POP_UNMARK                   32794
#define ID_POP_SCAN                     32795
#define ID_TOOLS_UPDATENOW              32796
#define ID_HELP_AVPONTHEWEB             32797
#define ID_CUSTOMIZE                    32798
#define ID_VIRLIST                      32799
#define IDS_NOTHING_FILES               37666
#define IDS_NOTHING_LOCATION            37667
#define IDS_LIST_ONAME                  37668
#define IDS_LIST_RESULT                 37669
#define IDS_DISINF_OFILE                37670
#define IDS_DISINF_OSECTOR              37671
#define IDS_DISINF_OMEM                 37672
#define IDS_SCANPROC_SPAWN              37673
#define IDS_SCANPROC_COMPLETE           37674
#define IDS_SCANPROC_INCOMPLETE         37675
#define IDS_SCANPROC_QUESTION           37676
#define IDS_ENTRY_FORMAT                37677
#define IDS_LOADBASE_FORMAT             37678
#define IDS_INTERFACE_FAULT             37679
#define IDS_KERNEL_FAULT                37680
#define IDS_OBJ_CORRUPTED               37681
#define IDS_OBJ_IOERROR                 37682
#define IDS_OBJ_DISINF_FAILED           37683
#define IDS_OBJ_ENCRYPTED               37684
#define IDS_OBJ_OK                      37685
#define IDS_OBJ_DISINFECTED             37686
#define IDS_OBJ_DELETED                 37687
#define IDS_OBJ_INFECTED                37688
#define IDS_OBJ_PACKED                  37689
#define IDS_OBJ_ARCHIVE                 37690
#define IDS_OBJ_WARNING                 37691
#define IDS_OBJ_SUSPICION               37692
#define IDS_OBJ_UNKNOWN                 37693
#define IDS_ERROR_FILE_OPEN             37694
#define IDS_ERROR_SET                   37695
#define IDS_ERROR_BASE                  37696
#define IDS_ERROR_KERNEL_PROC           37697
#define IDS_ERROR_LINK                  37698
#define IDS_REPORT_CUT                  37699
#define IDS_BOOT_SECTOR                 37700
#define IDS_MBR_SECTOR                  37701
#define IDS_REPORT_BANNER               37702
#define IDS_NEXT_CDROM                  37703
#define IDS_NEXT_FLOPPY                 37704
#define IDS_BASES_LOADED                37705
#define IDS_BASES_NOT_LOADED            37706
#define IDS_LOAD_PROFILE                37707
#define IDS_SAVE_PROFILE                37708
#define IDS_PROFILE_EXT                 37709
#define IDS_TAB_LOCATION                37710
#define IDS_TAB_OBJECTS                 37711
#define IDS_TAB_ACTIONS                 37712
#define IDS_TAB_OPTIONS                 37713
#define IDS_TAB_STATISTICS              37714
#define IDS_FLOPPY_DRIVE                37715
#define IDS_CDROM_DRIVE                 37716
#define IDS_ADD_FOLDER                  37717
#define IDS_SCAN_NOW                    37718
#define IDS_STOP                        37719
#define IDS_ABOUT                       37720
#define IDS_SUPPORT                     37721
#define IDS_ACTION                      37722
#define IDS_DISINFECT_DIALOG            37723
#define IDS_INFECTED_BY                 37724
#define IDS_DISINFECT_R                 37725
#define IDS_DISINFECT_D                 37726
#define IDS_DISINFECT_DEL               37727
#define IDS_COPYINFECTED                37728
#define IDS_APPLY_TOALL                 37729
#define IDS_TAB1_LOCAL                  37730
#define IDS_TAB1_NETWORK                37731
#define IDS_TAB1_FLOPPY                 37732
#define IDS_TAB1_ADD_FOLDER             37733
#define IDS_TAB2_MEMORY                 37734
#define IDS_TAB2_SECTORS                37735
#define IDS_TAB2_FILES                  37736
#define IDS_TAB2_PACKED                 37737
#define IDS_TAB2_EXTRACT                37738
#define IDS_TAB2_MASK_FRAME             37739
#define IDS_TAB2_SMART                  37740
#define IDS_TAB2_PROGRAMS               37741
#define IDS_TAB2_ALLFILES               37742
#define IDS_TAB2_USERDEF                37743
#define IDS_TAB3_WARNINGS               37744
#define IDS_TAB3_CA                     37745
#define IDS_TAB3_REDUNDANT              37746
#define IDS_TAB3_SHOWOK                 37747
#define IDS_TAB3_SHOWPACK               37748
#define IDS_TAB3_SOUND                  37749
#define IDS_TAB3_TRACK                  37750
#define IDS_TAB3_REPORT                 37751
#define IDS_TAB3_APPEND                 37752
#define IDS_TAB3_LIMIT                  37753
#define IDS_TAB5_SCANNED_FRAME          37754
#define IDS_TAB5_FOUND_FRAME            37755
#define IDS_TAB5_STATIC_SECTORS         37756
#define IDS_TAB5_STATIC_FILES           37757
#define IDS_TAB5_STATIC_FOLDERS         37758
#define IDS_TAB5_STATIC_ARCHIVES        37759
#define IDS_TAB5_STATIC_PACKED          37760
#define IDS_TAB5_STATIC_TIME            37761
#define IDS_TAB5_STATIC_VIRUSES         37762
#define IDS_TAB5_STATIC_BODIES          37763
#define IDS_TAB5_STATIC_DISINFECTED     37764
#define IDS_TAB5_STATIC_WARNINGS        37765
#define IDS_TAB5_STATIC_SUSPIC          37766
#define IDS_TAB5_STATIC_CORRUPTED       37767
#define IDS_TAB5_STATIC_IOERRORS        37768
#define IDS_TAB6_INFECTED_OBJ           37769
#define IDS_TAB6_SUSP_OBJ               37770
#define IDS_TAB6_REPORTONLY             37771
#define IDS_TAB6_DISINFECTDIALOG        37772
#define IDS_TAB6_DISINFECTAUTO          37773
#define IDS_TAB6_DELETE                 37774
#define IDS_TAB6_COPYINFECTED           37775
#define IDS_TAB6_COPYSUSPICIOUS         37776
#define IDS_NAME                        37777
#define IDS_ORGANIZATION                37778
#define IDS_REGNUMBER                   37779
#define IDS_REGISTERINFO                37780
#define IDS_SUPPORT_DLG                 37781
#define IDS_EXPIR_ALARM                 37782
#define IDS_EXPIRIED                    37783
#define IDS_SET_OUTOFDATE               37784
#define IDS_SHURE_DELETEALL             37785
#define IDS_NEEDTORESTART               37786
#define IDS_ASK_DELETE                  37787
#define IDS_ASK_DELETE_ALL              37788
#define IDS_ASK_DELETE_SKIP_ALL         37789
#define IDS_CURE_SECTOR                 37790
#define IDS_MEMORY                      37791
#define IDS_REMOTE_LAUNCH               37792
#define IDS_KEY_PLATHFORM_NT            37793
#define IDS_KEY_PLATHFORM_95            37794
#define IDS_ADMIN_RIGHTS                37795
#define IDS_KEY_ABSENT                  37796
#define IDS_MIN_CAPTION                 37797
#define IDS_TAB5_STATIC_DELETED         37798
#define IDS_TAB5_STATIC_SPEED           37799
#define IDS_ASK_REDUNDANT               37800
#define IDS_LAST_UPDATE                 37801
#define IDS_FINDNEXT                    37802
#define IDS_FIND                        37803
#define IDS_CANCEL                      37804
#define IDS_CASE                        37805
#define IDS_OBJ_DISKOUTOFSPACE          37806
#define IDS_OBJ_PROTECTED               37807
#define IDS_TAB2_MAILPLAIN              37808
#define IDS_TAB2_MAILBASES              37809
#define IDS_AVP_URL                     37810
#define IDS_SELF_DISINFECTED            37811
#define IDS_SELF_DISINFECTION_FAILED    37812
#define IDS_NEED_REBOOT                 37813
#define IDS_OBJ_LOCKED                  37814
#define IDS_OBJ_NO_ACCESS               37815
#define IDS_CUST_SINGLE_CLICK           37816
#define IDS_CUST_NEXT_DISK_PROMPT       37817
#define IDS_CUST_REDUNDANT_MESSAGE      37818
#define IDS_CUST_DELETE_ALL_MESSAGE     37819
#define IDS_CUST_STAT_AFTER_BEGIN       37820
#define IDS_CUST_STAT_AFTER_FINISH      37821
#define IDS_CUST_POPUP_AFTER_FINISH     37822
#define IDS_CUSTOMIZE_BTN               37823
#define IDS_CUSTOMIZE_DLG               37824
#define IDS_CUST_OTHER_MESSAGES         37825
#define IDS_REG_SECURITY_WEAK           37826
#define IDS_REG_IE_OPTIONS              37827
#define IDS_REG_MACRO_PROTECTION_DISABLED 37828
#define IDS_REG_W97_OPTIONS             37829
#define IDS_REG_E97_OPTIONS             37830
#define IDS_REG_W2000_OPTIONS           37831
#define IDS_REG_E2000_OPTIONS           37832
#define IDS_REG_PP97_OPTIONS            37833
#define IDS_REG_PP2000_OPTIONS          37834
#define IDS_AUTH_FAILED                 37835
#define IDS_AUTH_CONTINUE               37836
#define IDS_FULL_NAME                   37837
//////////////////////////////////////////////
// Priority
#define IDS_TAB3_PRIORITY_TEXT          20100
#define IDS_TAB3_PRIORITY_LOW           20101
#define IDS_TAB3_PRIORITY_HIGH          20102

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        187
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1117
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
