ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=unstored

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/CommonFiles \

METAFILE=unstored_trans.$(META)

SOURCESLIST=Sources.List

VCPROJ=UnStored.vcproj

include $(ROOT)/Makefiles/Make.Plugin
