ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=substio

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/CommonFiles

METAFILE=SubstIO.$(META)

SOURCESLIST=Sources.List

VCPROJ=substio.vcproj

include $(ROOT)/Makefiles/Make.Plugin
