//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TrainingWizard.rc
//
#define IDS_PROJNAME                    100
#define IDR_ADDIN                       101
#define IDR_PAGE_ANTISPAM               103
#define IDS_TITLEPage                   105
#define IDS_HELPFILEPage                106
#define IDS_DOCSTRINGPage               107
#define IDR_PAGE                        108
#define IDB_BITMAP1                     201
#define IDI_ICON_KAV                    203
#define IDB_BITMAP_TREE_FOLDERS         208
#define IDB_BITMAP_WZ_WATERMARK         211
#define IDB_BITMAP_WZ_WATERMARK_WELLCOME 212
#define IDD_MCOE_DIALOG_ANTISPAM        1000
#define IDD_MCOE_DIALOG_BROWSE_FOR_FOLDER 1001
#define IDD_MCOE_DIALOG_TRAINING_WZ0    1002
#define IDD_MCOE_DIALOG_TRAINING_WZ1    1003
#define IDD_MCOE_DIALOG_TRAINING_WZ3    1004
#define IDC_MCOE_MAINCAPTION            1099
#define IDC_MCOE_STATIC_CAPTION_WZ0     1100
#define IDC_MCOE_STATIC_SUBCAPTION_WZ0  1101
#define IDC_MCOE_STATIC_PRESS_NEXT      1102
#define IDC_MCOE_STATIC_CAPTION_WZ1     1103
#define IDC_MCOE_STATIC_SUBCAPTION_WZ1  1104
#define IDC_MCOE_TREE_FOLDERS           1105
#define IDC_MCOE_CHECK_INCLUDE_SUBFOLDERS 1106
#define IDC_MCOE_BUTTON_CLEAR           1107
#define IDC_MCOE_STATIC_CAPTION_WZ2     1108
#define IDC_MCOE_STATIC_SUBCAPTION_WZ2  1109
#define IDC_MCOE_STATIC_CAPTION_WZ3     1110
#define IDC_MCOE_STATIC_SUBCAPTION_WZ3  1111
#define IDC_MCOE_PROGRESS_TRAINING      1112
#define IDC_MCOE_STATIC_NOW_PROCCESSING 1113
#define IDC_MCOE_EDIT_PROCCESSING_FOLDER 1114
#define IDC_MCOE_STATIC_TIME_LEFT       1115
#define IDC_MCOE_EDIT_TIME_LEFT         1116
#define IDC_MCOE_STATIC_FOLDERS         1117
#define IDC_MCOE_STATIC_STATUS          1118
#define IDC_MCOE_STATIC_STATUS_MC       1119
#define IDC_MCOE_STATIC_CHANGE_SETTINGS 1120
#define IDC_MCOE_STATIC_CHANGE_SETTINGS_LINK 1121
#define IDC_MCOE_STATIC_CS_GRP_NAME     1122
#define IDC_MCOE_COMBO_CS_ACTION        1123
#define IDC_MCOE_STATIC_CS_TO_FOLDER    1124
#define IDC_MCOE_EDIT_CS_FOLDER         1125
#define IDC_MCOE_BUTTON_CS_BROWSE       1126
#define IDC_MCOE_CHECK_CS_MARK_READ     1127
#define IDC_MCOE_STATIC_PS_GRP_NAME     1128
#define IDC_MCOE_COMBO_PS_ACTION        1129
#define IDC_MCOE_STATIC_PS_TO_FOLDER    1130
#define IDC_MCOE_EDIT_PS_FOLDER         1131
#define IDC_MCOE_BUTTON_PS_BROWSE       1132
#define IDC_MCOE_CHECK_PS_MARK_READ     1133
#define IDC_MCOE_STATIC_TRAINIG         1134
#define IDC_MCOE_BUTTON_TRAINING        1135
#define IDC_MCOE_STATIC_STATUS_MC2      1137
#define IDC_MCOE_STATIC_CHANGE_SETTINGS2 1138
#define IDC_MCOE_STATIC_CHANGE_SETTINGS3 1139

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        213
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         1140
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
