ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=klavstl_test

INCLUDES= \
	$(ROOT)/include

VCPROJ=klavstl_test.vcproj

SOURCESLIST=Sources.List

include $(ROOT)/Makefiles/Make.Executable

