ROOT:=../..

include $(ROOT)/Makefiles/Make.Config

TARGET=scheduler

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/ProductCore \
	$(ROOT)/CommonFiles

METAFILE=schedule.$(META)

VCPROJ=schedule.vcproj

SOURCESLIST=Sources.List

include $(ROOT)/Makefiles/Make.Plugin
