ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=stdcompare

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/CommonFiles

METAFILE=stdcomp.$(META)

SOURCESLIST=Sources.List

VCPROJ=stdcompare.vcproj

include $(ROOT)/Makefiles/Make.Plugin
