ROOT:=../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=klavsyslib

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/klava \
	$(ROOT)/include/klava/bases


VCPROJ=klavsyslib.vcproj

SOURCESLIST=Sources.List

include $(ROOT)/Makefiles/Make.Archive

