ROOT:=../../../..

include $(ROOT)/Makefiles/Make.Config

TARGET=unshrink

INCLUDES= \
	$(ROOT)/include \
	$(ROOT)/include/Prague \
	$(ROOT)/include/Extract \
	$(ROOT)/CommonFiles

METAFILE=UNSHRINK_trans.$(META)

SOURCESLIST=Sources.List

VCPROJ=UNSHRINK.vcproj

include $(ROOT)/Makefiles/Make.Plugin
