/* Generated by Together */

#ifndef ISTORAGER_H
#define ISTORAGER_H

namespace KasperskyLicensing {

/** @interface */
class IStorageR
{
public:

	typedef Enumerator<const char_t*> NameEnumerator;

	/**
	 * loads stored object by given name
	 */
	virtual AutoPointer<IObjectImage> LoadObject(const char_t* name) const = 0;

	/**
	 * returns stored object names
	 */
	virtual NameEnumerator GetObjectNames() const = 0;

private:

	/** @link dependency
	 * @stereotype instantiate*/
	/*# IObjectImage lnkIStoredObject; */
};

} // namespace KasperskyLicensing

#endif // ISTORAGER_H
