# -*- Makefile -*- Time-stamp: <03/07/11 13:08:45 ptr>
# $Id: Makefile.inc,v 1.20 2004/04/08 09:20:26 ptr Exp $

PRGNAME = stdtest
MAJOR = 0
MINOR = 1
PATCH = 0
SRC_CC = ../../tst/kltester/data.cpp ../../tst/kltester/datareader.cpp\
	 ../../tst/kltester/main.cpp ../../tst/kltester/testdata.cpp\
	 ../../tst/kltester/testsset.cpp\
	 err/errtest.cpp\
	 par/partest.cpp\
	 sch/schtest.cpp sch/schtestfunc.cpp\
	 testing/testing.cpp\
	 thr/thrtest.cpp\
	 tp/tptest.cpp\
	 tp/queuetest.cpp\
	 stdtest.cpp



